### ISSUE TITLE
C++ support

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars-runner-cli#10]

**Comment by bkaes** [comment]
What's actually necessary to add a new language? A docker image, a test framework, and…? The repository/readme doesn't give too much information about the process, so it's kind of hard to add features as a non-indoctrinated user.

**Comment by schwaerz** [comment]
Would be willing to support - if I only knew how.

**Comment by siJordan** [comment]
Is this still being perused?

**Comment by Kavignon** [comment]
So guys, what's required here for C++ ?

**Comment by tomsmeding** [comment]
Same here, willing to help, but are there any pointers what to do?

**Comment by jhoffner** [comment]
C++ would be awesome. Its the highest voted next language. 

A few notes about what is needed:
- systems.docker was taken out of the Makefile due to some issues on travis. I think this image could be cleaned out, NASM & ARM probably dont need to be there. I don't recall if those were what was causing the issue. So the first step is to add `systems.docker` back into the `Makefile`, and fix any build issues that were happening. 
- pick a test framework to implement. [Igloo](http://igloo-testing.org/) is one idea. I'm not sure if its popular enough to have as our default framework, i just mentioned it because it uses BDD, like most of our other languages do.
- update `cpp.js` to support testIntegration mode. This is where you will integrate the test framework that you choose. Make sure to add tests to `cpp_spec.js`. 
- update `docker-compose.yml` to have a `cpp` and `cpp_test` service. This will make your development life a lot easier. To run your test suite you should just need to do `docker-compose run cpp_test`
- add an `examples/cpp.yml` file. Make sure to add it to the spec file (see `javascript_spec.js` for an example)

**Comment by Kavignon** [comment]
I'll be real.  VB and F# are going to take some time I'm guessing.  As fun
and cool it would be to be guy adding C++,  I think I'll have to let that
one go to Tom.  I don't know hot you feel about that.  I'm doing the GSOC16
plus working part time. I can't work full-time adding the rest of the MSFT
suite. Although,  I'll be glad to give you a hand I'd you need it and I can
assist you for that particular step/question!

**Comment by Dan-Nolan** [comment]
@tomsmeding - Let me know if you're definitely interested in this. I was planning to try and implement it this week, but if you're going to spearhead it I'll look into adding another language. 😃

**Comment by Kavignon** [comment]
This week? Its that short to do it?

**Comment by Dan-Nolan** [comment]
Couldn't say. I do intend to start something this week though.

**Comment by jhoffner** [comment]
Yeah its usually not more than 3 - 8 hours to implement a language, if you know what you are doing - meaning you are familiar with the language, test framework and familiar with the runner code. 

It mostly depends on how easy it is to get the test framework to output the correct format.

**Comment by tomsmeding** [comment]
I was looking to spend some time looking at this, but I can't really predict how much time I have the coming days/weeks, due to exams coming up. So I can definitely have a look at it, but no guarantees... If you'd like guarantees, I don't think I'm of much help here, sadly.

**Comment by javatlacati** [comment]
@Dan-Nolan Congratulations! it's extremately fast :D Class support [is pretty fine](https://www.codewars.com/kata/sum-of-numbers-from-0-to-n). And you can even [do some Assembly](https://www.codewars.com/kumite/53ee35a2ba190003f0000626?sel=575bdb2f81ce1de85100006c)! :cake:

**Comment by javatlacati** [comment]
The only small detail I've found is that you can't have any main method, not even adding a `#define main myfunction`.
Perhaps to use main function you should add some namespace, perhaps you can enhace it a little bit to add by default the namespace `solution` so it can be run as `solution::main`.

**Comment by Dan-Nolan** [comment]
You should be able to use `main` anywhere that tests aren't provided, but for Igloo integration we need the `main` entry point to run the test suite. 

I have to say, after playing around with Igloo a bit, it seems like it would be ideal to come up with a Codewars-Style C++ Test framework as well. I'll save that for another issue though :smile:

**Comment by javatlacati** [comment]
So... it seems that we couldn't train some others on the use of main function... too bad :disappointed:

**Comment by Kavignon** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Kevin

Confirm that you know Kevin: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=USsc429X&invitationId=6208290945515995137&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivzc5era%7Eer








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivzc5era-er&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEltrMhnN0Z0AAAAVihH1VOwgf7w77v4deljGlBLtwNaAQK6mIo5YJE7cjuLv8uYSr3SW5IQ-BiT1n420RBL_1Tbi7dSaIB0mD1ZrFF4I0IwHjGWl1a-QFa2kCn2b5il2CCbt_v31E76XMUS3kfDz57Pa0Z5GgpXMkdCfoHefh4dgzHQuBeN4P3evzfzzIgWEiglqp8A81Y0u063mHKvUsnjQ&eid=0-ivzc5era-er


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivzc5era-er&a=customerServiceUrl&ek=invite_guest

© 2016 LinkedIn Corporation, 1000 West Maude Avenue, Sunnyvale, CA 94085. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Kevin would like to stay in touch on LinkedIn.

Kevin Avignon
Senior Software Engineer Student 
Montreal, Canada Area

View profile https://www.linkedin.com/e/v2?e=0-ivzc6uaz-vl&a=publicProfile&tracking=eml-guest-invite-pprofile-link-cta&ek=invite_guest&vanityName=kevinavignon

Confirm that you know Kevin https://www.linkedin.com/comm/start/accept-invitation?sharedKey=GAkZbq8T&invitationId=6208290946073845760&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-112-null-null-0%7Eivzc6uaz%7Evl


.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=0-ivzc6uaz-vl&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&li=119&m=unsub&ts=unsub&loid=AQFjNl0MSMS6HwAAAVihIFa4zSdae-QUrf6eb7vpqU33zR7Qs7aOk08QM8o0Az22fCGdIK-jubNu1Nr-GlHAJlS3KOql3kX2mZL0JqZr43qVYvd7f3cjdY6UKG3MjeVZlctl6_dyK5iYHJ0D8_kFf0CshvjNjb5MFy5bFvDUsUYyk1_jTavoMC5FIV719jdKiWyOcrOTJiKPsRpEB65zKS32Zg&eid=0-ivzc6uaz-vl

Help: https://www.linkedin.com/e/v2?e=0-ivzc6uaz-vl&a=customerServiceUrl&ek=invite_guest&li=118&m=footer&ts=help&articleId=67


You are receiving Invitation emails. LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to reply@reply.github.com.

© 2016 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Kevin Avignon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=GAkZbq8T&invitationId=6208290946073845760&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-c3ozzr%7Eiw6msilx%7Epk

View Kevin Avignon&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=GAkZbq8T&invitationId=6208290946073845760&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-c3ozzr%7Eiw6msilx%7Epk





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=c3ozzr-iw6msilx-pk&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=c3ozzr-iw6msilx-pk&loid=AQH_DhCKjdNCiwAAAVi8NyN8tSUePSZvsJyi7E0xSZOtlznSKtX2gUMNWFgm36f7GtCNhs1gVYjuxnZ7IhCFELnJWf3H_hb876gUkN5WWzFBDuqsX4eauRw4-Kc_5_YTke1wsDZ8ARZbqf-5rir0D6XIHP4027GBR0naeDidIWigbXWtd80gHqxrFu87hWbtg7FNde1xdOTUWXcfc8U8-xYRcC-oXw

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=c3ozzr-iw6msilx-pk&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Dan-Nolan** [comment]
@Kavignon - Is this happening on purpose?

**Comment by Kavignon** [comment]
I have no idea why this is happening. There seems to be a bug with my Linkedin account. Account that I saw in possible connections to add where added without my consent and now this... 
I'm really sorry.

**Comment by Dan-Nolan** [comment]
Not at all, no harm done! 😄 
I just figured I'd call your attention to it, just in case you hadn't noticed it.
