### ISSUE TITLE
what TDD test framework does codewars use for javascript?

### ISSUE THREAD

**Issue by ralyodio** [Codewars/codewars-runner-cli#107]

**Comment by kgashok** [comment]
@xcthulhu I get timeouts when I use `assertSimilar` in this kata - https://www.codewars.com/kata/exclusive-presentations/train/javascript

What am I doing wrong?

**Comment by mdarmani** [comment]
```
function myFunction() {
  var myObject = {
    objProperty: "string",
    objMethod: function() {
      return myObject.objProperty;
		}
  };
  
  return myObject.objMethod();
};
```

How would I assert that myObject.objMethod() was called using CW test framework? All I can do now is assert if myFunction returns "string";

**Comment by jhoffner** [comment]
@mdarmani The CW test framework assertion features are rather limited. However the framework supports ChaiJS and the chai-spies library is already loaded on the image. 

http://chaijs.com/plugins/chai-spies/

**Comment by mdarmani** [comment]
@jhoffner thanks, it worked after I import the Chai-Library using:

var assert = require('chai').assert;
assert.propertyVal({myObject: 'objMethod'}, 'myObject', 'objMethod');
