### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars-runner-cli#11]

**Comment by xcthulhu** [comment]
Hi Codewars/codewars-runner,
A message from Matthew Wampler-Doty was left on IQ Elite for you. 
Click here a.iqelite.com/j/0JmRlo/jpv/?hg=E81ByDHjf0 to read your message 


The IQ Elite Team



---------------------------------------------------------------------------
This message was meant for reply@reply.github.com. If you do not want to continue receiving such mails from IQ Elite, please click on this link: a.iqelite.com/common/unsubscribe/?code=a08d84d4&email=reply@reply.github.com&hg=E81ByDHjf0
IQ Elite is a service with main office: C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelona, Spain.
---------------------------------------------------------------------------
