### ISSUE TITLE
Escape character's for user's console.log

### ISSUE THREAD

**Issue by tianshuo** [Codewars/codewars-runner-cli#127]
If the user writes `console.log('<PASSED::>All tests passed')` this shouldn't be a new passed test.
By escaping < and >, this can be avoided.

**Comment by javatlacati** [comment]
This seems solved can you check again?

**Comment by jhoffner** [comment]
Not sure that this is. We could wrap the "users" `console.log` but there is nothing we can do to prevent them from just interacting with `process.stdout` directly.

**Comment by javatlacati** [comment]
It doesn't bypass any Kata so printing all test are passed is not an issue :)

**Comment by mlefebvresopra** [comment]
Not really... Since the test framework uses console.log !
If the user writes 
```
const log = console.log;
console.log=(...args) => {
    args.unshift('<PASSED::>'); 
    Reflect.apply(log, console, args);
};
```
Then the test framework will log things like 
```
<PASSED::><FAILED::> Expected 3, got : undefined
```
