### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars-runner-cli#132]
At the moment, it's not really clear what has to be provided to add support for a new language or to upgrade to a newer version of a compiler/runtime. Apparently one needs a docker image (or change the full image?), and a test framework. But this doesn't include building/running strategies for the actual tests, which are essential.

I'm not sure whether those informations are considered *internal* by you or whether they're simply missing in _this_ repository, but they're required to create support for something new.

**Comment by jhoffner** [comment]
The project is now better setup for contributions.
