### ISSUE TITLE
F# support

### ISSUE THREAD

**Issue by dtchepak** [Codewars/codewars-runner-cli#133]
I'd love to help get F# katas running in codewars. AFAICT the .NET runner already supports F#, so I was wondering what else needs to be done to get to the point where we can start porting katas over to F#?

**Comment by jhoffner** [comment]
The project is now better setup for contributions if you are still interested. Test integration and examples still need to be added.

**Comment by Kavignon** [comment]
What is the actual state? I'd love to work on this as a summer project :D

**Comment by dtchepak** [comment]
Hi @Kavignon,
I haven't had a chance to start this. You are welcome to pick it up. 😄

**Comment by Kavignon** [comment]
@dtchepak  What's the current state ? All I have to do is to make the tests pass ? Are they any ? 
Can someone just walk me through the initial steps here and I'll be on my way to the top

**Comment by dtchepak** [comment]
I'm not sure of the details, but the [top-level steps are described in the README](https://github.com/Codewars/codewars-runner-cli#how-to-add-a-new-language).

**Comment by Kavignon** [comment]
Great. I gladly volunteer as tribute for F#

**Comment by herrerapedro** [comment]
Hey Kavignon, I got free cycles. I can contribute if you need any help.

**Comment by Kavignon** [comment]
I'll try to get started either this week-end or the next one and will keep you posted! Thanks for reaching out, I appreciate it :) @herrerapedro

**Comment by Kavignon** [comment]
I'll get into the e-how to understand what I need to do and the work will be started tomorrow morning.  @jhoffner  Since you said it'd take about 3-8 hours, I expect to be done with max Friday morning !
