### ISSUE TITLE
Unit tests pass automatically on any error

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#137]
For Java, JUnit4 tests pass automatically when error is launched even with `trycatch`. You can take for example [this Kata](http://www.codewars.com/kata/proficient-classic-hello-world/solutions) where Merlyn solution should not pass at all.
The testing pattern that if launches any exception fails the tests can't be used.

PS: I don't know why you can't add this issue yourself :broken_heart:

**Comment by jhoffner** [comment]
Thanks for filling over here. I wasn't sure if you were willing to look into yourself, since you likely weren't aware of this project. None of us are Java guys so it might take a bit for us to get to it.

**Comment by javatlacati** [comment]
He he even my mother calls me the Java man, I'll try it as soon I get familiarized with your xml templates for errors

**Comment by javatlacati** [comment]
If you run java_test.clj will find some errors:

>initializationError(Bar)

>Test class should have exactly one public constructor

>initializationError(Bar)

>No runnable methods

on this code:
```
(deftest java-basic
  (testing "-main can handle a very basic java code and fixture"
    (with-in-str
      (json/generate-string
       {:language "java"
        :code "class Foo {}"
        :fixture "class Bar {}"})
      (is (= org.junit.runner.Result (class (-main)))))))
```
if you add constructor it asks for method body, if you add constructor body( `{}` ) it will launch exactly the first error.

**Comment by javatlacati** [comment]
commit 6ab4b960278c7f1d91e9e1a583ade63e1297f8e3 fixed partially preventingcode that only throwed an exception to pass.

**Comment by javatlacati** [comment]
I've found a workaround, I think it's because you are running Java trough leningen.

**Comment by jhoffner** [comment]
What is the workaround? Is it something we can implement to prevent this? 

We plan to move off of lenignen and onto using groovyserv soon.

**Comment by javatlacati** [comment]
I've throwed exception at every test and for the last test there's a weird bug in the runner it duplicates last output when you pass nothing to a varargs function so I had to print redirect the output stream and then start capturing it was tricky hence you can modify your fixture template to use always a trycatch and anyway throw the catched exception so it can be detected by the runner.

I really hope that groovy can handle it without further modification.

**Comment by kazk** [comment]
Closing this because we no longer use `jvm-runner` for Java. Please open a new issue if this is not fixed.
