### ISSUE TITLE
make node fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by choxi** [Codewars/codewars-runner-cli#139]
I'm getting an error when I try to run `make node` on a Digital Ocean instance running Ubuntu 14.04 and Docker 1.11.1. The error I get is:

```
$ make node

...

  1) typescript runner example challenges should have a passing algorithms example:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.


  2) typescript runner mocha bdd should handle outputting objects:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.


  3) typescript runner mocha bdd should handle failures:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.


  4) typescript runner mocha bdd should handle errors:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.




The command '/bin/sh -c mocha -t 5000 test/runners/{javascript,coffeescript,typescript}_spec.js' returned a non-zero code: 4
make: *** [node] Error 1
```

It worked fine locally on my Mac running OS X 10.11.4.

**Comment by jhoffner** [comment]
The timeout usually only gets exceeded when running on slower or over worked hardware. Is your instance doing something else? It also might not have enough memory.

**Comment by choxi** [comment]
That looks correct, looks like the CPU is maxing out when I run `make node`.

```
$ top
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
2724 1000      20   0  952832 100520   8676 R  90.6  4.9   0:02.73 node
```

Thanks for the tip! I'll close this out.

**Comment by jhoffner** [comment]
Cool. You can also try increasing the timeout. If we find that the timeout is too low for many people due to hardware limitations then I'm fine with increasing the timeouts to give a little breathing room. You can just change `-t 5000` to something like `-t 8000`. If the tests need more time than that, something is really wack on the machine.
