### ISSUE TITLE
what's the best way to parse the test suite output?

### ISSUE THREAD

**Issue by choxi** [Codewars/codewars-runner-cli#140]
It looks like the test suite output comes in a log-like format in case the tests hit an exception before they complete, what's the best strategy for parsing that output into structured data? I'm curious how you take the test suite output format and use it on codewars.com, do you end up just writing a parser that take this:

```
<DESCRIBE::>Test Example
<DESCRIBE::>The Number 1
<IT::>should equal 1
<PASSED::>Passed
<COMPLETEDIN::>
<COMPLETEDIN::>
<COMPLETEDIN::>
```

and turn it into something like:

```javascript
{
  describe: {
    describe: {
      it: {
        result: "passed",
        completedin: null
      }
    }
  }
}
```

Or is there a better strategy than writing a parser?

**Comment by jhoffner** [comment]
Yes Codewars has a parser that lives outside of the project. It doesn't parse into JSON though, it parses directly into the basic HTML structure that is used to render the output. Strive on the other hand is kind of like Codewars 2.0 in terms of its codebase, so it is leveraging a JSON parser and then parses that data using Angular.

**Comment by choxi** [comment]
Got it, thank you!

**Comment by jhoffner** [comment]
NP. BTW the JSON format that we used was something like:
```
{
  items: [{
      t: "describe", 
      v: "Foo",
      items: [{
        t: "it",
        v: "should do stuff",
        items: [{
           t: "success",
           v: "Test Passed" 
         },{
           t: "console",
           v: "Some direct output" 
         }]
    }]
}
```
