### ISSUE TITLE
running tests against an entire application

### ISSUE THREAD

**Issue by choxi** [Codewars/codewars-runner-cli#141]
Right now, the runner is limited to one blob of code and one blob of tests. Are there any plans to support running tests against an entire application? If you could pass in a directory for an app and run tests against it, you could support frameworks like Rails, Express, React, etc.

It could be as simple as mounting the app directory as a volume into a container, and using a modified runner script to output the test results. I might try to put that together on a fork, is there an architecture you've already thought out that I could build on top of?

**Comment by jhoffner** [comment]
Yeah the project supports different strategies, right now only two (solution and solution + test cases). A `project` strategy could be added to support this. Another idea is for a `json_api` strategy, where the code is expected to receive and return JSON.

**Comment by jhoffner** [comment]
To answer this question yes this is in the works. Support has already been added for certain languages (JS, Ruby, C#) and a separate UI (outside the scope of this repo) is in the works.
