### ISSUE TITLE
How can I fix reported bugs  from approved Kata?

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#143]
Approved katas are locked so.. how can I fix the bugs lets say in test cases?.
Can't either unpublish the kata edit and put it online again when fixed.

what's to be done here?

**Comment by jhoffner** [comment]
Issue moved to [Codewars/codewars.com #910](https://github.com/Codewars/codewars.com/issues/910) via [**ZenHub**](https://www.zenhub.com/)
