### ISSUE TITLE
Coffescript runner down?

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#145]
No syntax highlight ans when trying to run it shows that there aren't test cases.

![error cw](https://cloud.githubusercontent.com/assets/1063901/15367593/6c0bca4c-1cef-11e6-825f-76862c90b5b2.PNG)

**Comment by jhoffner** [comment]
I'm unable to reproduce. Is this still happening? Did it happen just once or does it happen 100% of the time?

**Comment by Dan-Nolan** [comment]
This happens for me too, 100% of the time

**Comment by javatlacati** [comment]
it happends on the [edit link](http://www.codewars.com/kumite/573c9682eaffa3003f0001d4/edit) the[ draft link](http://www.codewars.com/kumite/573c9682eaffa3003f0001d4?sel=573c9682eaffa3003f0001d4) shows syntax highlight but not results

**Comment by jhoffner** [comment]
OK, I've gotten some other reports to. It seems to be non-language specific, but specific to Kumite.

**Comment by javatlacati** [comment]
Editing an already approved kata works fine but fails if it's a draft.

**Comment by javatlacati** [comment]
perhaps it's an API error( 401 	Unauthorized – Your API key is wrong )

**Comment by jhoffner** [comment]
OK I was able to reproduce and have deployed a fix. Please verify.

**Comment by javatlacati** [comment]
Editing works now, but if you open a draft and click on show output nothing appears is it ok?
