### ISSUE TITLE
Elixir runner has troubles with fixture

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#146]
When trying to run with fixture It prints

> module TestSolution is not available

as you can see in this [Kumite](http://www.codewars.com/kumite/56bb7b7838dd34e7b200180c?sel=573d5143cab7edbd800000d0)

**Comment by kazk** [comment]
Closing this because the issue seems to be the misuse of "Preloaded" code or not declaring the `module`.

**Comment by javatlacati** [comment]
Yup that was fixed now it shows test results will be shown here 😢
