### ISSUE TITLE
VB.NET Support

### ISSUE THREAD

**Issue by Kavignon** [Codewars/codewars-runner-cli#155]
As I can, both C# and F# will be supported in the Codewars platform. Thing is, you would miss out on the vb programmers that would love the chance to practice there skills ! I have a strong confidence in my C# skills and there are portable to VB. Would be fun to see what are your reaction to bringing VB. That way, you would have a full .net suite support 
- C#
- F#
- VB

**Comment by Kavignon** [comment]
@jhoffner 
What are your thoughts on this?

**Comment by Kavignon** [comment]
Of course, I'd work on vb right after F#*

**Comment by jhoffner** [comment]
VB and F# would both be great. Hopefully the readme has enough to get you started, let me know if its missing any key information or if anything isnt clear. That way I can help you and make the readme more useful at the same time.

**Comment by bpoole5591** [comment]
Any updates on when VB may be added?

**Comment by kazk** [comment]
@bpoole5591 Not anytime soon. I'm not sure if there're many users wanting it.

To add support, we need at least the following information:

- Installation/Usage (Linux)
- Test Frameworks
  - How to output results in [Codewars format](https://github.com/Codewars/codewars-runner-cli/blob/master/documentation/output_format.md)

**Comment by richardpawson** [comment]
I teach Computer Science at (senior) high-school level.  Personally I teach C#, and encourage my pupils to practice their skills using Code Wars.  But I know of a lot of schools that teach the same syllabus using VB.NET (and which, despite being structurally homomorphic with C#, does have a couple of features that make it more attactive as a first programming language to learn).  Recently, I suggest to a group of other teachers that they should make more use of CodeWars and was _shocked_ to be told that it doesn't support VB.NET  -  I had never thought to check.  If the 'owners' of CodeWars are keen to see the usage in high schools expanded, they would do well to take heed of this.

**Comment by kazk** [comment]
It should be possible to add VB support by using .Net Core and NUnit. I'll try adding it on my free time, but I can't say when yet.

**Comment by kazk** [comment]
VB.NET (VB 15.5) will be added very soon. Some of Qualified's customer wants it. It uses NUnit for testing. It's already supported by the runner and I'll close this when it's deployed on Codewars.

**Comment by kazk** [comment]
Codewars now supports VB.NET. Have fun and please help with translating existing kata.
