### ISSUE TITLE
Typescript progress is not appearing

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#156]
Typescript progress is not appearing in the rank progress at the `View Profile` section.
![cw](https://cloud.githubusercontent.com/assets/1063901/15514873/dc42424e-21b0-11e6-8426-a0bc91adc043.PNG)

**Comment by jhoffner** [comment]
That's what you get for being a polyglot 😉. Yeah that section needs to be redesigned. Its expanding beyond the div. I have a fix ready to go out that will add scrollbars if the list gets too long.

**Comment by jhoffner** [comment]
BTW this is a CW issue, not a code runner one.

**Comment by javatlacati** [comment]
Sorry I tought it was because date not being saved instead of rendering issues.
