### ISSUE TITLE
BASIC Support

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#157]
Perhaps you can add some old fashion BASIC programming language support by adding some Java based interpreter like [JBasic](https://sourceforge.net/projects/jbasic/) trough java-runner.

**Comment by javatlacati** [comment]
Visual Basic is part now of the new opensource Microsoft's wave and [roslyn](https://github.com/dotnet/roslyn) can be used to compile it.

**Comment by kazk** [comment]
Closing as duplicate of #155 then.
