### ISSUE TITLE
Add Prolog Support

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#159]
Some good edimburg prolog will be nice!

What about some open-source SWI-Prolog?

**Comment by javatlacati** [comment]
Swi prolog has its own testing framework package known as **[plunit](http://www.swi-prolog.org/pldoc/doc_for?object=section(%27packages/plunit.html%27))**

**Comment by kazk** [comment]
Does it support custom output?

**Comment by javatlacati** [comment]
You mean like writing to the console?

**Comment by kazk** [comment]
No, we need test results in Codewars format:
```
<PASSED::>
<FAILED::>
<ERROR::>
<DESCRIBE::>
<IT::>
```

Some test frameworks provides a way to add custom reporter.

**Comment by javatlacati** [comment]
I think that you should write that format as output like in:

```
error:-write('<ERROR::>'),nl,fail.
passed:-write('<PASSED::>'),nl.
it(Itdescription):-write('<IT::>'),write(Itdescription),nl.
describe(Description):-write('<DESCRIBE::>'),write(Description),nl.
describe(Description,It):-write('<DESCRIBE::>'),it(It),write(Description),nl.

```

where `nl`, prints a new line, and write provides a string output to standard output.

**Comment by javatlacati** [comment]
Regarding that the test unit framework says

```
2.2 Writing the test body

The test-body is ordinary Prolog code. 
```

**Comment by kazk** [comment]
I think you're misunderstanding.
Is is possible for `plunit` to output `<FAILED::>` whenever the test fail?

**Comment by kazk** [comment]
So this example from the documentation
```prolog
test(add) :-
        A is 1 + 2,
        A =:= 3.
```
needs to output `<PASSED::>`.

**Comment by kazk** [comment]
Another options is to derive the Codewars output from its test results. For PowerShell, we generate Codewars format from NUnit XML report.

The last resort is to parse its output and try our best to generate compatible result. We currently do this for Rust.

**Comment by javatlacati** [comment]
rules are evaluated sequentially, so in

    error:-write('<ERROR::>'),nl,fail.

it will print

> <ERROR::>
> fail.


And your example translated will be:

```
error:-write('<ERROR::>'),nl,fail.
passed:-write('<PASSED::>'),nl.
test(add) :-
        A is 1 + 2,
        A =:= 3,
        passed .
test(add) :-
        A \= 3,
        error.
```

**Comment by kazk** [comment]
I tried your suggestion
```prolog
:- begin_tests(example).

error:-write('<ERROR::>'),nl,fail.
passed:-write('<PASSED::>'),nl.

test(add) :-
        A is 1 + 2,
        A =:= 3,
        passed .

test(add) :-
        A \= 3,
        error .

:- end_tests(example).
```

and got

```
Warning: /runner/output.pl:11:
	Singleton variables: [A]
% PL-Unit: example <PASSED::>
.
ERROR: /runner/output.pl:11:
	test add: failed

 done
% 1 test failed
% 1 tests passed
ERROR: -g run_tests: false
```

Everything except `<PASSED::>` is written to stderr so I can redirect them to `/dev/null` to get `<PASSED::>` only, but it doesn't work for failed tests. It also gets really repetitive having to write opposite rules for all the test cases.

**Comment by javatlacati** [comment]
I've asked in the [English StackOverflow](https://stackoverflow.com/questions/59557006/change-the-default-output-values-in-swi-prolog-true-and-false-for-predicate) and [Spanish StackOverflow](https://es.stackoverflow.com/questions/319299/cambiar-los-valores-por-defecto-swi-prolog-true-y-false-en-evaluaci%c3%b3n-de-pre) sites in order to integrate it with the default unit test framework. I'll update later.

**Comment by kazk** [comment]
How does the regular output of `plunit` look like? Maybe we can do post processing (like Rust, Coq, etc) instead of letting it output what we need.

**Comment by javatlacati** [comment]
Sucessfull:
```
?- run_tests.
% PL-Unit: my_add .. done
% All 2 tests passed
true.
```

Unsucessfull:

```
?- run_tests.
% PL-Unit: my_add 
ERROR: c:/users/ruslanlopez/documents/prolog/addition_ut.pl:22:
        test my_add: failed

. done
% 1 test failed
% 1 tests passed
false.
```

**Comment by javatlacati** [comment]
What people said in the StackOverflow was that I could try to run a query with something like

Successful

```
my_add(2,4,X),(is(X,6)->writeln('<PASSED::>');writeln('<ERROR::>')).
<PASSED::>
X = 6.
```

Unsuccessful

```
my_add(2,4,X),(is(X,6)->writeln('<PASSED::>');writeln('<ERROR::>')).
<ERROR::>
X = 8.
```

But my concern is that this could implicate not using the standard test framework

**Comment by kazk** [comment]
I'd like to avoid that if possible. I think we should look for another option if `plunit` cannot be used normally. It'll be just confusing for users who are familiar with `plunit` so there's no real benefit of using the exiting tool.

I was reading their docs and found the section for [`assertion`](https://www.swi-prolog.org/pldoc/man?section=testassertion) that might produce enough output for post-processing.

**Failing Example:**
```prolog
% test.pl
:- begin_tests(test).

test(a) :-
        A is 2^3,
        assertion(float(A)),
        assertion(A == 9).

:- end_tests(test).
```

```
% PL-Unit: test 
ERROR: /test.pl:17:
	test a: assertion failed
	Assertion: float(8)
ERROR: /test.pl:17:
	test a: assertion failed
	Assertion: 8==9
A done
% 2 assertions failed
% 1 test failed
% 0 tests passed
```

**Passing Example:**
```prolog
% test.pl
:- begin_tests(test).

test(a) :-
        A is 2^3,
        assertion(A == 8).

:- end_tests(test).
```
```
% PL-Unit: test . done
% test passed
% halt
```

**Running Tests:**
To run the tests, do:
```shell
# `-g true` to suppress welcome message.
swipl -g true -t 'run_tests.' -s test.pl
```
For tests in separate file, do:
```shell
# tests in example.plt
swipl -g true -t "load_test_files([]), run_tests." -s example.pl
```

**Comment by kazk** [comment]
I think I can do the following (assuming the failure messages are always well formatted):

1. Extract test names from the test file so we can report passed tests.
2. From the failure message, detect failed tests:
    - When assertions are used, the output will include the failure info based on them.
      Each assertion failures will be grouped by the test name. 
    - When just a goal is used, the output will be just "Test Failed".
3. Mark all tests not found in the failure message as passed.

---

**Files:**
```prolog
% solution.pl
add_3_and_double(X,Y) :- Y is (X+3)*3.
```
```prolog
% solution.plt
:- begin_tests(solution).
:- include(solution).

test(test_add_3_and_double_1) :-
        add_3_and_double(1, X),
        assertion(float(X)),
        assertion(X == 8).

test(test_add_3_and_double_2) :-
        add_3_and_double(2, X),
        X == 10.

test(test_add_3_and_double_3) :-
        add_3_and_double(-3, X),
        X == 0.

:- end_tests(solution).
```

**Run tests:**
```
swipl -g true -t 'load_test_files([]), run_tests.' -s solution.pl
```

**`plunit` output:**
```
% PL-Unit: solution 
ERROR: /solution.plt:5:
	test test_add_3_and_double_1: assertion failed
	Assertion: float(12)
ERROR: /solution.plt:5:
	test test_add_3_and_double_1: assertion failed
	Assertion: 12==8
A
ERROR: /solution.plt:10:
	test test_add_3_and_double_2: failed

. done
% 2 assertions failed
% 2 tests failed
% 1 tests passed
```
(don't know where "A. done" comes from and seems inconsistent)

**Post-processed:**
```
<IT::>test_add_3_and_double_1

<FAILED::>Assertion Failed: float(12)

<FAILED::>Assertion Failed: 12==8

<COMPLETEDIN::>

<IT::>test_add_3_and_double_2

<FAILED::>Test Failed

<COMPLETEDIN::>

<IT::>test_add_3_and_double_3

<PASSED::>Test Passed

<COMPLETEDIN::>
```

**Rendered:**
![image](https://user-images.githubusercontent.com/639336/71762444-220c1780-2e84-11ea-858d-b95c464cc127.png)


@javatlacati, @flip111, @razvan-flavius-panda, @Radivarig, @Kinrany

What do you think? Can any of you provide some example challenge for me to play with?

**Comment by Kinrany** [comment]
> (don't know where "A. done" comes from and seems inconsistent)

Could it be a concurrency issue, with multiple messages being printed at the same time?

> What do you think? Can any of you provide some example challenge for me to play with?

Would the recursive Euclid algorithm be a good enough example?

https://rosettacode.org/wiki/Greatest_common_divisor#Prolog

**Comment by kazk** [comment]
I think `A` is printed after the assertion failures when a test fails with `assertion`, otherwise a `.` is printed.

When I change the second test to use assertion, the output changes to:
```
% PL-Unit: solution 
ERROR: /solution.plt:5:
	test test_add_3_and_double_1: assertion failed
	Assertion: float(12)
ERROR: /solution.plt:5:
	test test_add_3_and_double_1: assertion failed
	Assertion: 12==8
A
ERROR: /solution.plt:10:
	test test_add_3_and_double_2: assertion failed
	Assertion: 15==10
A. done
% 3 assertions failed
% 2 tests failed
% 1 tests passed
```

When all 3 tests pass, the output is:

```
% PL-Unit: solution ... done
```

It looks weird, but it makes sense now.

---

> Would the recursive Euclid algorithm be a good enough example?

I'm looking for different ways to fail the test to observe the outputs and adjust the post processing as needed. So it'll be really helpful if you can come up with some tests and different examples of failures for them.

**Comment by Kinrany** [comment]
> It looks weird, but it makes sense now.

It looks like it's printing both "A" and the error message in parallel, and "done" is just the end of enumeration. Maybe the error messages can be suppressed or redirected, so you can get an easy to parse "solution AA. done"?

> I'm looking for different ways to fail the test to observe the outputs and adjust the post processing as needed. So it'll be really helpful if you can come up with some tests and different examples of failures for them.

Like this?

```prolog
test(test_gcd_1) :-
    gcd(2, 3, 1).

test(test_gcd_2) :- 
    gcd(4, 6, 2).

test(test_gcd_3) :- 
    forall(gcd(4, 6, X), X is 2).
```

**Comment by kazk** [comment]
Got it working. `plunit` can be used normally and results will be shown like other languages we support. When `assertion` is used, its failure message is shown. Otherwise, the failure message is just "Test Failed".
It'll look something like this:
![image](https://user-images.githubusercontent.com/639336/71774271-d22f5e00-2f20-11ea-8292-ff50f1dddcb1.png)

The name of the solution module will be inferred from the test file (`:- begin_tests(example).`). Preloaded code is a separate module (`preloaded.pl`) that can be optionally included.

There might be some cases that breaks the post processing, but I'll let you guys play with it once it's on Codewars and fix them as it gets reported.

I'll close this issue when it's deployed on Codewars.

**Comment by kazk** [comment]
Deployed Prolog support.
Please let me know if you find any outputs that looks weird by opening new issues.

**Comment by javatlacati** [comment]
Hope this could help for the error messages:

## addition.pl
```
my_add(A,B,Result):-
    number(A),
    number(B),
    is(Result,+(A,B+2)).
```

## addition_ut.pl
```
:-['C:/Users/RuslanLopez/Documents/Prolog/adittion.pl']. %load file

:- begin_tests(my_add). %unit test block start
:- include(adittion). %load rules form file


% Codewars output format
error:-nl,write('<ERROR::>'),nl.
passed:-nl,write('<PASSED::>'),nl.
failed(Error):-nl,write('<FAILED::>'),write(Error) ,error.

unpacking2(Lists,L1,I):-
   findall(I,member([I],Lists),L1).


codewars_test(Rule, Parameters,Result, Condition, Message):-
        Parameters=[],
        call(Rule, Result), %evaluate predicate
        assertion(Condition) % Assertion
       ,(
            call(Condition) % test condition
           ->
              passed %sucess case
            ;
              failed(Message) %failed case

       )
      .

codewars_test(Rule, Parameters,Result, Condition, Message):-
        Parameters=[H],
        call(Rule, H, Result), %evaluate predicate
        assertion(Condition) % Assertion
       ,(
            call(Condition) % test condition
           ->
              passed %sucess case
            ;
              failed(Message) %failed case

       )
      .


codewars_test(Rule, Parameters,Result, Condition, Message):-
        Parameters=[H|T],
        T=[],
        call(Rule, H, Result), %evaluate predicate
        assertion(Condition) % Assertion
       ,(
            call(Condition) % test condition
           ->
              passed %sucess case
            ;
              failed(Message) %failed case

       )
      .


codewars_test(Rule, Parameters,Result, Condition, Message):-
        Parameters=[H|T],
        T=[S|_],
        call(Rule,H,S, Result), %evaluate predicate
        assertion(Condition) % Assertion
       ,(
            call(Condition) % test condition
           ->
              passed %sucess case
            ;
              failed(Message) %failed case

       )
      .


%unwraps up to 3 parameters
codewars_test(Rule, Parameters,Result, Condition, Message):-
        Parameters=[H|T],
        T=[S|W],
        W=[X,_],
        call(Rule,H,S,X, Result), %evaluate predicate
        assertion(Condition) % Assertion
       ,(
            call(Condition) % test condition
           ->
              passed %sucess case
            ;
              failed(Message) %failed case

       )
      .


test(my_add):- call(codewars_test(my_add, [1,2],Result, Result is 3,'1+2 should be 3')).
test(my_add):- call(codewars_test(my_add, [1,2],Result, Result \= 5,'1+2 should not be 5')).

:- end_tests(my_add).%unit test block end
```

# Interactive run

    ?- run_tests.

>     % PL-Unit: my_add 
>     ERROR: c:/users/ruslanlopez/documents/prolog/addition_ut.pl:94:
>             test my_add: assertion failed
>             Assertion: 5 is 3
> 
>     <FAILED::>1+2 should be 3
>     <ERROR::>
>     A
>     ERROR: c:/users/ruslanlopez/documents/prolog/addition_ut.pl:95:
>             test my_add: assertion failed
>             Assertion: 5\=5
> 
>     <FAILED::>1+2 should not be 5
>     <ERROR::>
>     A done
>     % 2 assertions failed
>     % 2 tests failed
>     % 0 tests passed
>     false.
