### ISSUE TITLE
Typescript enhace nodejs integration

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#160]
When you reference to process variable you get 

>error TS2304: Cannot find name 'process'

To solvent you can [install typings for node](http://stackoverflow.com/questions/35551185/typescript-read-arguments-from-command-line-error-ts2304-cannot-find-name-p)

**Comment by jhoffner** [comment]
They are installed, but you need to reference them at the top of the file.

**Comment by javatlacati** [comment]
how can I do that? :grinning:

**Comment by jhoffner** [comment]
The `examples/typescript.yml` file shows you how. You can simply just add `/// <reference path="/runner/typings/node/index.d.ts" />` to the top of your solution if you need it in there (the example only use it within the fixture)

**Comment by javatlacati** [comment]
TY lookign in https://github.com/Codewars/codewars-runner-cli/blob/master/examples/typescript.yml
