### ISSUE TITLE
Typescript chai needs more time

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#161]
When you call chai's `assert.notEqual` or `assert.isFalse` you get the message:

>Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

This only happends when test should pass on non passing tests you get the validation properly so I assume it needs more time to run. (Sorry for my bad english)

**Comment by javatlacati** [comment]
TY to bypass that I had to declare the fixture with arrow functions will try it later :)

**Comment by jhoffner** [comment]
FYI: I still havent deployed yet. Ran into a few snags thats holding me up. Should hopefully be up by tonight.
