### ISSUE TITLE
Adding support for Luna

### ISSUE THREAD

**Issue by Kavignon** [codewars/codewars-runner-cli#164]
So yeah,  this is going to get big soon.  Luna is a new alpha programming language. In short, Luna is a general purpose, purely functional programming language incorporating many recent innovation such as high order function. It interops with haskell,  python,  Javascript and C++.

**Comment by Kavignon** [comment]
Right now, it's in alpha testing, but it would be good to support them now in my mind. What are your thoughts on this @jhoffner

**Comment by jhoffner** [comment]
Looks pretty interesting. The more I look into it, the more languages I see popping up every week. Who knows which one will take off or not. There seems to be a lot interest for adding boutique languages on the site which is cool. I don't have any problems with it, at this point, having a bunch of them on the site. My only concern is how much support/maintenance they will need once they are added.

**Comment by Kavignon** [comment]
With what I've already given my self,  I got plenty now on my plate haha.
I thought Luna would be a good assement for people using Haskell
Javascript, etc. Of course,  you're right,  it's hard to know how much
maintenance will be required.
When adding a language to the cli runner, is the language directly
accessible on the Web site? Meaning that,  when adding Luna,  I'll be able
to solve any kata in Luna or someone has to implement it by himself?

**Comment by jhoffner** [comment]
No, there are still some integration points I need to add to the site. Mostly just a few config settings. We are running out of space to show all of the languages so I need to switch the kata trainer over to using a dropdown soon - so little things like that may come up. Also I need to usually write documentation, which now that I think about it is also something that could added as a requirement within this project before a language gets pushed out.

**Comment by Kavignon** [comment]
I think that would be a requirement too. We can't just say well works fine
on the image. Moving on to the next thing bye.

**Comment by Kavignon** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Kevin

Confirm that you know Kevin: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Cghkhc49&invitationId=6208290946375827456&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivzc5eaf%7Ece








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivzc5eaf-ce&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFJpXPhhgMfSwAAAVihH0TdGwJtMK-9ItymKRh4746AWeEgMkfCIfXHmGPSAKZY83Thh1SD0an_nmi9T13rz9FMbxeyAwoQgzGSM2aIrz1hRSQfVkoyslqfwzECbId03NpPlrn34oPemf5LIIZNlsmcdl3xurFbQ8lBMnZ7zXP1UO0-2lMToMPhfv6Y2lSwG7CcDJPL1nMzVYCvpFNjVVaQHg&eid=0-ivzc5eaf-ce


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivzc5eaf-ce&a=customerServiceUrl&ek=invite_guest

© 2016 LinkedIn Corporation, 1000 West Maude Avenue, Sunnyvale, CA 94085. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Kevin

Confirm that you know Kevin: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=K3T54Hvj&invitationId=6208290946065457152&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivzc72ka%7E0








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivzc72ka-0&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEPV7Y5IklE_gAAAVihIHuSQjIdKgUe2KNggtwp6h9S5ViLpcenVdwx1YHdmy0Xaebc_hrDdlPeZ4aGLTN3XRtQDnwwTru39UNW_fAzAuZ5UE8OxsOvtqgMGHplDi55lT5xSsImfKluot_cXnoPVLEgtb3Yv3ZwuBnkehgOU7C51bSB38TEDG8daigGDemultLAg2MixY25TjyBNvxLRRf6xg&eid=0-ivzc72ka-0


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivzc72ka-0&a=customerServiceUrl&ek=invite_guest

© 2016 LinkedIn Corporation, 1000 West Maude Avenue, Sunnyvale, CA 94085. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Kevin Avignon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=K3T54Hvj&invitationId=6208290946065457152&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7Eem9fj9%7Eiw6mslee%7Eqb

View Kevin Avignon&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=K3T54Hvj&invitationId=6208290946065457152&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7Eem9fj9%7Eiw6mslee%7Eqb





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-em9fj9-iw6mslee-qb&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-em9fj9-iw6mslee-qb&loid=AQGqgwoZVEVenwAAAVi8PHCc-_KdKHan4yao1HVD-lq7ho1a4D03dP2rb4iRHbzw1Fc5BW4aA_b4SHmQVQe7jLwm1YwxC2a9cb0ap4eDEb8VTFO7Z_v2wGEvM-Gkgs1gcIs9Rggcj8BVLv-zUE4j0jpH9cg08M5uo-YGrlWH7prIYV0QGglNdd5q1ceU5G9ruz7lzofpvaTXfkj82muYwZAp_CK84g

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-em9fj9-iw6mslee-qb&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Kevin Avignon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Cghkhc49&invitationId=6208290946375827456&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-o9nhqn%7Eiw6msfjg%7Ee0

View Kevin Avignon&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Cghkhc49&invitationId=6208290946375827456&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-o9nhqn%7Eiw6msfjg%7Ee0





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=o9nhqn-iw6msfjg-e0&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=o9nhqn-iw6msfjg-e0&loid=AQFtDa-G--B8JgAAAVi8PVSOGNVknDvM2PGUcYqrlTFRXLRB94ep5D7qfcYN5EWj_v_jK62m1SmyEqvfs8Y3etnzBdmQfWkeekLEY4W6YlCQEaLGt95KjPscw3hcztfwEfMOQepT4pFU63uIj1zNzQOfVD-SZEnkT5kC9z18Bw5mWPJCzsdybhHQc0U17hS0pNobeNpG6lVe1nduEwiigkzJfn4l7A

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=o9nhqn-iw6msfjg-e0&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
LinkedIn
------------

You've joined the world's largest professional network. Here's how to get started.

Codewars/codewars-ru,
Welcome to the world's largest professional network.

Get started: www.linkedin.com/start/welcome

---

Stay connected
See which of the 400+ million LinkedIn professionals you already know: www.linkedin.com/fetch/importAndInviteEntry

Be discovered
Tell your professional story and be found for career opportunities: https://www.linkedin.com/profile/edit

Get inspired
Follow LinkedIn Influencers to get unique insights from industry leaders: www.linkedin.com/today/influencers

Thanks for joining!
The LinkedIn Team



© 2017 LinkedIn Ireland Unlimited Company. LinkedIn, the LinkedIn logo, and InMail are registered trademarks of LinkedIn Corporation in the United States and/or other countries. All rights reserved.

This is an occasional email to help you get the most out of LinkedIn. Unsubscribe here: https://www.linkedin.com/e/v2?e=9nqrlj-j2vnpe7r-gh&a=nsettings-loid-email-unsubscribe-router&midToken=AQE6p04GF2BEhA&ek=welcome_day_0&loid=AQFWvYpAFFVpCAAAAVwgFlsouDzCI-rGGNVOV1bJ7uN2BUfRIVGIw-KhvvPIU_7cB3n1QZ8ZephIg1qtinSGe_8UEpn5wLNgeme0dolTFFJQ28lanobEZh53BHXN1oTtfvSFdDyhpk_thSlqAcKZnupXE6mOIULkTEZOfik7tE92CIdlw1lkPBLf9roB57wdFoiErLYJ-7r8PtremL2YdQDn&eid=9nqrlj-j2vnpe7r-gh



This email was intended for Codewars/codewars-ru Daniel Chukucha (--). 
Learn why we included this: https://www.linkedin.com/e/v2?e=9nqrlj-j2vnpe7r-gh&lipi=urn%3Ali%3Apage%3Aemail_welcome_day_0%3BiVVLRJh5QN2ooimp4s832Q%3D%3D&a=customerServiceUrl&midToken=AQE6p04GF2BEhA&ek=welcome_day_0&articleId=4788

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=9nqrlj-j2vnpe7r-gh&lipi=urn%3Ali%3Apage%3Aemail_welcome_day_0%3BiVVLRJh5QN2ooimp4s832Q%3D%3D&a=customerServiceUrl&midToken=AQE6p04GF2BEhA&ek=welcome_day_0

LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company.
Registered in Ireland as a private unlimited company, Company Number 477441
Registered Office: Wilton Plaza, Wilton Place, Dublin 2, Ireland

**Comment by Kavignon** [comment]
Charles Chiteure has accepted your invitation. Let's start a conversation.

Charles Chiteure
Finance Analyst
Afghanistan
View profile: https://www.linkedin.com/comm/in/charles-chiteure-08332536?midToken=AQE6p04GF2BEhA&trk=eml-email_accept_invite_single_01-hero-2-prof%7Ecta&trkEmail=eml-email_accept_invite_single_01-hero-2-prof%7Ecta-null-9nqrlj%7Ej2vot0fw%7E5f-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3Bfq3OP1FZTzqRUWagPr0EXg%3D%3D
Message: https://www.linkedin.com/comm/messaging/compose/?connId=126208035&midToken=AQE6p04GF2BEhA&trk=eml-email_accept_invite_single_01-hero-1-msg%7Ecta&trkEmail=eml-email_accept_invite_single_01-hero-1-msg%7Ecta-null-9nqrlj%7Ej2vot0fw%7E5f-null-neptune%2Fmessaging%2Ecompose&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3Bfq3OP1FZTzqRUWagPr0EXg%3D%3D


-----------------------------------
People you may know
-----------------------------------

Samuel F Poirier
Co-Founder at Retinad
View profile: https://www.linkedin.com/comm/in/samuelpoirier?midToken=AQE6p04GF2BEhA&trk=eml-email_accept_invite_single_01-accepted_invite-22-prof%7Ecta%7Etext&trkEmail=eml-email_accept_invite_single_01-accepted_invite-22-prof%7Ecta%7Etext-null-9nqrlj%7Ej2vot0fw%7E5f-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3Bfq3OP1FZTzqRUWagPr0EXg%3D%3D&authToken=5K20&authType=name
Connect: https://www.linkedin.com/comm/mynetwork/send-invite/samuelpoirier/?midToken=AQE6p04GF2BEhA&trk=eml-email_accept_invite_single_01-pymk-25-connect%7Ecta%7Etext&trkEmail=eml-email_accept_invite_single_01-pymk-25-connect%7Ecta%7Etext-null-9nqrlj%7Ej2vot0fw%7E5f-null-neptune%2Fmynetwork%2Einvite%7Esend&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3Bfq3OP1FZTzqRUWagPr0EXg%3D%3D&_sig=2QlUK6u1c5fTM1


Yan Leng Vuong
Software Engineering Student
View profile: https://www.linkedin.com/comm/in/yan-leng-vuong-44046831?midToken=AQE6p04GF2BEhA&trk=eml-email_accept_invite_single_01-accepted_invite-23-prof%7Ecta%7Etext&trkEmail=eml-email_accept_invite_single_01-accepted_invite-23-prof%7Ecta%7Etext-null-9nqrlj%7Ej2vot0fw%7E5f-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3Bfq3OP1FZTzqRUWagPr0EXg%3D%3D&authToken=FRyu&authType=name
Connect: https://www.linkedin.com/comm/mynetwork/send-invite/yan-leng-vuong-44046831/?midToken=AQE6p04GF2BEhA&trk=eml-email_accept_invite_single_01-pymk-26-connect%7Ecta%7Etext&trkEmail=eml-email_accept_invite_single_01-pymk-26-connect%7Ecta%7Etext-null-9nqrlj%7Ej2vot0fw%7E5f-null-neptune%2Fmynetwork%2Einvite%7Esend&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3Bfq3OP1FZTzqRUWagPr0EXg%3D%3D&_sig=2dK4c7JcI5fTM1


Yanis Ikene
Technology Associate at Morgan Stanley
View profile: https://www.linkedin.com/comm/in/yanisikene?midToken=AQE6p04GF2BEhA&trk=eml-email_accept_invite_single_01-accepted_invite-24-prof%7Ecta%7Etext&trkEmail=eml-email_accept_invite_single_01-accepted_invite-24-prof%7Ecta%7Etext-null-9nqrlj%7Ej2vot0fw%7E5f-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3Bfq3OP1FZTzqRUWagPr0EXg%3D%3D&authToken=onl5&authType=name
Connect: https://www.linkedin.com/comm/mynetwork/send-invite/yanisikene/?midToken=AQE6p04GF2BEhA&trk=eml-email_accept_invite_single_01-pymk-27-connect%7Ecta%7Etext&trkEmail=eml-email_accept_invite_single_01-pymk-27-connect%7Ecta%7Etext-null-9nqrlj%7Ej2vot0fw%7E5f-null-neptune%2Fmynetwork%2Einvite%7Esend&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3Bfq3OP1FZTzqRUWagPr0EXg%3D%3D&_sig=1Aj2zyWxY5fTM1


See more: https://www.linkedin.com/comm/mynetwork/add-connections/?midToken=AQE6p04GF2BEhA&trk=eml-email_accept_invite_single_01-accepted_invite-6-text_see%7Emore%7Ecta&trkEmail=eml-email_accept_invite_single_01-accepted_invite-6-text_see%7Emore%7Ecta-null-9nqrlj%7Ej2vot0fw%7E5f-null-neptune%2Fmynetwork%2Eadd%7Econnections&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3Bfq3OP1FZTzqRUWagPr0EXg%3D%3D

.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=9nqrlj-j2vot0fw-5f&a=nsettings-loid-email-unsubscribe-router&midToken=AQE6p04GF2BEhA&ek=email_accept_invite_single_01&li=33&m=unsub&ts=unsub&loid=AQELeOOZYPvE1QAAAVwgMo-53NCaIh6uUPx5ltiyZVQojOkVH0DIcSetvGm1bnxHAMPj8n48plAk10zWcu2Y5D4J1m_ZXL1r-8sfW8-7C_sJWJjfgu2Y11wdX2X8jrwzctKlXE5LZq6OkBADHGRVSfbOp5E9ssD45V8m5cZiEi_DCuasHamnjPLRiT3Wnd-7bxC0K2rEur2wuijV4XdU25kNvBpfJA&eid=9nqrlj-j2vot0fw-5f

Help: https://www.linkedin.com/e/v2?e=9nqrlj-j2vot0fw-5f&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3Bfq3OP1FZTzqRUWagPr0EXg%3D%3D&a=customerServiceUrl&midToken=AQE6p04GF2BEhA&ek=email_accept_invite_single_01&li=32&m=footer&ts=help&articleId=67


You are receiving Accepted Invitation emails.

This email was intended for Codewars/codewars-ru Daniel Chukucha (Student at university or Nations university).
Learn why we included this: https://www.linkedin.com/e/v2?e=9nqrlj-j2vot0fw-5f&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3Bfq3OP1FZTzqRUWagPr0EXg%3D%3D&a=customerServiceUrl&midToken=AQE6p04GF2BEhA&ek=email_accept_invite_single_01&articleId=4788

© 2017 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Nadia Boodram has accepted your invitation. Let's start a conversation.

Nadia Boodram
Senior Recruitment Consultant at Inteqna
Toronto, Canada Area
View profile: https://www.linkedin.com/comm/in/nadia-boodram-1026b12a?midToken=AQE6p04GF2BEhA&trk=eml-email_accept_invite_single_01-hero-2-prof%7Ecta&trkEmail=eml-email_accept_invite_single_01-hero-2-prof%7Ecta-null-9nqrlj%7Ej2vuuopq%7Eqt-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3BeXXXb2gmTAa3%2Bp4Fb%2BMWbw%3D%3D
Message: https://www.linkedin.com/comm/messaging/compose/?connId=103246418&midToken=AQE6p04GF2BEhA&trk=eml-email_accept_invite_single_01-hero-1-msg%7Ecta&trkEmail=eml-email_accept_invite_single_01-hero-1-msg%7Ecta-null-9nqrlj%7Ej2vuuopq%7Eqt-null-neptune%2Fmessaging%2Ecompose&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3BeXXXb2gmTAa3%2Bp4Fb%2BMWbw%3D%3D


-----------------------------------
People you may know
-----------------------------------

Samuel F Poirier
Co-Founder at Retinad
View profile: https://www.linkedin.com/comm/in/samuelpoirier?midToken=AQE6p04GF2BEhA&trk=eml-email_accept_invite_single_01-accepted_invite-22-prof%7Ecta%7Etext&trkEmail=eml-email_accept_invite_single_01-accepted_invite-22-prof%7Ecta%7Etext-null-9nqrlj%7Ej2vuuopq%7Eqt-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3BeXXXb2gmTAa3%2Bp4Fb%2BMWbw%3D%3D&authToken=5K20&authType=name
Connect: https://www.linkedin.com/comm/mynetwork/send-invite/samuelpoirier/?midToken=AQE6p04GF2BEhA&trk=eml-email_accept_invite_single_01-pymk-25-connect%7Ecta%7Etext&trkEmail=eml-email_accept_invite_single_01-pymk-25-connect%7Ecta%7Etext-null-9nqrlj%7Ej2vuuopq%7Eqt-null-neptune%2Fmynetwork%2Einvite%7Esend&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3BeXXXb2gmTAa3%2Bp4Fb%2BMWbw%3D%3D&_sig=12IclYYiuKfTM1


Yan Leng Vuong
Software Engineering Student
View profile: https://www.linkedin.com/comm/in/yan-leng-vuong-44046831?midToken=AQE6p04GF2BEhA&trk=eml-email_accept_invite_single_01-accepted_invite-23-prof%7Ecta%7Etext&trkEmail=eml-email_accept_invite_single_01-accepted_invite-23-prof%7Ecta%7Etext-null-9nqrlj%7Ej2vuuopq%7Eqt-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3BeXXXb2gmTAa3%2Bp4Fb%2BMWbw%3D%3D&authToken=FRyu&authType=name
Connect: https://www.linkedin.com/comm/mynetwork/send-invite/yan-leng-vuong-44046831/?midToken=AQE6p04GF2BEhA&trk=eml-email_accept_invite_single_01-pymk-26-connect%7Ecta%7Etext&trkEmail=eml-email_accept_invite_single_01-pymk-26-connect%7Ecta%7Etext-null-9nqrlj%7Ej2vuuopq%7Eqt-null-neptune%2Fmynetwork%2Einvite%7Esend&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3BeXXXb2gmTAa3%2Bp4Fb%2BMWbw%3D%3D&_sig=0xeKl9dCKKfTM1


Yanis Ikene
Technology Associate at Morgan Stanley
View profile: https://www.linkedin.com/comm/in/yanisikene?midToken=AQE6p04GF2BEhA&trk=eml-email_accept_invite_single_01-accepted_invite-24-prof%7Ecta%7Etext&trkEmail=eml-email_accept_invite_single_01-accepted_invite-24-prof%7Ecta%7Etext-null-9nqrlj%7Ej2vuuopq%7Eqt-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3BeXXXb2gmTAa3%2Bp4Fb%2BMWbw%3D%3D&authToken=onl5&authType=name
Connect: https://www.linkedin.com/comm/mynetwork/send-invite/yanisikene/?midToken=AQE6p04GF2BEhA&trk=eml-email_accept_invite_single_01-pymk-27-connect%7Ecta%7Etext&trkEmail=eml-email_accept_invite_single_01-pymk-27-connect%7Ecta%7Etext-null-9nqrlj%7Ej2vuuopq%7Eqt-null-neptune%2Fmynetwork%2Einvite%7Esend&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3BeXXXb2gmTAa3%2Bp4Fb%2BMWbw%3D%3D&_sig=1RqhJjfTGKfTM1


See more: https://www.linkedin.com/comm/mynetwork/add-connections/?midToken=AQE6p04GF2BEhA&trk=eml-email_accept_invite_single_01-accepted_invite-6-text_see%7Emore%7Ecta&trkEmail=eml-email_accept_invite_single_01-accepted_invite-6-text_see%7Emore%7Ecta-null-9nqrlj%7Ej2vuuopq%7Eqt-null-neptune%2Fmynetwork%2Eadd%7Econnections&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3BeXXXb2gmTAa3%2Bp4Fb%2BMWbw%3D%3D

.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=9nqrlj-j2vuuopq-qt&a=nsettings-loid-email-unsubscribe-router&midToken=AQE6p04GF2BEhA&ek=email_accept_invite_single_01&li=33&m=unsub&ts=unsub&loid=AQGKQcQAAehxfwAAAVwgzXeUjaEr9LGBNrWpucmfv8n9_NFs3J3gE7NUBOpFEBJE2Rgk7Da_Cyy5GGnmKtON58-AZI1IhUyRz8baDxXfO4I4nhgWHNtoOnWEEBOZt1G2r1Alkx7tbCHktwjRJxWD9nGSekeJP8M_w9rsF91Nw1vPzAMETuJbOPdfUrFQU_Bk08lgGGzT1h3bXoEwSmMp1ZYk2-fdQA&eid=9nqrlj-j2vuuopq-qt

Help: https://www.linkedin.com/e/v2?e=9nqrlj-j2vuuopq-qt&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3BeXXXb2gmTAa3%2Bp4Fb%2BMWbw%3D%3D&a=customerServiceUrl&midToken=AQE6p04GF2BEhA&ek=email_accept_invite_single_01&li=32&m=footer&ts=help&articleId=67


You are receiving Accepted Invitation emails.

This email was intended for Codewars/codewars-ru Daniel Chukucha (Student at university or Nations university).
Learn why we included this: https://www.linkedin.com/e/v2?e=9nqrlj-j2vuuopq-qt&lipi=urn%3Ali%3Apage%3Aemail_email_accept_invite_single_01%3BeXXXb2gmTAa3%2Bp4Fb%2BMWbw%3D%3D&a=customerServiceUrl&midToken=AQE6p04GF2BEhA&ek=email_accept_invite_single_01&articleId=4788

© 2017 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by OverZealous** [comment]
@Kavignon You've got something forwarding messages, sort of spamming GitHub.

**Comment by jhoffner** [comment]
@Kavignon I had to block you unfortunately because you continue to spam our comments with some sort of linkedin forwarding.

**Comment by kazk** [comment]
See https://github.com/codewars/runner/issues/34
