### ISSUE TITLE
Support for Lua

### ISSUE THREAD

**Issue by Kavignon** [Codewars/codewars-runner-cli#166]
Being one of the top voted languages for Codewars, I think it makes sense to take some time and integrate Lua inside Codewars. I'll let it be for the time being in order to finish first what I'd love to integrate (F#, VB,Kotlin & Go). If by the time no one pick this baby up, I will assign it to myself and work on it :+1:

**Comment by VStankoV** [comment]
come on guys! I am waiting about three months for Lua, horry up ))))

**Comment by jhoffner** [comment]
@VStankoV the great thing about this being open source is that the power is completely in your hands to add it if you want it badly enough 😄
