### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#167]
When you create some sort of infinite cycle error msg should be more friendly

> <--- Last few GCs --->
> 
> 1109 ms: Mark-sweep 641.2 (1890.8) -> 386.2 (1635.8) MB, 62.6 / 0 ms [allocation failure] [GC in old space requested].
> 1162 ms: Mark-sweep 386.2 (2209.6) -> 385.9 (2209.6) MB, 52.5 / 0 ms [allocation failure] [GC in old space requested].
> 1216 ms: Mark-sweep 385.9 (2783.3) -> 385.9 (2783.3) MB, 53.1 / 0 ms [last resort gc].
> 1268 ms: Mark-sweep 385.9 (2783.3) -> 385.9 (2783.3) MB, 51.9 / 0 ms [last resort gc].
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 0x3679005c9fa9
> 2: countBy [[eval]:~6] [pc=0xf3f46966ac5](this=0x3679005e7901 ,x=1,n=5)
> 3: /\* anonymous _/ [[eval]:16] [pc=0xf3f46965d60](this=0x3679005e7901)
> 4: /_ anonymous */ [[eval]:18] [pc=0xf3f46965fc3](this=0x3679005e7901)
> 5: handleError [/runner/frameworks/javascript/cw-2.js:251] [pc=0xf3f469658aa] (this=0x1229f38041d9
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by kazk** [comment]
I don't know what you mean by "infinite cycle", but are you suggesting `node-runner` to *know* what's wrong with the user's code?

```javascript
// array becomes too large
const a = [];
for (let i = 0; i < 1000000000; ++i) a.push(i); 
```

```javascript
// loop never terminates
const a = [];
for (let i = 0; i < 10; --i) a.push(i); 
```

I don't know any tools supporting this.

Isn't `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory` informative enough?
