### ISSUE TITLE
CSS support

### ISSUE THREAD

**Issue by javatlacati** [codewars/codewars-runner-cli#172]
I've seen that in the kumite section there's the type css but you can't create other than drafts. Perhaps you could add some css support by leaving alone the css string and passing it to the javascript runner, please look at this [Kumite](http://www.codewars.com/kumite/570fe09cb29c7012110015eb?sel=570fe09cb29c7012110015eb)

**Comment by kazk** [comment]
Closing this one since #836 contains more useful information.
