### ISSUE TITLE
Add support for Nim

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#177]
Could you guys add the Nim programming language as a future Language implementation? http://nim-lang.org

**Comment by hcorion** [comment]
I would love for this to happen!
For reference, here are some prebuilt docker images for nim: 
https://github.com/yglukhov/nim-docker
and this one is based on a release version (vs latest devel like the previous one):
https://hub.docker.com/r/coopernurse/docker-nim/~/dockerfile/
