### ISSUE TITLE
access the solutions source code that is being tested from Ruby fixture? 

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#183]
Is it possible to access the solutions source code that is being tested?
The usecase here would be to disallow the use of certain language keywords that cannot be overridden and cannot easily be tested for during runtime. E.g. "Don't use the 'if' keyword in this kata"

**Comment by jhoffner** [comment]
Yes, though it still needs to be documented. `/home/codewarrior/solution.txt` can be read in if need be

**Comment by javatlacati** [comment]
can you please tag it as question so people can find it more easily? :smile:
