### ISSUE TITLE
Translation into C++ #377

### ISSUE THREAD

**Issue by g964** [Codewars/codewars-runner-cli#186]
I'm trying to translate a kata into C++ but I got lots of "Nope", "Try again" or
```
clang++-3.6 -stdlib=libc++ -std=c++1y -isystem /runner/frameworks/cpp error: expected ';' after struct
}
 ^
 ;
1 error generated.
0 Passed
0 Failed
0 Errors
```
I think there might be a problem of the "runner" because I have all the necessary ';' and no struct in my code.

**Comment by Dan-Nolan** [comment]
This seems to happen when you don't add a semi-colon after the `Describe` block because the Igloo framework turns that macro into a struct. Let me know if that resolves it for you

That's a pretty terrible error and I'll see what I can do to fix it 😄

**Comment by g964** [comment]
The error was not that terrible:-) You were right: adding a semi-colon fixed the thing, thanks!
