### ISSUE TITLE
Dart - Syntax highlighting not correct [Kumite Testing]

### ISSUE THREAD

**Issue by lteacher** [Codewars/codewars-runner-cli#188]
@jhoffner I noticed that the syntax doesn't look nice in the various code view sections. Couldn't figure out what it is set to now, assuming its js or something like that, [but there is one for dart](http://codemirror.net/mode/dart/index.html):

Specifically I saw this on the example at the above link:
```javascript
  CodeMirror.defineMIME("application/dart", {
    name: "clike",
    ... other stuff
```

**Comment by lteacher** [comment]
Maybe this should be on the other issue list for the site? Either way any updates here?

**Comment by jhoffner** [comment]
We are stuck on an older version of CodeMirror but hopefully the Dart stuff will translate over. Yes this would be better on the site issues list since its UI related.

**Comment by lteacher** [comment]
Moved to Codewars site since its UI relateed as above.
