### ISSUE TITLE
Dart - Errors not output in some cases [Kumite Testing]

### ISSUE THREAD

**Issue by lteacher** [Codewars/codewars-runner-cli#189]
There are some cases where the errors are not output and instead it just outputs 'undefined', such as this example which is actually missing an entire bracket from the constructor:
![image](https://cloud.githubusercontent.com/assets/6103860/15995109/9181cbaa-3158-11e6-9d39-1d70e3ee419e.png)

Other cases like missing semi-colons do work however depending on where they occur, there is probably an issue where the error is taken from the test output.

**Comment by lteacher** [comment]
It turns out that sometimes it can be considered a warning, I suppose since its just a linter anyways
```sh
Failed to load "/tmp/dart/116513-827-9q26w.dart":
Unable to spawn isolate: 'file:///tmp/dart/116513-827-9q26w.dart': warning: line 11 pos 19: unbalanced '(' opens here
            Person(this.firstName,this.lastName
                  ^
line 12 pos 11: unbalanced '}'
```

Of course the text is chopped up to format into the `<ERROR::>` section since obviously `Unable to spawn isolate: "ugly/filename"` is not desirable, however, [its looking for `'error: '`](https://github.com/Codewars/codewars-runner-cli/blob/master/lib/runners/dart.js#L121)

**Comment by lteacher** [comment]
Actually this issue still occurs probably because the Dart image in production has not been updated per #190 though of course I can only assume.

@jhoffner Any updates on this? the PR was merged a while ago and I made comments on that but still hoping to see those fixes live...

**Comment by jhoffner** [comment]
Yeah I actually meant to push this out today, but got held up with some other deployments and changes. If I don't get it live tonight I will tomorrow. The PHP stuff needs to go out to so I just wanted to get some basic manual testing done.

**Comment by lteacher** [comment]
Ok great! Thanks for the update on this.
