### ISSUE TITLE
PowerShell Support

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#192]
Would be a fantastic addition to the supported languages.

**Comment by Kavignon** [comment]
This would be an awesome addition for. NET :D

**Comment by jhoffner** [comment]
Sorry to say but this is likely never going to happen. We don't run Windows machines nor can we simulate them.

**Comment by javatlacati** [comment]
Not even trough wine?

**Comment by jhoffner** [comment]
Re-opening since apparently Google is telling me there is some sort of linux support for PowerShell. Not sure how well it works or how to install it or anything, but someone in the community is certainly welcome to giving it a shot and submitting a PR.

**Comment by Kavignon** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Kevin

Confirm that you know Kevin: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=ACfTFxzN&invitationId=6208290946057064448&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivzc6nby%7Em2








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivzc6nby-m2&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQF0OiL_ZljHSgAAAVihIC9Yi9QjSboaXtskAQvOOhjKV3cUsKb6M2pLMIkvRKRy-dnMCty-aPlPul8fZVnfstm4BVo4JYt6eskLechlVMRQ4p2AJSgEvapNw_B2d1wFXdmtxOglsUNtzNDXjvIEw9cbLob9qFtgmZDR4uOvj7owh_WsYsOp3eZifZAyfZaaaxxo4U2zz9jD9XzIAmpFjbPm4Q&eid=0-ivzc6nby-m2


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivzc6nby-m2&a=customerServiceUrl&ek=invite_guest

© 2016 LinkedIn Corporation, 1000 West Maude Avenue, Sunnyvale, CA 94085. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Kevin Avignon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=ACfTFxzN&invitationId=6208290946057064448&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7E4fqi54%7Eiw6mrfao%7E2i

View Kevin Avignon&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=ACfTFxzN&invitationId=6208290946057064448&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7E4fqi54%7Eiw6mrfao%7E2i





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-4fqi54-iw6mrfao-2i&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-4fqi54-iw6mrfao-2i&loid=AQFQqSg_cFBb8gAAAVi8MgbqSctchIwQRUjk8mBklJNttieizQ7uEtSjBEcHCEdT_Ddd4NllZy2Z6yXa1X5mGNXRmeT-ih0wlrCxFtjp97jzHPhy5BHSTBr4iO5np2TOUEEDB_twBiqTaRS33ns8RuPqRZsEVlfkIc7ZZtlVx4Ljji_eK4B19NYXNsqruMorRyBhwq2AVq5VL7APszMIdytD0AIMsg

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-4fqi54-iw6mrfao-2i&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jhoffner** [comment]
@Kavignon Not sure whats going on but your linkedin stuff is blowing up our issues all over the place. Anyway you can turn that off?

**Comment by Kavignon** [comment]
My LinkedIn stuff?

**Comment by jhoffner** [comment]
Yeah look at this thread (and any other thread that you are on). You have some sort of linkedin invitation auto responder turned on.

**Comment by Xeleema** [comment]
Just joined CodeWars and went RED :)  Would love to see PowerShell added (and can contribute Kata once I'm more comfortable w/ the interface and the community).

If CodeWars is running on Ubuntu, Centos, or Red Hat, then it should be possible to setup "PowerShell Core".  [Instructions](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#centos-7) and downloads ("[Releases](https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-alpha.18
)") are available on Microsoft's GitHub for CentOS7/RHEL7.

**Comment by kenmaglio** [comment]
I would be willing to help out as much as possible once the basic docker image and scaffolding for codewars building is in place. Or I can also help learn that process..  PowerShell Core is more than sufficient to do CodeWars Kata's.   

Already run on PS Core on Linux on a few machines in our environment

**Comment by PowerSchill** [comment]
I would also be willing to help out with this task.
