### ISSUE TITLE
Coffeescript has troubles with indentation.

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#197]
This code with exactly the same indentation works perfectly on coffeescript page bou not on codewarts can you fix it?

```
arr2bin=(arr)->
  if arr.filter( (n)-> !(n%1==0) ).length
    return '0'
  sum = arr.map((x)-> if typeof x =="number" then x else 0).reduce((x,y)->(x+y))
  return sum.toString(2);

alert arr2bin([null])== "0"
```

**Comment by Dan-Nolan** [comment]
Looks fine to me except `alert` isn't available. Can you reduce the problem to something specific?

**Comment by javatlacati** [comment]
try with the code without alet, it is not allowed on any new Kata. The alert code is for you can test it on coffeescript page.

**Comment by Dan-Nolan** [comment]
https://www.codewars.com/kumite/576836aa16447acb370004c7?sel=576836aa16447acb370004c7

**Comment by javatlacati** [comment]
Great it works now ty :)
