### ISSUE TITLE
Can't delete language

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#198]
It shows the message:

> Comments is invalid

**Comment by Dan-Nolan** [comment]
Can you add steps to reproduce or more detail?

**Comment by jhoffner** [comment]
Yeah this is pretty vague. Also sounds like a CW issue not a Runner one.

**Comment by javatlacati** [comment]
For this Kata: https://www.codewars.com/kata/arguments-to-binary-addition/discuss/javascript open coffeescrit and click the X icon. Error message shows.
