### ISSUE TITLE
Error with typescript runner

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#200]
Take a look at [this translation](https://www.codewars.com/kumite/57730b20c37fc4f75b00256b?sel=57730b20c37fc4f75b00256b)

If you erase the description section with typescript if passes, but if you add it it will throw the following error:

```
../tmp/typescript116528-17-jj8esg.c35raa714i/spec.ts(1,1): error TS1084: Invalid 'reference' directive syntax.
../tmp/typescript116528-17-jj8esg.c35raa714i/spec.ts(2,1): error TS1084: Invalid 'reference' directive syntax.
/runner/lib/util.js:21
            else throw error;
                 ^
```

>Error: Command failed: tsc --module commonjs /tmp/typescript116528-17-jj8esg.c35raa714i/spec.ts
>
>    at ChildProcess.exithandler (child_process.js:202:12)
>    at emitTwo (events.js:106:13)
>    at ChildProcess.emit (events.js:191:7)
>    at maybeClose (internal/child_process.js:850:16)
>    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

**Comment by spencerwi** [comment]
Typescript references are typically written as self-closing tags. I'm not sure why editing the description makes an impact, but 

```ts
/// <reference path="/runner/typings/main/ambient/mocha/index.d.ts" ></reference>
/// <reference path="/runner/typings/main/ambient/chai/index.d.ts" ></reference>
```

should be 

```ts
/// <reference path="/runner/typings/main/ambient/mocha/index.d.ts" />
/// <reference path="/runner/typings/main/ambient/chai/index.d.ts" />
```

**Comment by jhoffner** [comment]
No one fixed this, it should still be an issue. I was actually going to work on it today.

**Comment by jhoffner** [comment]
See #473 for more details. I'll actually re-close this one since its reported in more detail there.

**Comment by samjewell** [comment]
@jhoffner you've referenced issue #473 in your last comment, but there is no issue with that number in this repo. Can you update your last comment, with the correct issue number if there is an issue which replaces this one?

I'm seeing the same issue when editing a Typescript Kata:

- When I update the references at the top of the Sample Test Cases to be self-closing, the tests pass fine.
- Then when I click SAVE, for some reason my code gets updated by the save action, and the references are all updated to have separate opening and closing tags, which then fails tests.

**Comment by kazk** [comment]
@samjewell

- Codewars/codewars.com#473
  - Codewars/codewars.com#361
