### ISSUE TITLE
Dart - undefined returned for some syntax errors [Kumite Testing]

### ISSUE THREAD

**Issue by lteacher** [Codewars/codewars-runner-cli#201]
Still in some examples a syntax error causes undefined to be returned such as this example just missing the semicolon in the test fixture
![image](https://cloud.githubusercontent.com/assets/6103860/16508483/aade42be-3f76-11e6-8796-23c29799350a.png)

More obvious errors do seem to return:
![image](https://cloud.githubusercontent.com/assets/6103860/16508510/ec408424-3f76-11e6-9188-797ab578e3d3.png)

**Comment by jhoffner** [comment]
Latest dart updates have been deployed. Is this still an issue?

**Comment by lteacher** [comment]
Sorry I was't so clear here. The changes mostly look good but I had to stop testing last time as the issues basically meant that errors didn't show at all. 

Now just putting the issues up for the more smaller edge cases I think which I can look at and then i'll address the issue in any subsequent change.

**Comment by lteacher** [comment]
Hmmm in this example there is no `error:` or `warning:` with the failed to spawn isolate message, instead its just the failed to load message then the text.... here are the 3 examples.. 

**Missing bracket in main code**
```sh
Failed to load "/tmp/dart/11662-170-16u1tlt.dart":
Unable to spawn isolate: 'file:///tmp/dart/11662-170-16u1tlt.dart': warning: line 11 pos 19: unbalanced '(' opens here
            Person(this.firstName,this.lastName
                  ^
line 12 pos 11: unbalanced '}'
          }
```

**Missing end of a literal**
```sh
Failed to load "/tmp/dart/11662-170-1v2wxao.dart":
Unable to spawn isolate: 'file:///tmp/dart/11662-170-1v2wxao.dart': error: line 13 pos 48: unterminated string literal
          test('function returns 50, () async {
                                               ^
```

**New - Missing semicolon in the test fixture**
```sh
Failed to load "/tmp/dart/11662-170-1ledmxe.dart":
line 13 pos 42: semicolon expected
          expect(returnFive(), equals(4))
                                         ^
```

I previously assumed that the `error:` or `warning:` would be there but apparently not the case
