### ISSUE TITLE
Dart - excessive runtime output [Kumite Testing]

### ISSUE THREAD

**Issue by lteacher** [Codewars/codewars-runner-cli#202]
The runtime displayed is either incorrect, or way to slow. I think I recall its the first one... I'm pretty sure its not correct and rather an error in the test json output or however its interpreted to decide the total runtime.
![image](https://cloud.githubusercontent.com/assets/6103860/16508592/bac978fa-3f77-11e6-8e7d-0f986f03be15.png)

**Comment by jhoffner** [comment]
Is there a VM startup cost? Its a fresh container instance on each run.

**Comment by lteacher** [comment]
I guess the time is the mocha test time, there must be some slow startup time in the test framework since the mocha tests consistently show similar time for the tests. 

The dart code without the tests, so referencing the VM question, are about 150ms or so for me. I messed with not parsing the json output and found no difference so that definitely isn't it.

I also now just now removed the test config write to disk and ran without the json results and still shows a 1412ms run time.

@jhoffner I think i saw there is a 2 sec timeout usually, though that is the mocha default I guess, what is the impact of such a slow average time?

**Comment by lteacher** [comment]
Well aside from this issue and #188 the rest of the changes look good have done a bit of testing there and cant find further problems. [Here is a link to a kumite](https://www.codewars.com/kumite/578a0d9f7c77f57eeb000091?sel=578a0d9f7c77f57eeb000091) with the latest stuffs
