### ISSUE TITLE
Elixir renders an INFO REPORT message when test cases are used

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars-runner-cli#203]
Output always includes 
```
=INFO REPORT==== 1-Jul-2016::06:52:32 ===
application: logger
exited: {{shutdown,{failed_to_start_child,'Elixir.GenEvent',undef}},
{'Elixir.Logger.App',start,[normal,[]]}}
type: temporary
```

Seems even though Elixir 1.2.4 is specifically installed on the image, the OTP somehow got updated and is causing possible version issues and backwards incompatible changes.

Backwards incompatible issues include warnings that fail the execution since they write to STDERR, even though all tests pass.

@cris we could use your help on this.

See https://github.com/Codewars/codewars.com/issues/428 for more info.

**Comment by jhoffner** [comment]
Also, the Elixir specs no longer pass. I'm not sure how the docker image got updated since it should have been frozen. The file hasn't changed in 2 months.

**Comment by jhoffner** [comment]
In fact, even just running `elixir -v` causes the info report to be rendered:
```
Erlang/OTP 19 [erts-8.0] [source-6dc93c1] [64-bit] [smp:3:3] [async-threads:10] [hipe] [kernel-poll:false]


=INFO REPORT==== 1-Jul-2016::19:06:19 ===
    application: logger
    exited: {{shutdown,{failed_to_start_child,'Elixir.GenEvent',undef}},
             {'Elixir.Logger.App',start,[normal,[]]}}
    type: temporary
Elixir 1.2.4

```

It reports 1.2.4 as being installed but @g964 indicated that the versions being reported seem to vary somehow.

**Comment by jhoffner** [comment]
OK looks like OTP was not set in stone in the Dockerfile. I'm updating it to always install 18 and then we should be good.

**Comment by jhoffner** [comment]
Reverting OTP ending being more complicated than I have bandwidth for right now. It would be easier if I knew more about Erlang/Elixir. For now I have reverted the docker image to an older version and the image is now frozen from any new builds until it can be fixed. The most ideal would be to keep the upgraded OTP 19 version but I don't know how to turn the info/warnings off. 

@cris if you can lend your knowledge on this when you get a chance that would be greatly appreciated. 

I am closing this issue and opening a new one indicating that the image is frozen.

**Comment by cris** [comment]
@jhoffner 
The issue was that Elixir 1.2.4 is not compatible with Erlang R19. You did everything right, reverting Erlang runtime to R18.

If we want to update Elixir & Erlang - we need to update Elixir to `v1.2.6` or to `v1.3.x` and Erlang to `R19`. I will update locally and check how it's doing. Actually Elixir `v1.3.x` changed also ExUnit (added groups with `describe`), so need to be sure, all specs will pass after upgrade.

Also, supporting `describe` will for sure require some changes in ExUnit runner. Will ping you with PR.
