### ISSUE TITLE
Clojure Tests/Submission Pass; summary not updated, cannot "finalize"

### ISSUE THREAD

**Issue by mattwellss** [Codewars/codewars-runner-cli#215]
Trying to submit my solution for the [Printer Error](https://www.codewars.com/kata/56541980fa08ab47a0000040/train/clojure) kata, and the test passes, but the summary is not reflective of that[1].

When I submit the solution in hopes that it lets me save my solution and move on, the same issue reoccurs [2].

I have run the tests and submitted using Firefox Developer (49a2) and Opera Dev (40.0.2288) with all content blockers disabled.

Would any other information be useful in debugging this?

[1](https://cloud.githubusercontent.com/assets/1776257/17079739/1646fc54-50ce-11e6-9acb-c445ccf555d5.png)
[2](https://cloud.githubusercontent.com/assets/1776257/17079763/989c030c-50ce-11e6-9b20-2ccbaeb7e29f.png)

**Comment by oleksandr-oksenenko** [comment]
I've got the same issue.

**Comment by mattwellss** [comment]
@oleksandr-oksenenko I just tried again and was successful. If this worked for you I'm going to assume this was a temporary issue with the Codewars Clojure runner and close it.

**Comment by oleksandr-oksenenko** [comment]
@mattwellss yeah, working for me as well. Thanks for update.
