### ISSUE TITLE
PHP Coderunner sometimes doesn't handle Errors / Exceptions properly

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars-runner-cli#223]
Sometimes, when the PHP code throws a certain type of Error or Exception, the PHP code runner (or the PHPUnit testing framework, I'm not sure which one is causing the problem) does not catch or handle the error properly which causes certain tests to be skipped and the faulty solution to be accepted even when it shouldn't be.

The screenshot below is an example of this bug (the highlighted section in the screenshot are the tests that were skipped due to the uncaught Error / Exception):

![2016-07-29 11 18 52](https://cloud.githubusercontent.com/assets/7777884/17253684/57734bea-55e4-11e6-915a-1e6f2f9b7e11.png)

**Comment by jhoffner** [comment]
@Dan-Nolan any thoughts on what this might be?

**Comment by jhoffner** [comment]
This also seems to be the same issue as #221

**Comment by OverZealous** [comment]
I've got a fix for it coming.

**Comment by OverZealous** [comment]
Closed via #226
