### ISSUE TITLE
PHP showing Warning as the test case desriptions

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#231]
Hello if I change

```
class MyTestCases extends TestCase
{
    public function testThatSomethingShouldHappen() {
```

to anything else like

```
class MyTestCases extends TestCase
{
    public function ArrayOfStrings() {
```

Runner shows as result
![warning](https://cloud.githubusercontent.com/assets/1063901/17832779/cd543c8c-66d0-11e6-9415-33e05aaf27b0.PNG)

**Comment by OverZealous** [comment]
All PHP tests must start with `test`, though I agree we need better feedback if there are not tests in a test suite.

**Comment by javatlacati** [comment]
Interesting sorry never used phpUnit, but anyway.. I think it should say something about that on comments at the initial sample phpunit code :)

**Comment by kazk** [comment]
Closing this because it has `// test function names should start with "test"` now.
