### ISSUE TITLE
JavaScript - Object.values Unavailable for Tests, Available for Submissions

### ISSUE THREAD

**Issue by Dan-Nolan** [Codewars/codewars-runner-cli#235]
For some reason `Object.values` ([MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values)) is available as a method when submitting code, but when running tests it is not. It would be okay if it was one way or the other, but the inconsistency [is confusing people](http://www.codewars.com/kata/reviews/57c5c8c4097ac3c35e000015/groups/57c5ce8854987154aa0000a1).

**Comment by Dan-Nolan** [comment]
Plan on looking into this further when I get the chance, just putting it here as reminder.

**Comment by OverZealous** [comment]
Interestingly, this isn't even part of ES2016, so it's not really valid yet.

Since all the code is run through the same version / build process, it might be that sometimes code is running using pure Node 6 and sometimes with Babel.

**Comment by Dan-Nolan** [comment]
Turns out it was added in preloaded code for that particular kata. :smile:
