### ISSUE TITLE
link not working

### ISSUE THREAD

**Issue by g964** [Codewars/codewars-runner-cli#237]
Jake gives me this link to have a look: 
https://github.com/Codewars/codewars.com/issues/github.com/Codewars/codewars-runner-cli
but I get "Error 404. Page not found".

**Comment by Dan-Nolan** [comment]
Seems like two separate links, https://github.com/Codewars/codewars-runner-cli/ and https://github.com/Codewars/codewars.com/issues/

Maybe they got appended somehow?
