### ISSUE TITLE
Random tests are currently impossible in Rust

### ISSUE THREAD

**Issue by error256** [Codewars/codewars-runner-cli#240]
I'm not really sure but it looks like there's no way to generate random numbers properly without using an external crate which requires adding a dependency to Cargo.toml project file.
https://doc.rust-lang.org/rand/rand/index.html
https://stackoverflow.com/questions/30735490/unresolved-name-randthread-rng

**Comment by lteacher** [comment]
Hi,

Originally there was a solution which used cargo but it was more irritating for some various reasons and now just `rustc` is used. It looks like either way an enhancement is required to do it.

**Comment by DonaldKellett** [comment]
*Bump*

@jhoffner Do you know an active contributor to this Repo who might just be able to allow for random input generation in Rust?  I have just received a Rust translation to one of my Kata without random tests and I would love to approve it (the overall translation quality is good) but I can't until he/she has added random tests to it.
