### ISSUE TITLE
submit or run test does not work always 

### ISSUE THREAD

**Issue by creepystranger** [Codewars/codewars-runner-cli#244]
I found this out randomly while doing some Kata , the test button and submit button was not working for me ,but If I right click and do an inspect element in chrome and make the chrome window a bit small it works .I have recorded the steps which I feel could be useful for debugging ,
point of note ,the buttons does not work even when the console is open if I stretch the chrome window 

[issue.zip](https://github.com/Codewars/codewars-runner-cli/files/502299/issue.zip)

**Comment by jhoffner** [comment]
Is this still an issue?
