### ISSUE TITLE
Error with c++ runner

### ISSUE THREAD

**Issue by stev-0** [Codewars/codewars-runner-cli#249]
When attempting this Kata https://www.codewars.com/kata/sort-and-star/train/cpp 

A number of people including me have the message:

`-isystem /runner/frameworks/cpp  fatal error: 'boost/algorithm/string/join.hpp' file not found
#include <boost/algorithm/string/join.hpp>`

when submitting the test, despite all tests passing, and not including any external files.

**Comment by Dan-Nolan** [comment]
Looks like the Translation author included that file in the test cases and it's not available. 

I know people wanted an upgrade to the boost libraries and some documentation on what's available. The current libraries that are included were unintentional so hopefully not too many people are making use of them. Will hopefully be looking into that soon. :)

**Comment by Dan-Nolan** [comment]
Not sure how it passed validation in the first place, but I removed the include and the reference solution is still working. Should be good to go now

**Comment by stev-0** [comment]
Cool, thanks

**Comment by Dan-Nolan** [comment]
Thanks for bringing it up!
