### ISSUE TITLE
C++ Test Framework Cheat

### ISSUE THREAD

**Issue by LawfulHacker** [Codewars/codewars-runner-cli#252]
The user Durdo [reported](http://www.codewars.com/kata/base-2/discuss#58091ac3b44adbc16b000ebe) an error on my Kata and during the test for his issue I found that the C++ test framework has an issue which allow us to cheat.

It just require one test passing if the real function doesn't return a value.

The following test if pasted on the code, allow us to pass any C++ Kata.

``` c++
Describe(ImJustCheating)
{
    It(BecauseIcan)
    {
        Assert::That(0, Equals(0));
    }
};
```

Tested Katas which allowed this trick:

https://www.codewars.com/kata/strings-mix/train/cpp
https://www.codewars.com/kata/magnet-particules-in-boxes/train/cpp
https://www.codewars.com/kata/getting-along-with-integer-partitions/train/cpp
https://www.codewars.com/kata/valid-braces/train/cpp
https://www.codewars.com/kata/build-a-pile-of-cubes/train/cpp

**Comment by Dan-Nolan** [comment]
Good find, will get on this soon.

**Comment by LawfulHacker** [comment]
An update on this issue:

I tested this again and now the server is return

```
SIGILL
Process exited prematurally with a SIGILL signal.
```

Maybe this was already fixed.

**Comment by kazk** [comment]
This used to work by crashing the process after passing one test case, making this equivalent to early exit cheat. This won't work anymore because the exit code is checked.

There're many other ways to bypass tests and we rely on the community to catch them. Repeated offenders are permanently banned from the site.
