### ISSUE TITLE
SQL vendors and ANSI SQL

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#253]
I think that your SQL Katas were creating having on mind ANSI SQL, but it doesn't seem to be reflected.
You have to chooose a provider and then while resolving the Kata the other providers can't be used even if listed.

Under the premise of having a test framework based on Ruby and exactly the same SQL query:

1. ¿Can you please create another type of Kata where if your SQL passes on all vendors (ANSI SQL) solution can pass?
2. ¿Can you create a type of Kata for every DB vendor so we can have PostgreSQL Katas and SQLite Katas?

**Comment by jhoffner** [comment]
If a query can be used for both providers it will work automatically. If not then there is nothing we can do. It's a major effort to try to support both separately.
