### ISSUE TITLE
Make PL/pgSQL a language, not language version of SQL

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#255]
Related to #253 I've checked a [Kata ](https://www.codewars.com/kata/580fe518cefeff16d00000c0)that is not solved by ANSI SQL since it implies functions and it may even use already PL/pgSQL as you can see on [this](https://www.codewars.com/kata/reviews/5810678f418e60612900003d/groups/5812f8e3bee85709d0000251) or [this](https://www.codewars.com/kata/reviews/5810678f418e60612900003d/groups/58126fb76858b6903f0002be) solution.
As an addition perhaps you can copy your docker image and create a new Kata type for **PL/pgSQL** with some minor modifications to your runner.

**Comment by jhoffner** [comment]
I'm not sure I follow. We already have pgSQL support. We have the language version feature for choosing different versions.

**Comment by jhoffner** [comment]
See #258 for details of how to use PL/pgSQL. Does this cover your use case?

**Comment by javatlacati** [comment]
no, create a new Kata type for PL/pgSQL?

**Comment by kazk** [comment]
Closing because I don't think we're going to make pgSQL a separate language at this point.
