### ISSUE TITLE
language/version dropdown menus in some of the Swift kata are not functioning

### ISSUE THREAD

**Issue by jasondebolt** [Codewars/codewars-runner-cli#257]
IMPACT:
The language/version dropdown menus in some of the Swift kata are not functioning. 

ERROR SEEN:
"Request Timeout: Language undefined is not supported"

STEPS TO REPRODUCE:

1) Open the following Kata for the Swift language:
https://www.codewars.com/kata/sum-of-all-the-multiples-of-3-or-5/train/swift

Notice that language and version dropdown menus are empty.

2) Implement the solution and click "RUN SUITE"

3) Notice an error saying "Request Timeout: Language undefined is not supported"

I'm guessing this error arises because the language and version are unable to be selected in the drop down menu.

2 out of the 9 current Swift kata appear to be impacted by this issue:
https://www.codewars.com/kata/stringy-strings/train/swift
https://www.codewars.com/kata/sum-of-all-the-multiples-of-3-or-5/train/swift

**Comment by jhoffner** [comment]
Thanks, fixed.

**Comment by jasondebolt** [comment]
Great, thanks!

I noticed that the two problems mentioned were fixed, but I just created a
new kata and I'm seeing the issue again:

https://www.codewars.com/kata/linked-lists-push-and-buildonetwothree/train/swift

**Comment by jhoffner** [comment]
Works for me. Maybe you saw this issue before I deployed (about 20 minutes ago).

**Comment by jasondebolt** [comment]
Strange. I noticed that your recent fix worked for the two kata I mentioned
in the bug, but a third one (the linked list kata) that I just created is
showing the same behavior. I'll try again tomorrow.

https://www.codewars.com/kata/linked-lists-push-and-
buildonetwothree/train/swift

Thank you sir.

Jason

**Comment by jasondebolt** [comment]
Hi Jake,

What do you think about adding a button for Swift kata that allows users to download a complete XCode project with the solution setup, preloaded code, and test cases for a given Kata?

I don't think any other code challenge websites offer this functionality. Would be amazing.
