### ISSUE TITLE
PostgreSQL Missing features? DO

### ISSUE THREAD

**Issue by slothpie** [Codewars/codewars-runner-cli#258]
The sql statement below doesn't seem to work, the error being: 
```
There was an error with the SQL query:

PG::SyntaxError: ERROR:  syntax error at or near "DO"
LINE 2: DO $$
        ^
```

Query:

```sql
DO $$
BEGIN
    PERFORM fn_createProductCrosstab();
END;
$$
```

After doing some research I believe the currently version of PostgreSQL should support the `DO` statement but whenever I have attempted to use it I receive the above error.

**Comment by slothpie** [comment]
After inspecting how the CLI breaks up the commands I have found a way to format my given code to properly execute the `DO` statement.

I guess there's no issue and I'll close this ticket :)

**Comment by jhoffner** [comment]
What is the way to properly format?

**Comment by slothpie** [comment]
I can't really explain but here's the gist of it:
```sql
CREATE EXTENSION IF NOT EXISTS tablefunc;

CREATE OR REPLACE FUNCTION fn_createProductCrosstab() RETURNS VOID AS
$$ DECLARE 
BEGIN 
-- stuff
END; $$
LANGUAGE plpgsql; DO $$
BEGIN
    PERFORM fn_createProductCrosstab(); END; $$;
SELECT * FROM product_table;
```

It seems because I had a function in my query I could not add a newline after the ```LANGUAGE plpgsql; ``` I had to append that straight after the `LANGUAGE plpgsql; `. I'm not too sure why... I haven't looked into that much but when it gets parsed into the $sql_command variable the create function and do statement is one command and the SELECT is a single one.

Hopefully it's clear enough..

**Comment by slothpie** [comment]
I believe I have found the issue..
SQL
```sql
LANGUAGE plpgsql; 
DO $$
```

Converts to this when parsed
```
$$\nLANGUAGE plpgsql", "\nDO $$\nBEGIN\n
```
It's the leading `\n` character which is what I believe would be causing the issue.

**Comment by jhoffner** [comment]
ah I see. In your case multiple statements need to be run as one operation, but not all of the statements. Hmm. This is a pretty tricky fix.

**Comment by jhoffner** [comment]
This should be better now.

**Comment by slothpie** [comment]
Do you know if this will affect any existing solutions and katas?

**Comment by jhoffner** [comment]
I just realized it broke WITH queries, because it was determining if a statement needed to return a result set based off of "SELECT" being at the beginning. I'm adding "WITH" right now but can you think of any other commands that might be at the start of a select operation?
