### ISSUE TITLE
Haskell Timeouts

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#260]
The site hasn't been working for about the last 5 hours as [reported by users in the platform](https://www.codewars.com/kata/555615a77ebc7c2c8a0000b8/discuss#581b41a20fb9569da500027d).

**Comment by SergiuB** [comment]
Now it seems to be working for Javascript (and maybe other environments), but for Haskell I always get the same error:
```
{"stdout":"","stderr":"Process was terminated. It took longer than 6000ms to complete\n","status":"max_time_reached"}
```

**Comment by jhoffner** [comment]
Servers seem to be running a bit slow today, though honestly until someone who knows Haskell can get into that image and fix it, I dont know if Haskell support is going to go the distance. I don't know Haskell and I'm spread way too thin as it is to try to fix it myself. The Haskell image hasn't been updated in well over a year.

**Comment by javatlacati** [comment]
can you add the label help wanted?

**Comment by wizzup** [comment]
AFAIK, Timing on [runhaskell](https://github.com/Codewars/codewars-runner-cli/blob/00a657c99f347ef8ecb075b8a19ebab7d8fc1535/lib/runners/haskell.js) would actually count `compile time + run time` so, like many compiled program, it could take time to compile while the real `run time` may just a only litttle portion of total time.

I wonder if it is possible to just count only `run time` with current runner.

**Comment by wizzup** [comment]
To reply to my own comment.  You don't need additional Main.hs file.
```bash
$ ghc -o run -main-is MyLibTest.main MyLibTest.hs
[1 of 2] Compiling MyLib            ( MyLib.hs, MyLib.o )
[2 of 2] Compiling MyLibTest        ( MyLibTest.hs, MyLibTest.o )
Linking run ...

$ ./run 

test myFunc
  works for some examples
  returns 0 if array is empty

Finished in 0.0002 seconds
2 examples, 0 failures
```
I wish I could help on this by I don't know javascript and don't fully understand the runner yet.

**Comment by jhoffner** [comment]
Anyone else still having consistent timeout issues?

**Comment by lilred** [comment]
I'm having inconsistent timeout issues, retrying multiple times does help.
