### ISSUE TITLE
node-runner docker don't have bash

### ISSUE THREAD

**Issue by wizzup** [Codewars/codewars-runner-cli#262]
from README.md (line no. 32)
``` 
docker run --rm -it codewars/node-runner bash
```

but I got

``` bash
$ docker run --rm -it codewars/node-runner bash
module.js:457
    throw err;
    ^

Error: Cannot find module '/runner/bash'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by jhoffner** [comment]
Its because you need to override the entry point if you are going to use docker directly. 

`docker run --rm -it --entrypoint bash codewars/node-runner`

**Comment by wizzup** [comment]
> Its because you need to override the entry point if you are going to use docker directly

Please update README.md so others won't follow the same mistake I made.
