### ISSUE TITLE
Typescript : Still problems when CW saves a translation

### ISSUE THREAD

**Issue by g964** [Codewars/codewars-runner-cli#267]
When you save, trying to publish a TS translation,  ```<``` or ```>``` are replaced (even in the code) by ```&lt;``` or ```&gt;``` and so the code becomes impossible to run. Same thing in:
```
/// <reference path="/runner/typings/main/ambient/mocha/index.d.ts" />
/// <reference path="/runner/typings/main/ambient/chai/index.d.ts" />
```
TS should have remained in Beta...

**Comment by jhoffner** [comment]
Yeah I regret adding it. It's more trouble than it's worth. I'll take another look there must be a regression.

Thanks,

--
Jake Hoffner
Sent with Airmail

**Comment by g964** [comment]
Seems fixed. Thanks!

**Comment by javatlacati** [comment]
if fixed please close 😄
