### ISSUE TITLE
C++ - no output returned

### ISSUE THREAD

**Issue by harrylippy** [Codewars/codewars-runner-cli#276]
I've seen this on several katas.  I'm reporting the issue on "reverse-or-rotate" (https://www.codewars.com/kata/reverse-or-rotate/train/cpp)

The issue is, I get absolutely zero feedback when either running the examples or running the suite.  I get:

Time: 14ms Passed: 0 Failed: 0
Test Results:
  revRot_Tests
  Fixed__Tests

Frustrating to spend the time coding up the kata, then getting no feedback whatever.

**Comment by jhoffner** [comment]
Sorry to hear that. Looks like not everyone is having this issue, I can't reproduce. Please provide the solution that you were running, browser info, and any errors that may have been thrown (by opening up your web inspector and looking at the console output). 

Thanks

**Comment by jhoffner** [comment]
This also looks like it might be related to #275

**Comment by harrylippy** [comment]
I'm using Chrome Version 54.0.2840.71 m (64-bit) on Windows 10.

Here's what I see in the output window:

![image](https://cloud.githubusercontent.com/assets/361489/20464927/c59354d0-af17-11e6-909b-04f176aaca38.png)

Here's the output from the web inspection (I tried "Run Examples" and "Run Suite"):

![image](https://cloud.githubusercontent.com/assets/361489/20464936/e9141214-af17-11e6-85e4-f0289c576196.png)

**Comment by harrylippy** [comment]
Here's the solution I was trying (work in progress):

#include <string>
#include <algorithm>

class RevRot
{
private:
    static std::string reverse(const std::string &strng, unsigned int sz);
    static std::string rotate(const std::string &strng, unsigned int sz);
    static unsigned int sumCubes(const std::string &strng);

public:
    static std::string revRot(const std::string &strng, unsigned int sz);
};

std::string RevRot::reverse(const std::string &strng, unsigned int sz)
{
    std::string reversed = strng;
    
    for (int i = 0; i < sz/2; i++)
    {
        char tmp = reversed[i];
        reversed[i] = reversed[sz-i-1];
        reversed[sz-i-1] = tmp;
    }
    
    return reversed;
}

std::string RevRot::rotate(const std::string &strng, unsigned int sz)
{
    std::string rotated = strng;
    char tmp = rotated[0];
    
    for (int i = 1; i < sz; i++)
        rotated[i-1] = rotated[i];
    rotated[sz-1] = tmp;
    
    return rotated;
}

unsigned int RevRot::sumCubes(const std::string &strng)
{
    unsigned int sum = 0;
    
    for (char c : strng)
    {
        int digit = c - '0';
        sum += digit * digit * digit;
    }
    
    return sum;
}

std::string RevRot::revRot(const std::string &strng, unsigned int sz)
{
    std::string result = "";
    
    if ((sz <= 0) || (sz > strng.length()))
        return "";
        
    for (int pos = 0; pos < strng.length(); pos += sz)
    {
        char chunk[sz+1];
        chunk[sz] = 0;
        if (strng.copy(chunk, sz, pos) == sz)
        {
            std::string modified;
            
            if (RevRot::sumCubes(chunk) % 2 == 0)
                modified = RevRot::reverse(std::string(chunk), sz);
            else
                modified = RevRot::rotate(std::string(chunk), sz);
                
            result += modified;
        }
    }
}

**Comment by harrylippy** [comment]
AAAAAAAAAAAANNNNNNNNNNNNNNNDDDDDDDDDDDDDDDDDD......there it is.  No return statement in the revRot method.  Sorry to have wasted your time, @jhoffner.

**Comment by harrylippy** [comment]
User error.
