### ISSUE TITLE
Unit test bypass by early script termination

### ISSUE THREAD

**Issue by kdask** [Codewars/codewars-runner-cli#279]
### Description

It is possible to bypass unit tests almost entirely by returning correct output for the first test and then just  terminating.

### Reproducing
```ruby
def kata_main_method s
  # Provide correct output for the first test
  if s == "First test input"
    return "Correct answer" 
  end

  # Terminate
  exit 0
end
```

I've managed to reproduce it for Python and Ruby on various katas.

### Expected behavior

Other unit tests should fail.

```
Time: 298ms Passed: 1 Failed: 20
  <...>
```
### Actual behavior

Other unit tests are completely ignored.

```
Time: 350ms Passed: 1 Failed: 0
Test Results:
  Basic tests
✔ Test Passed: Value == true
You have passed all tests! :)
```

**Comment by kazk** [comment]
There're many ways to bypass tests and we rely on the community to catch them. Repeated offenders are permanently banned from the site.
