### ISSUE TITLE
Allow solution even when Failed to process output too much data was written to STDOUT.

### ISSUE THREAD

**Issue by robinmattheussen** [Codewars/codewars-runner-cli#289]
I'm trying to solve this kata: https://www.codewars.com/kata/53d40c1e2f13e331fc000c26

Unfortunately, I keep getting

> Failed to process output. It is possible that too much data was written to STDOUT.

I understand why this is done, and I can see that [the buffer length is already pretty high](https://github.com/Codewars/codewars-runner-cli/blob/24f35810cb8c2579e2c6fedacb289597466ea00f/lib/shovel.js#L186-L189). However, this still prevents people from submitting their (working) solutions every once and a while.

Is it not possible to simply to display a more "condensed" version of the output window? For example, just show the tests that succeeded and failed, but not the output? That way you would still be able to submit your solutions.

P.S.: My kata solution fails on both www.codewars.com and preview.codewars.com

**Comment by jhoffner** [comment]
This has been approved somewhat. The output is all mixed together so we probably can't cherry pick it the way you wanted but you at least now should a little bit more useful of an output response.
