### ISSUE TITLE
New Elixir Version

### ISSUE THREAD

**Issue by allonhadaya** [Codewars/codewars-runner-cli#291]
Hey, I was recently working on a [kata](https://www.codewars.com/kata/exclamation-marks-series-number-3-remove-all-exclamation-marks-from-sentence-except-at-the-end) and came up with this solution:

```elixir
defmodule Solution do
  def remove(s) do
    # assume s does not contain the unit separator character
    unit_separator = "\x1F"
    s
    |> String.replace_trailing("!", unit_separator)
    |> String.replace("!", "")
    |> String.replace_trailing(unit_separator, "!")
  end
end
```

Turns out that `String.replace_trailing` had a bug fix delivered in [1.2.5](https://github.com/elixir-lang/elixir/releases/tag/v1.2.5).

I'm not sure if this alone is enough of a reason to offer a new version of the language, or how exactly you decide that, but I am under the impression that the language / standard library have made quite a bit of progress this past year [1.2.4 -> 1.3.4](https://github.com/elixir-lang/elixir/compare/v1.2.4...v1.3.4).

Let me know what you think.

**Comment by ice1000** [comment]
The newest is 1.5 https://preview.codewars.com/topics/feature-requests#5997de3dc2bd3a773700007b

**Comment by DCrow** [comment]
Would be great, since newest Elixir also includes new Erlang features

**Comment by kazk** [comment]
If the upgrade doesn't break existing content, then we can just swap the installed version, but this is unlikely.
- Elixir v1.5.0 is 100% compatible with v1.2.4
- ExUnit is also compatible
- Existing content doesn't use deprecated features

I've proposed having versioned images, e.g., having images `elixir-runner:1.2.4` and `elixir-runner:1.5.0`, but this requires some rework and not happening soon.

More quicker solution will be to install both versions in the same image using [asdf](https://github.com/asdf-vm/asdf) with [asdf-elixir](https://github.com/asdf-vm/asdf-elixir), but I haven't looked into them yet.

**Comment by koskoci** [comment]
+1

**Comment by kazk** [comment]
This is on our roadmap. The new system we've been working avoids the issue of breaking existing contents. See https://github.com/Codewars/codewars-runner-cli/pull/528#issuecomment-348716997

**Comment by kazk** [comment]
We'll have Elixir 1.6 available on the new system.
See #566 for future updates/discussions.
