### ISSUE TITLE
Failing to test or submit solution , help

### ISSUE THREAD

**Issue by mikeyny** [Codewars/codewars-runner-cli#293]
I have been failing to test or submit solutions to codewars for the past two weeks now , I've tried using both Firefox and chrome to no luck. When i try and test my solutions ,it simply doesn't respond , when i click submit ,it just gives me a blank reply on the response tab.

**Comment by jhoffner** [comment]
Try changing the URL to a non https version and let me know if that helps.

**Comment by mikeyny** [comment]
@jhoffner  No luck :(

**Comment by jhoffner** [comment]
OK. Are there any errors in the console output?

**Comment by mikeyny** [comment]
![codewars](https://cloud.githubusercontent.com/assets/18025235/21752967/dcbb4d4e-d5ea-11e6-920a-c3d19f41f677.png)
### Errors with https url

![code 2](https://cloud.githubusercontent.com/assets/18025235/21752985/38fdd798-d5eb-11e6-8ed5-e43fb15b0fe0.png)
### Errors without https url

**Comment by mikeyny** [comment]
Codewars Output just remains blank tho

**Comment by jhoffner** [comment]
Looks like the sandbox allow-same-origin feature isn't working for you for some reason. I've updated preview to use a different domain. Lets try it there and see if that fixes your issues. https://preview.codewars.com/

**Comment by mikeyny** [comment]
@jhoffner The preview works just fine ,thanks

**Comment by Ohshi60** [comment]
hi i just had this exact problem, and the preview.codewars.com worked for me as well
