### ISSUE TITLE
[C#] Warnings when using async

### ISSUE THREAD

**Issue by ghost** [Codewars/codewars-runner-cli#300]
Hi, I'm trying to create a Kata which implements async (and System.Threading.Tasks), but when I run it I get these warnings: 

> warning CS1685: The predefined type `System.Runtime.CompilerServices.INotifyCompletion' is defined multiple times. Using definition from `mscorlib.dll'
/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
/runner/frameworks/csharp/nunit/System.Threading.Tasks.dll (Location of the symbol related to previous warning)
warning CS1685: The predefined type `System.Runtime.CompilerServices.IAsyncStateMachine' is defined multiple times. Using definition from `mscorlib.dll'
/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
/runner/frameworks/csharp/nunit/System.Threading.Tasks.dll (Location of the symbol related to previous warning)
warning CS1685: The predefined type `System.Runtime.CompilerServices.AsyncTaskMethodBuilder' is defined multiple times. Using definition from `mscorlib.dll'
/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
/runner/frameworks/csharp/nunit/System.Threading.Tasks.dll (Location of the symbol related to previous warning)
warning CS1685: The predefined type `System.Runtime.CompilerServices.ICriticalNotifyCompletion' is defined multiple times. Using definition from `mscorlib.dll'
/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
/runner/frameworks/csharp/nunit/System.Threading.Tasks.dll (Location of the symbol related to previous warning)
warning CS1685: The predefined type `System.Runtime.CompilerServices.AsyncVoidMethodBuilder' is defined multiple times. Using definition from `mscorlib.dll'
/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
/runner/frameworks/csharp/nunit/System.Threading.Tasks.dll (Location of the symbol related to previous warning)

**Comment by kazk** [comment]
Closing because it's old and the reporter deleted GitHub account. This might be resolved in C# 7.3.
