### ISSUE TITLE
[C/C++] Separate tests and solution during compilation

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars-runner-cli#301]
While it's probably too late, solution and test code should be in two separate object files and then linked together. Otherwise it's sometimes possible to simply use `solution`, e.g.

``` cpp
int solution(std::vector<ArcaneType> values);
int myVeryComplexFunction(std::vector<ArcaneType> values){
 return solution(values);
}
...
...
/* Test framework code, including solution */
```

This wouldn't be possible if `solution` was in another object file with static linkage.

**Comment by error256** [comment]
Compile-time code like templates can't be tested that way. Also, that would require creating headers with declarations for solution functions/classes.
As for hiding the solution, you can write it in a lambda.

**Comment by bkaestner** [comment]
>  As for hiding the solution, you can write it in a lambda.

That works. However, it still doesn't hide the source code, which is another problem (that affects all language on Codewars).
