### ISSUE TITLE
Python 2 str.translate() issue

### ISSUE THREAD

**Issue by anter69** [Codewars/codewars-runner-cli#311]
According to the official documentation of [str.translate()](https://docs.python.org/2/library/stdtypes.html#str.translate), in python 2.6+ you can
> ... set the _table_ argument to `None` for translations that only delete characters:
> ```
> >>> 'read this short text'.translate(None, 'aeiou')
> 'rd ths shrt txt'
> ```

However, doing this in CW gives an error:
`TypeError: translate() takes exactly one argument (2 given)`

Note that this feature is not supported in python 3 anymore, there you get the above error message.

**Comment by kazk** [comment]
Closing this because this works fine with Python 2.7.6 selected.

![image](https://user-images.githubusercontent.com/639336/29246361-5427ab5a-7fac-11e7-910f-c6b557e58645.png)

![image](https://user-images.githubusercontent.com/639336/29246359-48d52a3e-7fac-11e7-86ce-c44900075cf1.png)
