### ISSUE TITLE
Enhace Crystal-lang test framework

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#312]
While translating I got

> 23908490234823904835.should eq 23908490234823904835
> Syntax error in ./fixture.cr:24: 23908490234823904833 doesn't fit in an UInt64

that means that `should eq` has a definition for `UInt64` but not for `BigInt`

You can check this issue on [this Kumite](https://www.codewars.com/kumite/589d1a48dfdef02bbf00001b/edit).

**Comment by error256** [comment]
https://crystal-lang.org/api/0.19.4/Int.html
> If no suffix is present, the literal's type is the lowest between Int32, Int64 and UInt64 in which the number fits

I don't think there're BigInt literals.
(There's still an issue with BigInts on Codewars (/usr/bin/ld: cannot find -lgmp).)

**Comment by javatlacati** [comment]
Nope, there are [BigInt Objects](https://crystal-lang.org/api/0.19.4/BigInt.html)

````
puts BigInt.new("123456789101101987654321").to_s # => 123456789101101987654321
````

**Comment by error256** [comment]
There are BigInt objects but there're no BigInt literals, just the same as in Java.

**Comment by javatlacati** [comment]
Hence testing framework should accept BigInt too

**Comment by jhoffner** [comment]
We don't manage this framework, its part of the language framework itself.

**Comment by javatlacati** [comment]
So it's a bug from the testing framework? 😨
