### ISSUE TITLE
Typescript is broken?

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#316]
Please check [my Kata](https://www.codewars.com/kumite/58af1666a54f595b20000123/edit) I can get sometimes the following error

>  ../home/codewarrior/spec.ts(3,27): error TS2306: File '/home/codewarrior/solution.ts' is not a module.
> STDERR:
> Error: Command failed: tsc --module commonjs /home/codewarrior/spec.ts

but most of the times It runs without perform the actual test functionality, no results just output.

**Comment by jhoffner** [comment]
Looks like its stable now

**Comment by javatlacati** [comment]
Now I get

> ../home/codewarrior/spec.ts(1,1): error TS1084: Invalid 'reference' directive syntax.
>../home/codewarrior/spec.ts(2,1): error TS1084: Invalid 'reference' directive syntax.
>STDERR:
>Error: Command failed: tsc --module commonjs /home/codewarrior/spec.ts
