### ISSUE TITLE
Crystal lang can't compile on fixture

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#322]
To create this Kata: https://www.codewars.com/kumite/58c1e71fc7df54394300011c?sel=58c1e71fc7df54394300011c

I had to put the solution in preloaded code if I add the code into fixture it will complain

> can't declare def dynamically

**Comment by jhoffner** [comment]
This is likely a Crystal issue, we don't do anything special to cause this from what I can tell.
