### ISSUE TITLE
Timeouts for compiled languages

### ISSUE THREAD

**Issue by kazk** [Codewars/codewars-runner-cli#333]
@jhoffner I noticed that you've [increased timeouts](https://github.com/Codewars/codewars-runner-cli/commit/d5bde1ad0c8059ecf61f8b7993f49a26eedbcf63) for Haskell and Go.

Go compiles pretty fast, but I realized that some compiled languages are given compile time in addition to the default timeout.
Should I change Go runner to this way? I think this can be done by `go test -c` to build, then executing `./solution.test`.
If this is preferred, I'll also change work-in-progress Nim and D.

Also, isn't default `12000ms` timeout too much for those compiled separately? Most C kata reports the time under `500ms`.

**Comment by jhoffner** [comment]
Yeah we could increase them at the compile stage. The Go, Haskell and to a lesser degree Swift seem to timeout a lot. I'm really not sure why but really the timeouts had been increased overall on all languages to try to limit issues with noisy servers just responding slowly.

**Comment by kazk** [comment]
> The Go, Haskell and to a lesser degree Swift seem to timeout a lot.

Did this happen when you're building the image? I've already made a version of Go runner that compiles separately, but I don't think it helps with that. Maybe I'm misunderstanding the issue.

---

> I'm really not sure why but really the timeouts had been increased overall on all languages to try to limit issues with noisy servers just responding slowly.

Isn't `timeout` in `lib/config.js` used to specify `maxTime` in `runCode`?

[lib/shovel.js#L199](https://github.com/Codewars/codewars-runner-cli/blob/8a843124d34c592a72733d567f76e9511bfdd354/lib/shovel.js#L199)
```js
maxTime = opts.timeout || config.timeouts[opts.language] || config.timeouts.default;
```

I was concerned that Go is given `1500ms` to compile and run:

[lib/runners/go.js#L34-L45](https://github.com/Codewars/codewars-runner-cli/blob/8a843124d34c592a72733d567f76e9511bfdd354/lib/runners/go.js#L34-L45)
```js
runCode({ // compile AND run. maxTime is 1500ms now
  name: 'go',
  args: ['test'],
  options: {
    cwd: dir,
    env: Object.assign({}, process.env, {
      // append the directory to $GOPATH so the test can
      // use the import path "codewarrior/pakage" for arbitrary package name
      GOPATH: `${process.env.GOPATH}:/home/codewarrior/go`
    })
  }
});
```

while C is given `1200ms` to run *after* it's compiled:

[lib/runners/c.js#L31-L35](https://github.com/Codewars/codewars-runner-cli/blob/8a843124d34c592a72733d567f76e9511bfdd354/lib/runners/c.js#L31-L35)
```js
exec(args.join(' '), function (error, stdout, stderr) { // compile
    if (error) return fail(error, stdout, stderr);
    opts.publish('stdout', stdout);
    runCode({'name': executable, 'args': ['-q','-j1']}); // run maxTime 1200ms
});
```

**Comment by kazk** [comment]
Also, we might need to look into this:

[lib/shovel.js#L289-L293](https://github.com/Codewars/codewars-runner-cli/blob/8a843124d34c592a72733d567f76e9511bfdd354/lib/shovel.js#L289-L293)

```js
// Get the time left in a set timeout
// http://stackoverflow.com/questions/3144711/find-the-time-left-in-a-settimeout
function getTimeLeft(timeout) {
    return Math.ceil((timeout._idleStart + timeout._idleTimeout - Date.now()) / 1000);
}
```

I think you got it from [this answer](http://stackoverflow.com/a/10786331). There's a comment (2016-07-15) "not work on node 6.3, because the timeout structure is leak of those information.".

**Comment by jhoffner** [comment]
> Did this happen when you're building the image? I've already made a version of Go runner that compiles separately, but I don't think it helps with that. Maybe I'm misunderstanding the issue.

No I just mean that when using Codewars with these languages, it seems like up to 50% of the time you can get timeouts. Seems to be worse/better at different times throughout the day. 

> I was concerned that Go is given 1500ms to compile and run

Is there a way to do them as separate steps? Would be good to know though not sure if its necessary. 

> getTimeLeft(timeout)

I'm glad you pointed this code out. This was added a long time ago and I think it needs to be evaluated if this is even really necessary, and if it is if we can cut down the amount of time that is waited so that we don't go all the way to the max. Its possible that this is running and causing the timeouts (though we should be seeing buffered output via the CW Red buffer feature).

**Comment by jhoffner** [comment]
I also wonder if these timeouts are randomly happening on these languages because for some reason the STDOUT buffer is not being flushed properly.

**Comment by kazk** [comment]
> No I just mean that when using Codewars with these languages, it seems like up to 50% of the time you can get timeouts.

I don't think I had this problem with Go (did `53` so far). I remember Haskell timeout randomly and not sure about Swift :/

> Seems to be worse/better at different times throughout the day.

Does this correlate with number of users?

---

> Is there a way to do them as separate steps? Would be good to know though not sure if its necessary.

```js
exec('go test -c', {
  cwd: dir,
  env: Object.assign({}, process.env, {
    // append the directory to $GOPATH so the test can
    // use the import path "codewarrior/pakage" for arbitrary package name
    GOPATH: `${process.env.GOPATH}:/home/codewarrior/go`
  })
}, function(err, stdout, stderr) {
  runCode({
    name: `./${pkgName}.test`,
    args: [],
    options: {
      cwd: dir,
    }
  });
});
```

I couldn't tell the difference when building because test programs are tiny. I `diff`ed the outputs against the current one and the difference was inconsistent and small. Go compiles quickly and 1.8 made it even faster, so I don't know if this is necessary either. If the timeout becomes a problem, we can try this.

---

I'll start looking into `shovel.js` including buffers. I need to refresh my knowledge about Node's [event loops and timers](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/) first.

---

Little off topic, but I'm against using `Date` to measure elapsed time (e.g., `buffer.walTime`). On Node, I'd use `process.hrtime([time])`.

**Comment by jhoffner** [comment]
> Does this correlate with number of users?

Not sure if its users on our system or users on neighbor systems running on the same underlying AWS hardware. 

> I'm against using Date to measure elapsed time

We could return a hrTIme value as well, if we can figure out how to accurately utilize it (we aren't really running anything in the node process so process.hrtime doesn't seem like it will be accurate?). wallTime usually means the time on the wall (wall clock) so using date I think is standard here. 

I would also love to return memory usage, but again we need to monitor the cpu time/memory of the child process, not the current process.

**Comment by kazk** [comment]
Isn' t `wallTime` basically this?

```js
const cp = require('child_process');
const start = process.hrtime();
cp.exec('sleep 1', function(err) {
  const [s, ns] = process.hrtime(start); // wall time [seconds, nanoseconds]
  console.log(`${s + ns/1e9}s`);      // 1.022519277s
  console.log(`${s*1e3 + ns/1e6}ms`); // 1022.519277ms
});
```

**Comment by jhoffner** [comment]
Yeah I think your right. I read the documentation too quickly and was thinking that it was based off of amount of actual CPU time spent within the process.

**Comment by kazk** [comment]
> I also wonder if these timeouts are randomly happening on these languages because for some reason the STDOUT buffer is not being flushed properly.

Is it this part?

[lib/shovel.js#L273-L284](https://github.com/Codewars/codewars-runner-cli/blob/8a843124d34c592a72733d567f76e9511bfdd354/lib/shovel.js#L273-L284)
```js
    child.on('exit', function (code, signal) {
        // wait the remaining time left to see if all stdio processes close
        // preferably we cleanup after 'exit' is called
        setTimeout(function() {
            complete(code, signal);
        }, getTimeLeft(timeout));
    });

    child.on('close', function (code, signal) {
        clearTimeout(timeout);
        complete(code, signal);
    });
```

Why do we have both `'exit'` and `'close'` handlers calling `complete(code, signal)`? If I'm not misunderstanding `'close'` is emitted after `'exit'` once `child`'s `stdio` is closed. 
Can't we do this?

```js
child.on('exit', function(code, signal) {
  // handle irregular termination
  if (signal !== null) { // process terminated
  }
  // handle unexpected exit code
});
child.on('close', function(code, signal) {
  clearTimeout(timeout);
  complete(code, signal);
});
```

**Comment by jhoffner** [comment]
Closing since these adjustments seem to have improved things.
