### ISSUE TITLE
ESLint 'brace-style'

### ISSUE THREAD

**Issue by kazk** [Codewars/codewars-runner-cli#342]
I forgot to fix the indentation of comments and I started to work on this.
When I opened [frameworks/javascript/cw-2.js](https://github.com/Codewars/codewars-runner-cli/blob/321c62e176e4b0e031e355ffc973a5e23c6d6b18/frameworks/javascript/cw-2.js), I found that it looks terrible because of inconsistent braces.
This can be fixed using `eslint --fix` with [brace-style](http://eslint.org/docs/rules/brace-style) rule, but which rule should we use?

The most common style is ["1tbs"](http://eslint.org/docs/rules/brace-style#1tbs):

```js
if (foo) {
  bar();
} else {
  baz();
}
```

@jhoffner [prefers](https://github.com/Codewars/codewars-runner-cli/pull/323#discussion_r105473359) `else` on its own line and there's a rule for that called ["stroustrup"](http://eslint.org/docs/rules/brace-style#stroustrup):

```js
if (foo) {
  bar();
}
else {
  baz();
}
```

Another one is called ["allman"](http://eslint.org/docs/rules/brace-style#allman):

```js
if (foo)
{
  bar();
}
else
{
  baz();
}
```

I think this should be decided by Codewars team to avoid holy war.
@jhoffner, @OverZealous, @Dan-Nolan, @nathandoctor

---

(I should have asked this within "Start using ESLint #338" before merge :()

**Comment by jhoffner** [comment]
In the team I primarily maintain this code base so I'll speak up and say stroustrup. It's also what is used for the Coderunner UI. The reason I prefer that style is that it makes a more smooth transition between ruby, which is our main backend language.

**Comment by kazk** [comment]
Ok, I'll start working on this soon.
