### ISSUE TITLE
Can't import numpy in Python 3.6.0

### ISSUE THREAD

**Issue by error256** [Codewars/codewars-runner-cli#367]
https://www.codewars.com/kumite/58e4b96a823ffd23db00007c?sel=58e4b96a823ffd23db00007c

```python
import numpy
```

```
Traceback:
   in 
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 153, in 
    from . import add_newdocs
  File "/usr/lib/python3/dist-packages/numpy/add_newdocs.py", line 13, in 
    from numpy.lib import add_newdoc
  File "/usr/lib/python3/dist-packages/numpy/lib/__init__.py", line 8, in 
    from .type_check import *
  File "/usr/lib/python3/dist-packages/numpy/lib/type_check.py", line 11, in 
    import numpy.core.numeric as _nx
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 6, in 
    from . import multiarray
ImportError: cannot import name 'multiarray'
```

**Comment by kazk** [comment]
`numpy` is installed with:

```dockerfile
# Install Python3 libraries
RUN apt-get install -y python3-numpy python3-scipy python3-pandas
```

`numpy` is [1.8.1 (2014-03-25)](https://pypi.python.org/pypi/numpy/1.8.1) according to <http://packages.ubuntu.com/trusty/python3-numpy>.

---

Maybe creating isolated environments for each Python version using `virtualenv` will work for now.
Ideally, we should have independent images, `codewars/python-runner:{python-version}`, as I proposed before, but it's not easy to transition.

**Comment by kazk** [comment]
Fixed in https://github.com/Codewars/codewars.com/issues/1336

**Comment by kazk** [comment]
@begueradj 

> not fixed in the link you shared

Do you mean https://www.codewars.com/kumite/58e4b96a823ffd23db00007c?sel=58e4b96a823ffd23db00007c ? That's just showing the output when that was created. You shouldn't see the error if you run it after forking.
