### ISSUE TITLE
High Priority: A bug in the PHP TestCases that set all TestCases as correct

### ISSUE THREAD

**Issue by osofem** [Codewars/codewars-runner-cli#372]
Just discovered a bug in the PHP testcase that let any code pass once it extend the TestCase class. For example this kata (https://www.codewars.com/kata/55911ef14065454c75000062) as TestCases like

<code>class MultiplyStringsTest extends TestCase { public function testBigExamples() { $this->assertEquals("5619135910", multiply("98765", "56894")); $this->assertEquals("2830869077153280552556547081187254342445169156730", multiply("1020303004875647366210", "2774537626200857473632627613")); $this->assertEquals("444625839871840560024489175424316205566214109298", multiply("58608473622772837728372827", "7586374672263726736374")); $this->assertEquals("81129638414606663681390495662081", multiply("9007199254740991", "9007199254740991")); } }</code>
All I have to put in my solution to pass this kata is
<code>class Multiply extends TestCase { function multiply(string $a, string $b) { echo "whatever"; } }</code>

I confirmed with two other random PHP katas, all I have to do to pass the kata is to extend the Testcase in my solution and my solution is marked as correct.

**Comment by kazk** [comment]
Same as the second method in #307.
