### ISSUE TITLE
TypeScript: Update Typings

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#380]
While creating a [translation in Typescript](https://www.codewars.com/kumite/58f7ef7c7a5c280cd1000023/edit) I've got

> ../home/codewarrior/solution.ts(11,75): error TS2339: Property 'from' does not exist on type 'ArrayConstructor'.

but you can run the solution without problems from Typescript playground, so I suppose that your es6 typings are outdated or you are forcing output to an old version od ecmascript.

**Comment by kazk** [comment]
This is actually `target` issue and should be resolved with #476 (using `languageVersion` `2.4/ES6`).

**Comment by javatlacati** [comment]
That-s a gerat new but still it doesn't work on preview I still got

> ../home/codewarrior/solution.ts(9,35): error TS2339: Property 'from' does not exist on type 'ArrayConstructor'.

can you reopen the issue???

**Comment by kazk** [comment]
I don't think it's deployed yet.

**Comment by kazk** [comment]
preview.codewars.com still shows `1.8.10`
![image](https://user-images.githubusercontent.com/639336/28997501-138503b8-79cb-11e7-904f-0d0b19568f9b.png)

when deployed, it should show versions like `2.4/ES3` and `2.4/ES6`.
