### ISSUE TITLE
Java Console support

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars-runner-cli#382]
It looks like the Java console is just a log viewer of all STDOUT/STDERR output. I’m assuming we might need to redirect the default logger to STDOUT. Thats going to be a ton of noise though, so we may need to add a way to tag each line of these logger messages with a new data token so that we can display them separately later.

This may be possible now even using JVM-runner

**Comment by javatlacati** [comment]
What do you mean by `Java console`? Read and write data from standard input/output?

**Comment by jhoffner** [comment]
I meant [this](https://www.java.com/en/download/help/javaconsole.xml) but I think this can be closed now with the new #447 PR.
