### ISSUE TITLE
Rest API wrapper for the cli

### ISSUE THREAD

**Issue by mohamedrez** [codewars/codewars-runner-cli#384]
Is there an already rest api wrapper built for this cli

**Comment by jhoffner** [comment]
There is not. At least not open source. We have a server that manages resources and is more complicated than a basic wrapper would need to be. 

It would definitely benefit the project to have a very simple server to run the CLI. The tricky parts are that you need to manage docker containers and lifecycles, so building a simple wrapper that utilizes docker correctly is easier said than done.

**Comment by jhoffner** [comment]
I think the easiest (but non-production quality at the scale that CW has to handle) solution to creating a wrapper would be to make docker calls directly using https://github.com/shelljs/shelljs. That should be pretty straightforward.

**Comment by kazk** [comment]
Closing because this project is no longer actively developed.
