### ISSUE TITLE
[RFC] Paradigm Shift v2

### ISSUE THREAD

**Issue by kazk** [Codewars/codewars-runner-cli#396]
(Moved from a comment in #318)

## Abstract

A new paradigm to improve maintainability with extensibility.
Takes advantage of NPM and improves flexibility by packaging components.

## Background

> There is currently no way of handling language/package versioning well.

Previous proposal (#318) was fun to discuss, but wasn't realistic.

## Proposal

Modularize the codebase into smaller packages.
Avoid the pain of maintaining multiple repositories by using [Lerna](https://lernajs.io/) :dragon:.
This allows much more flexibility while keeping the convenience of having the code in one place.

### Backward Compatibility

Allows progressive enhancements.
Each language can update when it's ready.

Image tags can be used in conjunction to keep track of compatibilities.

### Contribution Barrier

Decentralized design and flexibility presented in this proposal will lower the barrier of contribution.

### Build Context

This structure allows having `Dockerfile` instead of `.docker`.
Each image can have `.dockerignore` to keep build contexts small.

### package.json

`package.json` has become unmanageable mixing `dependencies` with `devDependencies`.

## Implementation

Create `@codewars` org on `npmjs.com` (free for public packages) and restructure the codebase to something similar to:

```
# repository: codewars/codewars-runners
- packages
  - codewars-runner
    - package.json
      - `name: @codewars/runner`
      - `version: "1.0.0"`
- runners
  - codewars-node-runner
    - Dockerfile
    - package.json
      - `name: @codewars/node-runner`
      - `version: "1.0.0"`
      - `dependencies:`
        - `@codewars/runner: "^1.0.0"`
  - codewars-ruby-runner
    - Dockerfile
    - package.json
      - `name: @codewars/ruby-runner`
      - `version: "1.0.0"`
      - `dependencies:`
        - `@codewars/runner: "^1.0.0"`
- lerna.json
- package.json
```

When a breaking change is introduced, increment the major version and update runners progressively. For example, `@codewars/runner` and `@codewars/ruby-runner` becomes `2.0.0`, but `@codewars/node-runner` can stay `1.0.0`.

Can be modularized further like:

```
- packages
  - codewars-runner
    - package.json
      - `name: @codewars/runner`
      - `version: "1.0.0"`
      - `dependencies:`
        - `@codewars/runner-util: "^1.2.1"`
        - `@codewars/runner-service-manager: "^1.0.0"`
  - codewars-runner-util
  - codewars-runner-service-manager
- runners
  - codewars-node-runner
  - codewars-ruby-runner
  - codewars-python-runner
  - codewars-go-runner
- lerna.json
- package.json
```

and improve the codebase  in smaller steps.

---

@jhoffner Here's my new proposal. I actually like this one over the original.
Please let me know what you think.

**Comment by jhoffner** [comment]
Thanks @kazk. I never knew about Lerna, that's definitely going to come in handy!

The proposal is very interesting.

> Allows progressive enhancements.

OK this one I think I see where you are going. You are saying that when we update one runner we can bump the version without having to bump the versions of every runner. Currently when any change to the repo happens our CI system has to build all images. The way you are suggestion means we could tag/bump the image version on a per runner basis, resulting in less images to build/manage on specific changes. Each runner would maintain its own version number.  

I like this a lot. The lazy/overworked part of me is dreading having to update the CI system and go into devops mode to support the additional changes that would be needed to fully support this, but I like where you are going :) 

> this proposal will lower the barrier of contribution.

This is the part that it's not clear to me. What exactly would this make easier? I may be too familiar with the codebase to realize this off the bat.

**Comment by kazk** [comment]
I've already got used to the codebase, but it's definitely not easy. I'll try to explain what I mean.

---

First of all

```
.
|-- docker/
|-- documentation/
|-- examples/
|-- frameworks/
|-- jvm-runner/
|-- lib/
|-- sample_data/
|-- test/
|-- typings/
|-- LICENSE
|-- Makefile
|-- README.md
|-- docker-compose.yml
|-- listen.js
|-- package.json
|-- run-json.js
|-- run.js
|-- test_cs.sh
|-- tsconfig.json
`-- typings.json
```

becomes

```
.
|-- packages/
|   |-- codewars-runner/
|   |-- codewars-runner-options/
|   |-- codewars-runner-services/
|   |-- codewars-runner-util/
|   `-- README.md
|-- runners/
|   |-- codewars-node-runner/
|   |-- codewars-python-runner/
|   |-- codewars-ruby-runner/
|   `-- README.md
|-- README.md
|-- lerna.json
`-- package.json
```

where most contributors can just treat `packages/` as black box.

If a contributor wants to improve `ruby`, then s/he will go to `codewars-ruby-runner` where all the requirements are contained in.

If a contributor wants to add a language, then s/he will implement the requirements of `runner` reading the documentation and using the well supported `runner` as a reference.

---

Currently, it's hard to *see* what is required to implement a `runner`. Improving the documentation will help, but structuring the project this way makes things more obvious.

```
runners/codewars-node-runner
|-- frameworks/
|   `-- cw-2.js
|-- lib/
|   |-- frameworks/
|   |   |-- with-cw-2.js
|   |   `-- with-mocha.js
|   |-- index.js
|   |-- solution-only.js
|   `-- test-integration.js
|-- test/
|   |-- fixtures/
|   |   `-- mocha-examples.yml
|   |-- solution-only.js
|   |-- test-integration-with-cw-2.js
|   `-- test-integration-with-mocha.js
|-- .dockerignore
|-- Dockerfile
`-- package.json
```

Also a `runner` is free to organize the code in the way it makes sense in it without worrying about other `runners`.

**Comment by jhoffner** [comment]
@kazk Thanks for the explanation. Makes sense to me! I could also see us adding a generator for when someone needs to build out a new language.

**Comment by kazk** [comment]
> The lazy/overworked part of me is dreading having to update the CI system and go into devops mode to support the additional changes that would be needed to fully support this

What are you using?
I think Docker Cloud has autobuild/autotest based on repository tag patterns and build contexts can be specified. So Lerna can tag the repository `codewars-go-runner@1.0.0` and the build rule for `codewars-go-runner` is triggered. I haven't confirmed this though.

---

I made a sample of multi-package approach:

- [kazk/codewars-runner](https://github.com/kazk/codewars-runner)
- [kazk/codewars-go-runner](https://github.com/kazk/codewars-go-runner)

Note:
- `npm run make` does what `make LANG` currently does
- `cw/go-runner run` is not implemented, but should be easy to
- Not using Lerna because I didn't want to publish them

**Comment by kazk** [comment]
Some random thoughts.

---

Eventually, `runner` and `Dockerfile` should be decoupled.
If we can keep each `runner` minimum, flexible and `npm` installable we can do something like this later:

```shell
docker run existing-image {install codewars stuff}
docker commit $(docker ps -lq) custom-image # docker ps -lq; gets id of last
```

---

I'm still unsure how things are done on server, but the experimental [`docker checkpoint`](https://criu.org/Docker) might become useful once it matures. This allows restoring from pre-warmed checkpoint if I'm not misunderstanding.

**Comment by jhoffner** [comment]
> Eventually, runner and Dockerfile should be decoupled.

I was having the same thoughts. Installing node and the cli shouldn't be that much of an effort, and without having to use a base image we could just start using official images and save ourselves a lot of maintenance issues. I like the idea of using commits. I used to do something like that for the Qualified dev build scripts and it worked pretty well. 

> docker checkpoint

I didn't know about this. This could be very interesting to utilize.

**Comment by kazk** [comment]
> Installing node and the cli shouldn't be that much of an effort

@jhoffner Have you seen [zeit/pkg](https://github.com/zeit/pkg)?

> "This command line interface enables you to package your Node.js project into an executable that can be run even on devices without Node.js installed."

We can't utilize this right now because of the code like the following.

```javascript
const customStrategy = require(opts.dir + '/.runner/run.js');
```

But if we can somehow refactor to eliminate those dynamic `require` then we can just copy the executable.

**Comment by jhoffner** [comment]
Whoa, I didn't know about `pkg` that could come in handy. I've been wanting to create a solver cli tool for CW/Qualified that allows you to write code within your own editor, this would make that much easier to install!

customStrategy can be taken out. The idea behind it is that when working with the new multi-file project format, you can also specify a customer runner. This could be useful for developing out new runners or for customizing the way one works for a specific challenge. It was an experiment. 

BTW you can see the prototype of the multi-file interface here. runner.codewars.com/studio. The only languages that are setup with starter templates right now are JS and Ruby, everything else defaults to classic (CW compatible) mode where you can't add files. Also this thing is not by any means finished so its going to have issues.

**Comment by jhoffner** [comment]
Forgot to add: To see the customStrategy in action, open the code studio link and go to the view menu and click advanced. Then open the .runner/run.js file.

**Comment by kazk** [comment]
Thanks, Looks nice! I'll take a look at them.
Have you seen my questions in #142?

**Comment by kazk** [comment]
@jhoffner I played with the new UI and it's amazing!

I think Codewars' strength is how we can solve problems more naturally.
I like code challenges so I also have accounts from many others. But I don't know anywhere else that allows one to write tests. Most of them requires to parse the input from stdin and output the result to stdout. I think CodeFights is closest (no stdin/stdout), but their tests are only simple input and output pairs if I remember correctly.

I'm super excited about the multi-file support. I guess I didn't realize how much value it has until I actually saw this.

**Comment by jhoffner** [comment]
Awesome, glad you like it! 

Yeah it opens up so many more possibilities. I also want to support client side specific files so that you can customize how a challenge renders (opening up custom game challenges like other sites have). 

> I think Codewars' strength is how we can solve problems more naturally.

We took the hard path to support our style of using actual tests, but I agree, I think it paid off. STDIN/OUT based challenges rub me the wrong way pretty badly.

**Comment by kazk** [comment]
(continuing from #142 because this issue seems more relevant)

@jhoffner thanks for explaining. I know you're already on vacation, but I'll post some comments to organize my thoughts and to keep the record.

> It's a fleet of servers with each server running one instance of each runner.
>
> So effectively each server can only handle one job at a time, which is why we run many cheap servers. 

I think something like the following is what you mean.

```
- executing (docker exec)
o ready (keep-alive; TCP server)
x killed
                            [ queue ]
                                |
      +------------+------------+------------+------------+
      |            |            |            |            |
      v            v            v            v            v
+---[S1]---+ +---[S2]---+ +---[S3]---+ +---[S4]---+ +---[S5]---+
| - ruby   | | - ruby   | | o ruby   | | o ruby   | | o ruby   |  x5 t2.micro
| o node   | | o node   | | - node   | | - node   | | o node   |
| o python | | o python | | o python | | o python | | - python |
| ...      | | ...      | | ...      | | ...      | | ...      |
| ...      | | ...      | | ...      | | ...      | | ...      |
+----------+ +----------+ +----------+ +----------+ +----------+

+---[S1]---+
| x ruby   | killed after responding
| o node   |
| o python |
| ...      |
+----------+

+---[S1]---+
| o ruby   |
| - node   | pulls the job once runner restarts
| o python |
| ...      |
+----------+
```

If I'm not misunderstanding, this looks really hard to maintain and/or extend :(

---

I started to experiment and found `docker swarm` to be relatively easy to use.

```
- executing (triggered by POST)
o ready (http server)
x exited

+---[S1]---+ +---[S2]---+ +---[S3]---+
| - ruby   | | - node   | | - python |
| - ruby   | | - node   | | o python |
| o ruby   | | o node   | | x python |
| o ruby   | | x node   | |          |
| x ruby   | |          | |          |
+----------+ +----------+ +----------+

* each runner is a service (`docker service`) and replicated as needed
* each runner can have reserved resources
* exited services are automatically restarted
* can update images without stopping
* scalable
* flexible. services are independent
```

I made a simple node-runner service as a HTTP server that accepts one request and closes after responding. Load balancing and restarting are handled internally by Docker. I still need to understand what's going on, but it's much more flexible and easy. It might be also more cost-effective depending on the configuration. I'll continue with my experiments and let you know if I find it useful for our needs.

**Comment by kazk** [comment]
Closing this because we've been working on a new project based on different idea that's more flexible.
