### ISSUE TITLE
Fixing the LF issue

### ISSUE THREAD

**Issue by kazk** [Codewars/codewars-runner-cli#410]
Fixing the issue where users' output affects the test result.

```
user logged output<FAILED::>
```

- [x] Dart
  - `Server Execution Error`, see the [comment below](https://github.com/Codewars/codewars-runner-cli/issues/410#issuecomment-299260220)
- [x] C# (#411, #572)
- [x] JavaScript (#502)
- [x] TypeScript (#502)
- [x] OCaml (#468)
- [x] Swift (#451)
- [x] PHP (#421)
- [x] F# (#419)
- [x] Elixir (#417)
- [x] Crystal (#416)
- [x] Ruby (#414)
- [x] C++ (#413)
- [x] Python (#412)
- [x] Lua (#409)
- [x] Java (#336)
- [x] Go (#339)
- [x] C ([@25e5609](https://github.com/Codewars/codewars-runner-cli/commit/25e560940a9cdc249d00e6d732c2a54e0a7014d5))

---

- [x] Rust ([lib/runners/rust.js](https://github.com/kazk/codewars-runner-cli/blob/815480438a336443327e850a2c9e51eaae8e4989/lib/runners/rust.js)) outputs the result differently from the most and not really affected.
  - `stdout` is transformed after the test and only contains the output commands
    ```
    <DESCRIBE::>returns_expected
    <FAILED::>Test Failed
    ```
  - `stderr` contains the details on failure (`print!("foo"); assert_eq!(1, 2);`)
    ```
    Failure Info:
    
    ---- returns_expected stdout ----
    	foothread 'returns_expected' panicked at 'assertion failed: `(left == right)` (left: `1`, right: `2`)', main.rs:17
    ```

---

Codewars/codewars.com#867
Codewars/codewars.com#937

**Comment by kazk** [comment]
C# example from @Voileexperiments's comment

```csharp
using System;
using NUnit.Framework;

[TestFixture]
public class KataTestClass
{
    [Test]
    public void Test()
    {
        Console.Write("foobar");
        Assert.AreEqual(true, false);
    }
}
```

Outputs

```
foobar<FAILED::>  Expected: True
  But was:  False
```

![image](https://cloud.githubusercontent.com/assets/14909989/25662584/a00a9140-3047-11e7-8aa1-16a089f15c56.png)

**Comment by Voileexperiments** [comment]
JS example:
```
Test.expect(true);
process.stdout.write('foobar');
Test.expect(false);
process.stdout.write('foobar\n');
Test.expect(false);
process.stdout.write('foobar');
Test.expect(false);
```
![](https://cloud.githubusercontent.com/assets/14909989/25662950/ee236f86-3048-11e7-959e-3e0ee8c79764.png)

Python example:
```python
#Python 2
import sys

test.expect(True)
sys.stdout.write('foo')
test.expect(False;
sys.stdout.write('bar')
test.expect(True)

#Python 3
test.expect(True)
print('foo', end='')
test.expect(False)
print('bar', end='')
test.expect(True)
```
![image](https://cloud.githubusercontent.com/assets/14909989/25688399/59c436a4-30b1-11e7-81d2-b1c86656e287.png)

**Comment by Voileexperiments** [comment]
Throwing out some ideas:

Is it possible for the runner to detect current stdout? If so, it can then just check if the last character is a line feed, and if not, send one to stdout first.

Or alternatively, send a extra linefeed before the test messages no matter what. This will increases the character count by a bit and doubles the number of lines, but it might totally avert the issue?

**Comment by kazk** [comment]
Extra line feed will be added (like in Codewars/codewars-runner-cli@bb41dbb88d7fd668b65be37ef813bb5d7435fb9a).
See @jhoffner's [comment](https://github.com/Codewars/codewars.com/issues/867#issuecomment-288503427) in Codewars/codewars.com#867.

**Comment by kazk** [comment]
Causes server execution error in Dart :(

![image](https://cloud.githubusercontent.com/assets/639336/25717447/58b15188-30b7-11e7-91b2-bb7ae9e30b22.png)

**Comment by kazk** [comment]
@jhoffner can we move [Codewars/mocha-reporter](https://github.com/Codewars/mocha-reporter) in this repository by updating Mocha?
[Mocha v3.3.0](https://github.com/mochajs/mocha/releases/tag/v3.3.0) "Adds support for loading reporter from an absolute or relative path" and supports `node >= 0.10.x`.

**Comment by jhoffner** [comment]
Sure let's do it.

**Comment by kazk** [comment]
I found that JavaScript has been tested with `mocha` installed in base-image at [docker/base.docker#L107](https://github.com/Codewars/codewars-runner-cli/blob/05b31129d1a27e656224f51c9ffc8fe24a504234/docker/base.docker#L107) and not `"mocha": "2.5.3"` in [package.json#L55](https://github.com/Codewars/codewars-runner-cli/blob/05b31129d1a27e656224f51c9ffc8fe24a504234/package.json#L55).
I think the version has been `3.2.0` for while...
