### ISSUE TITLE
Multiple source file support 

### ISSUE THREAD

**Issue by mohamedrez** [Codewars/codewars-runner-cli#427]
Does the current cli runner supports multiple source files on submission ?

**Comment by kazk** [comment]
For CLI runner, I think Node,Ruby,Python,C#,Shell,SQL has support if I remember correctly.

It's not supported on Codewars yet. The new UI adding this feature is work in progress.

**Comment by mohamedrez** [comment]
what about Java ?

**Comment by kazk** [comment]
I don't think Java has multi-file support.
