### ISSUE TITLE
Add Ramda as explicit npm dependency

### ISSUE THREAD

**Issue by afhole** [Codewars/codewars-runner-cli#428]
Currently an older version of ramda is available as a dependency: https://github.com/Codewars/codewars.com/issues/854#issuecomment-291317772

It would be great to add the latest version explicitly.

**Comment by kazk** [comment]
This was requested in #373 and added in #375.
The documentation wasn't updated to reflect that.

**Comment by afhole** [comment]
Awesome! Closing
