### ISSUE TITLE
C assertion outputs aren't very useful

### ISSUE THREAD

**Issue by OverZealous** [codewars/codewars-runner-cli#430]
The errors reported for C aren't very useful as they are only reporting the variable names, making it much harder to debug than necessary.

For example, this test:

```c
Test(find_smallest, should_work_with_negative_numbers)
{
  int actual = find_smallest((int[]){1,2,3,4,5,6,7,8,-9,10});
  int expected = -9;
  cr_assert_eq(actual, expected);
};
```

When failing simply reported:

`The expression (actual) == (expected) is false.`

It would be nice to see what values were being compared.

**Comment by kazk** [comment]
To show what's being tested, I think the framework is meant to be used like the following:

```c
Test(find_smallest, should_work_with_negative_numbers) {
  cr_assert_eq(find_smallest((int[]){1,2,3,4,5,6,7,8,-9,10}), -9);
};
```

which displays

```
The expression (find_smallest((int[]){1,2,3,4,5,6,7,8,-9,10})) == (-9) is false.
```

or simply using the optional format string.

```c
Test(find_smallest, should_work_with_negative_numbers) {
  int actual = find_smallest((int[]){1,2,3,4,5,6,7,8,-9,10});
  int expected = -9;
  cr_assert_eq(actual, expected, "find_smallest((int[]){1,2,3,4,5,6,7,8,-9,10}) != -9");
};

// or, write `array_to_str` helper function and
// cr_assert_eq(actual, expected, "find_smallest(%s) != %d", array_to_str(input), expected);
```

---

For testing multiple array inputs, using [parameterized tests](http://criterion.readthedocs.io/en/master/parameterized.html) will help.

**Comment by kazk** [comment]
Closing because https://github.com/codewars/codewars-runner-cli/issues/430#issuecomment-304407567
