### ISSUE TITLE
Java files encoding currently accepts only ASCII

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#449]
Related to changes for #383 I've seen a new error that says

> Error: Command failed: javac -verbose -cp /home/codewarrior -d /home/codewarrior -sourcepath /home/codewarrior -cp /usr/local/groovy/lib/junit-4.12.jar:/usr/local/groovy/lib/hamcrest-core-1.3.jar /home/codewarrior/Kata.java /home/codewarrior/BonusTimeTest.java ./frameworks/java/CwRunListener.java
> [parsing started RegularFileObject[/home/codewarrior/Kata.java]]
> [parsing completed 26ms]
> /home/codewarrior/BonusTimeTest.java:10: error: unmappable character for encoding ASCII

Tu support more than ASCII add `-encoding utf-8` as param to javac program to accept utf-8 encoding.

Just in case you need another charset I'll drop [this link](http://docs.oracle.com/cd/B19306_01/server.102/b14225/ch2charset.htm)

**Comment by javatlacati** [comment]
Reviewed the code the problem is here on this line:

    (def ^:private file-manager (byte-code-manager (.getStandardFileManager compiler nil nil nil)))

The current Java equivalent is:

    private StandardJavaFileManager fileManager = compiler.getStandardFileManager(null, null, null);

And should be modified to something equivalent to:

    private StandardJavaFileManager fileManager = compiler.getStandardFileManager(null, java.util.Locale.getDefault(), java.nio.charset.Charset.forName("UTF-8"));

or

    private StandardJavaFileManager fileManager = compiler.getStandardFileManager(null, java.util.Locale.US, java.nio.charset.Charset.forName("UTF-8"));


Hoope it helps.

**Comment by javatlacati** [comment]
You can test it at: https://www.codewars.com/kata/do-i-get-a-bonus/train/java

**Comment by jhoffner** [comment]
This should be covered by PR #447

**Comment by javatlacati** [comment]
if you deployed to preview it didn't worked :/

**Comment by jhoffner** [comment]
I haven't yet.

**Comment by jhoffner** [comment]
OK #460 should resolve this specifically.
