### ISSUE TITLE
Java tests fail due to deprecated API use warning in the test runner

### ISSUE THREAD

**Issue by duncan-at-hiveit** [Codewars/codewars-runner-cli#457]
This has started to affect multiple Katas.  Something is now deprecated that did not used to be.  It seems like the test runner treats this as a test failure:

STDERR:
Note: /home/codewarrior/src/main/java/KataTests.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

See comments here for multiple katas affected by this.  It only seems to have appeared in the last 24 hours:

https://www.codewars.com/kata/550f22f4d758534c1100025a/discuss#5968e5a66875986b2500015b

and here:

https://www.codewars.com/kata/unflatten-a-list-harder-than-easy/discuss/java

Many thanks,
Duncan

**Comment by jhoffner** [comment]
PR #459 should resolve this

**Comment by duncan-at-hiveit** [comment]
Many thanks for the speedy fix Jake!
