### ISSUE TITLE
New Swift Runner is not rendering proper output

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars-runner-cli#463]
@kazk I have no idea what is going on but the latest runner is not sending proper output:

https://preview.codewars.com/kata/some-egyptian-fractions/train/swift

![image](https://user-images.githubusercontent.com/579835/28235581-aca5805c-68c5-11e7-8efd-40b547f38f1f.png)

I'm looking into it now to make sure there wasn't some sort of deployment error but I need to leave soon.

**Comment by kazk** [comment]
You need to use `_XCTMain` as described in #451 under "Required Changes". For more detailed reason I wrote https://github.com/Codewars/codewars-runner-cli/issues/448#issuecomment-314555315.

**Comment by kazk** [comment]
@jhoffner 
I don't know why I didn't think of this, but I can replace `XCTMain` with `_XCTMain` inside `testIntegration` so that there's no compatibility issue from users' point of view.

**Comment by jhoffner** [comment]
Ah, I completely missed that it was a breaking change to existing content. I had thought there was some sort of rewrite already happening. I see two options:

### Option 1
Automatically rewrite user code with `opts.fixture.replace(/^ *(XCTMain *\( *\[)/m, '_$1')`

### Option 2
Don't use an Observer at all and simply format the natural output, since it seems to be easily parsable:

```
Test Suite 'All tests' started at 02:03:29.842
Test Suite 'codewarrior.xctest' started at 02:03:29.998
Test Suite 'SolutionTest' started at 02:03:29.998
Test Case 'SolutionTest.decompse' started at 02:03:29.999
/workspace/main.swift:9: error: SolutionTest.decompse : XCTAssertEqual failed: ("test") is not equal to ("1/2,1/4") - should return 1/2,1/4
/workspace/main.swift:9: error: SolutionTest.decompse : XCTAssertEqual failed: ("test") is not equal to ("3") - should return 3
/workspace/main.swift:9: error: SolutionTest.decompse : XCTAssertEqual failed: ("test") is not equal to ("1/2,1/4,1/20") - should return 1/2,1/4,1/20
/workspace/main.swift:9: error: SolutionTest.decompse : XCTAssertEqual failed: ("test") is not equal to ("1/2,1/7,1/59,1/5163,1/53307975") - should return 1/2,1/7,1/59,1/5163,1/53307975
/workspace/main.swift:9: error: SolutionTest.decompse : XCTAssertEqual failed: ("test") is not equal to ("1/2,1/3,1/9,1/83,1/34362") - should return 1/2,1/3,1/9,1/83,1/34362
Test Case 'SolutionTest.decompse' failed (0.001 seconds)
Test Suite 'SolutionTest' failed at 02:03:30.000
	 Executed 1 test, with 5 failures (0 unexpected) in 0.001 (0.001) seconds
Test Suite 'codewarrior.xctest' failed at 02:03:30.000
	 Executed 1 test, with 5 failures (0 unexpected) in 0.001 (0.001) seconds
Test Suite 'All tests' failed at 02:03:30.000
	 Executed 1 test, with 5 failures (0 unexpected) in 0.001 (0.001) seconds
```

I'm going to go with option #1 right now since it seems safer and less error prone.

**Comment by kazk** [comment]
I just opened a PR for option 1. I don't know why I didn't think of this :/
