### ISSUE TITLE
Add Erlang Support

### ISSUE THREAD

**Issue by kazk** [Codewars/codewars-runner-cli#474]
I've started looking into adding Erlang support.

- [Erlang/OTP 20.0](http://www.erlang.org/news/114) (2017-06-21)
- Use [rebar3](http://www.rebar3.org/)
- Output using `eunit_listener`

`erlang-runner` is locked to Erlang/OTP 18.x for Elixir 1.2.4 (#473).
I'm thinking of just making a new `erlang-runner` and turning the existing one into `elixir-runner`.

**Comment by jhoffner** [comment]
> I'm thinking of just making a new erlang-runner and turning the existing one into elixir-runner

That's fine if that's what needs to happen. Ideally they would be on the same image just to minimize overhead (container overhead, ram overhead, startup overhead, image management, testing, etc). The list of containers is getting pretty large - but at this point we may just have to accept this as business as usual.
