### ISSUE TITLE
Custom error message in Dart

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#481]
I don know if related to #410 but I want to show a specified message for Dart tests.

How can I do it?

Here my attempts so far:
https://preview.codewars.com/kumite/597f5ecdb44a5fec1800000d/?sel=597f5ecdb44a5fec1800000d

It only shows

> Test Results:
> Codewars is in the array
> ! Test Failed

**Comment by kazk** [comment]
I think you need to rewrite [lib/runners/dart.js](https://github.com/Codewars/codewars-runner-cli/blob/6d90a54f1ae484a4298a5395b55238d6c469476f/lib/runners/dart.js).

```js
for (let id in results) {
  let test = results[id];
  stdout += `<IT::>${test.name}\n`;
  stdout += test.result == 'success' ? `<PASSED::>Test Passed\n` : `<FAILED::>Test Failed\n`;
  stdout += `<COMPLETEDIN::>${test.runTime}\n`;
}
```
[lib/runners/dart.js#L112-L117](https://github.com/Codewars/codewars-runner-cli/blob/6d90a54f1ae484a4298a5395b55238d6c469476f/lib/runners/dart.js#L112-L117).

If Dart's test output JSON includes those custom messages, it should be possible by modifying above lines.

**Comment by javatlacati** [comment]
You mean like adding variable desidered to the output?

    stdout += test.reason ? `${test.reason}` : '';

**Comment by javatlacati** [comment]
It will fix the issue in this Kata https://www.codewars.com/kata/sum-of-numbers-from-0-to-n/train/dart

**Comment by kazk** [comment]
I rewrote the test reporter for Dart 2.1 and backported to 1.x. So this is fixed now. Your kumite outputs

![image](https://user-images.githubusercontent.com/639336/53212896-91c23c80-35fb-11e9-9102-439c64fb0bb0.png)
