### ISSUE TITLE
Ruby error messages inside `it` blocks are processed improperly

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#484]
Let's say I have this code in text fixture:

```ruby
def func
  10.times do
    continue if true
  end
  return -1
end

describe "foo" do
  it "bar" do
    puts func
  end
end
```

There is a syntax error: `continue` should actually be `next`.

When things are run inside an `it` block and throws an error, the error message is incorrectly butchered:

![image](https://user-images.githubusercontent.com/14909989/28854816-db373bea-776b-11e7-959a-422e608a6633.png)

Removing the `it` block resolves the issue, however it also removes the test block:

![image](https://user-images.githubusercontent.com/14909989/28854871-0d932fc2-776c-11e7-8428-fac42c151932.png)

**Comment by kazk** [comment]
Confirmed with Codewars test framework, RSpec 3 handles this fine.
The actual test output from the test framework is:

```
<DESCRIBE::>foo

<IT::>bar

<ERROR::>#<NameError: undefined local variable or method `continue' for main:Object><:LF:> `block in func'<:LF:> `times'<:LF:> `func'<:LF:> `block (2 levels) in <main>'

<COMPLETEDIN::>

<COMPLETEDIN::>1ms
```

**Comment by Voileexperiments** [comment]
@kazk is this fixed in the new runner?

**Comment by kazk** [comment]
No. I think this is caused by the frontend (I don't know much about it).

The server is correctly returning object like this:

```json
{
  "t": "error",
  "v": "#<NameError: undefined local variable or method `continue' for main:Object>\n `block in func'\n `times'\n `func'\n `block (2 levels) in <main>'"
}
```

It's probably that `<NameError: undefined local ...` is being treated as invalid HTML. I might be able to fix this by changing the test output so I'll look into it.

**Comment by 10XL** [comment]
Any updates to this?

**Comment by kazk** [comment]
No, I thought about simply escaping `<` on the server side but decided not to because I'm not sure how it's handled on the frontend. I haven't spent much time on this either because of other tasks.

Maybe I can change the output from
```
<ERROR::>#<NameError: undefined local variable or method `continue' for main:Object><:LF:> `block in func'<:LF:> `times'<:LF:> `func'<:LF:> `block (2 levels) in <main>'
```
to
```
<ERROR::>NameError
<LOG:ESC:Error>#<NameError: undefined local variable or method `continue' for main:Object><:LF:> `block in func'<:LF:> `times'<:LF:> `func'<:LF:> `block (2 levels) in <main>'
```

/cc @jhoffner

**Comment by jhoffner** [comment]
I thought Error messages should always be escaped, because they should never contain HTML that is meant to be rendered. I think the one edge case to this was Crystal, because it provides ansi formatting for better log/error messages, which is converted to HTML by us. Thats why a "raw" output type was added.

**Comment by Blind4Basics** [comment]
\o/

Waiting eagerly for the deployment, because I just lost like 2 hours scratching my head on a translation until I realized that what the error message didn't tell me was that there was a damn _f..._ing misspelled variable some lines further in my code... x/

**Comment by kazk** [comment]
Deployed the fix.

![image](https://user-images.githubusercontent.com/639336/43922530-e6434d98-9bd3-11e8-92e3-de9afccb9b8f.png)
