### ISSUE TITLE
Request Error when try to run tests on Katas with JS

### ISSUE THREAD

**Issue by GeorgeGkas** [Codewars/codewars-runner-cli#485]
Language: JavaScript

**What's the problem:**
Every time I hit either "Run Sample Tests" or "Attempt" on any Kata, I get *Request* and *Server Execution* errors.

**When it first occurred**:
Wed Aug 02 2017 11:09:00 GMT+0300 (EEST)

**How to reproduce:**
1. Find a kata. (eg [Twice linear](https://www.codewars.com/kata/twice-linear/train/javascript))
2. Hit "Run Sample Tests" (you don't have to provide a solution).

**Output:**
After you hit "Run Sample Tests" switch your attention in the Output screen. Bellow I provide each output I get:
1. Status: Sending Request... 
2. Status: Assigning a server... 
3. Status: Request received 
4.
```
Network Error

This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.
```
*Press "You can retry the request."*

5. Status: Sending Request... 
6. Status: Assigning a server... 

7.
```
Server Execution Error:
The server attempted to execute your code but there was an issue with the request. This should be a rare issue. Please try running your code again. If the issue persists, please contact us.
```
```
Request Error:

Network Error
This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.
```

**Console output:**
I debug the page with my browser's console. Bellow is the output after I click either "Run Sample Tests" or "Attempt":
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://runner.codewars.com/run. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```
I do not know if it relates with the above issue, but I found it interested.

**What I've tried to solve the issue:**
* Restart my router.
* Restart my computer.
* Clear browser cache.

I believe the source of the problem is related with the servers that execute the provided code. Please check it.

Regards,
George

**Comment by DaveOrrock** [comment]
Same issue for myself, been a problem for the last 5hrs at least. The runner is showing as online on the service outages page.

**Comment by patricksile** [comment]
Hey I have been going through the same problem for 2 weeks now and I can tell you it is pretty bad for me, and I don't know what can be done about it @jhoffner please do something. Thanks....
