### ISSUE TITLE
Replace sync code with async code. 

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars-runner-cli#49]
Much of the code has been implemented in their sync forms. The exec-sync package was recently added to the project as well. This package is not meant to be used in production code. 

All code should be asynchronous to ensure that the server doesn't lock up when dealing with additional requests.

**Comment by xcthulhu** [comment]
Hi Codewars/codewars-runner,
A message from Matthew Wampler-Doty was left on IQ Elite for you. 
Click here a.iqelite.com/j/0JmRlo/47e/?hg=MGkIj0LW8Q to read your message 


The IQ Elite Team



---------------------------------------------------------------------------
This message was meant for reply@reply.github.com. If you do not want to continue receiving such mails from IQ Elite, please click on this link: a.iqelite.com/common/unsubscribe/?code=5d44a6b2&email=reply@reply.github.com&hg=MGkIj0LW8Q
IQ Elite is a service with main office: C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelona, Spain.
---------------------------------------------------------------------------
