### ISSUE TITLE
go support

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars-runner-cli#5]

**Comment by xcthulhu** [comment]
Hi Codewars/codewars-runner,
A message from Matthew Wampler-Doty was left on IQ Elite for you. 
Click here a.iqelite.com/j/0JmRlo/ghy/?hg=E81ByDHjf0 to read your message 


The IQ Elite Team



---------------------------------------------------------------------------
This message was meant for reply@reply.github.com. If you do not want to continue receiving such mails from IQ Elite, please click on this link: a.iqelite.com/common/unsubscribe/?code=b198c50e&email=reply@reply.github.com&hg=E81ByDHjf0
IQ Elite is a service with main office: C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelona, Spain.
---------------------------------------------------------------------------

**Comment by Kavignon** [comment]
What's the current state here? Do we need to create a personal Go test framework? Can we use ginkgo?

**Comment by jhoffner** [comment]
ginkgo 👍

**Comment by Kavignon** [comment]
Perfect. This is the perfect chance for me to finally learn about Scala & Go. I try to be as fast as possible, but I think 5 languages by september will be awesome ?

**Comment by jhoffner** [comment]
Yeah that all sounds great! Though other members may want to contribute as well. I would say pick your top language and then take it one language at a time.
