### ISSUE TITLE
Julia run issues

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars-runner-cli#505]
![image](https://user-images.githubusercontent.com/579835/29439672-04359d70-8374-11e7-94bc-0c19e8ecb906.png)

You can test within a [kumite](https://www.codewars.com/kumite/5996399c0a14ac9b200000e4?sel=5996399c0a14ac9b200000e4). This is with 

```
module AgeUtils
export two_oldest_ages
  function two_oldest_ages(ages)
    oldest = 0
    next_oldest = 0;
    for age in ages
      if age > oldest
        next_oldest = oldest
        oldest = age
      else age > next_oldest
        next_oldest = age
      end
    end
    return [next_oldest, oldest]
  end
end
```

and 

```
# some example data
using AgeUtils
results1 = two_oldest_ages([1,5,87,45,8,8])
results2 = two_oldest_ages([6,5,83,5,3,18])

facts(()->(@fact  results2[1] => 18) ,"Number is not the second oldest")

facts(()->(@fact results1[2] => 83))
```

**Comment by jhoffner** [comment]
It looks like the example code taken from julia.yml just doesn't work. I am able to get a basic example to work.

**Comment by sunoru** [comment]
Hello Jake,
I'm interested in filing a PR for fixing the current issues within Julia test framework and completing the examples. I wonder if it's OK to upgrade everything to 0.6 - since Julia has not been 1.0 yet and the syntax has been changed so frequently that there's various outdated code at present. I'm really looking forward to the support of Julia kata on codewars :)

**Comment by kazk** [comment]
@sunoru
We're working on the new system that is more flexible and have Julia 0.6 with patched FactCheck.jl (from https://github.com/JuliaArchive/FactCheck.jl/commit/51a5e71937e3d35c0ce8e5b9fbbf84ffba81dd45) there.
We can't give ETA yet, but it's in progress.

**Comment by sunoru** [comment]
@kazk oh, I see. That's nice. Is there anything I can help?

**Comment by kazk** [comment]
@sunoru Thanks. Nothing at the moment because Julia's implementation is mostly complete and we're currently working on other languages. But authoring kata and giving feedbacks once it becomes available will help us to make it better.

**Comment by sunoru** [comment]
@kazk OK, I'm looking forward to it!

**Comment by kazk** [comment]
Closing as resolved. We're planning to release Julia 0.6 support tonight.
