### ISSUE TITLE
cw-2.py throws UnicodeEncodeError

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#508]
I'm doing this kata today:

https://www.codewars.com/kata/so-many-kinds-of-numbers/discuss

Turns out that the test methods message reports are using `ascii` as the encode charset, and hence will cause problems when trying to print out unicode characters.

```
Traceback:
   in <module>
  File "./frameworks/python/cw-2.py", line 28, in assert_equals
    expect(actual == expected, message, allow_raise)
  File "./frameworks/python/cw-2.py", line 16, in expect
    print("\n<FAILED::>{0}".format(message))
UnicodeEncodeError: 'ascii' codec can't encode character '\xb2' in position 13: ordinal not in range(128)
```

**Comment by SpecterTerrasbane** [comment]
Coming here from [#459](https://github.com/Codewars/codewars.com/issues/459), regarding the [Vigenere Cipher Helper](https://www.codewars.com/kata/vigenere-cipher-helper) kata:

I don't know if this helps, but running against tests with unicode in the _authoring_ editor works just fine, while running the exact same solution code in the _training_ editor causes the issue that everyone is complaining about in the comments on that kata.  Observed when I attempted to edit the kata to see what was going on with the Katakana test.

**Comment by kazk** [comment]
Fixed in https://github.com/Codewars/codewars.com/issues/1336

```python
test.assert_equals("x", u'\u2713')
```
Python 3.4/3.6
```
'x' should equal '✓'
```
Python 2.7
```
'x' should equal u'\u2713'
```
