### ISSUE TITLE
Seeing webrequest issues when running C code

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars-runner-cli#509]
When trying to run C code, I repeatedly encounter

--
Request Error:
Cannot create property 'flags' on string '<!DOCTYPE html><html lang=en xml:lang=en><meta charset=utf-8><meta http-equiv=Content-Language content=en><meta name=description content="Run programming languages safely within your browser."><meta name=robots content=nofollow><meta name=google content=notranslate><title>CodeRunner</title><script src=https://cdn.ably.io/lib/ably.min.js></script><script type=text/javascript>window.webpackManifest={"0":"static/js/0.4a1c5f6008802bcebe36.js","1":"static/js/1.0cc99290246adbac79c9.js","2":"static/js/2.0a41e7ec7a24f3afdbf6.js","3":"static/js/3.b49295107180cc9e6e24.js"}</script><link href=/static/css/app.98bf950ac8826bafdaa88b7b3e724635.css rel=stylesheet><body><div id=app></div><script type=text/javascript src=/static/js/manifest.d18fde6882adf3832bcb.js></script><script type=text/javascript src=/static/js/vendor.0a41e7ec7a24f3afdbf6.js></script><script type=text/javascript src=/static/js/app.b49295107180cc9e6e24.js></script></body></html>'

This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.
--

This is persistent for already about 15 minutes.

**Comment by nomennescio** [comment]
Not sure if this repo is the correct one, will also submit to codewars.com at Github

**Comment by nomennescio** [comment]
Closing Codewars in the browser, then reentering the Kata ("Train Again") showed me the code, and running went fine.

Unclear why this is reported as a request error.

**Comment by Voileexperiments** [comment]
I think it happens whenever you have

> This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.

More than once in a row.

**Comment by jhoffner** [comment]
If you refresh your cache this should be resolved now. Its a bit tricky to reproduce but I think I got it covered.
