### ISSUE TITLE
Mono 5 Support

### ISSUE THREAD

**Issue by Souzooka** [Codewars/codewars-runner-cli#510]
What needs to be done to integrate Mono 5 into Codewars?

According to the [Mono website](http://www.mono-project.com/download/), the package for Mono 5 seems to be already included in the `mono-complete` package.

**Comment by kazk** [comment]
As explained in https://github.com/Codewars/codewars-runner-cli/issues/496#issuecomment-322351728, current implementation is very hacky for historical reasons and we're planning to phase out.

For the new version, I'm considering to replace Mono with .Net Core, make it straightforward and more natural (`dotnet build/run/test`).

**Comment by kazk** [comment]
Closing this because we'll add .Net Core 2.1 (C# 7.3) instead. Maybe some time next week.
