### ISSUE TITLE
CW JS does not handle comments in last line well

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#514]
If you put a comment at the last line of user solution, it does not play well with CW (because of how the code are injected together).

Now, normally putting a comment in the last line will cause errors. However, I found a way to circumvent it, but putting a function declaration before the comment:

```javascript
f=_=>//
```

This would run basically the same as just putting a `return`.

In general, CW just doesn't handle comments in the last line well. IMO if user solution code is injected into the whole code runner, there should a newline after user solution before other stuff so that injection attacks like the above becomes impossible.

**Comment by kazk** [comment]
I can see that the last line comment can cause issues when the previous line is an expression without semicolon.

```js
var foo = function() {}
//
```
Is this what you mean?
This can be fixed with inserting `\n` like you said or adding `;` at the beginning of the line after the solution.

**Comment by Voileexperiments** [comment]
The issue with this is that since a last line single-line comment will *eliminate all the code after it*, if the user has put tests in Preloaded and they passed, this will allow them to effortlessly bypass all the tests. (If there are no tests in Preloaded code terminates with 0 passed tests, which defaults to "failed" so it isn't a problem.)

**Comment by kazk** [comment]
I see. The concatenation turns the code into something like this:
```javascript
f=_=>//;
(function() {
})();
```
```javascript
f=_=>(function() { })();
```

This should be fixed in the new runner because I changed where the semicolon is inserted and added line break:
```javascript
f=_=>//

;(function() {
})();
```

> if the user has put tests in Preloaded

This is more concerning. Tests shouldn't be in preloaded.
I was thinking of loading `cw-2` after the solution so that it prevents cheating thorough modifying the `global` or `Test` easily. Is this common on CW?

**Comment by Voileexperiments** [comment]
`global` can't be modified because there are checks on it, not even `var global` will work:

https://github.com/Codewars/codewars-runner-cli/pull/298

IIRC `Test` also has the same anti-cheat; it's only a problem if people are using the global version of `describe` and `it` instead of the ones under `Test` (trust me, lots of people do this), which can be overridden by `var it` or something. I don't think aliasing them to `global` is a good idea in the first place.

The problem though is that often we want some variables to be constructed before user code is run and check them with tests (e.g in a golf kata you want to check code length, in a source restriction kata you want to check source code, etc). Currently there aren't any ways to safely transport variables in Preloaded to the test fixture, and throwing errors in Preloaded is a bad, *bad* idea: it blocks all subsequent things, *even when user is just running sample tests*.

**Comment by kazk** [comment]
> Currently there aren't any ways to safely transport variables in Preloaded to the test fixture

Use `const`? For objects, freeze it?
```javascript
// Preloaded
const V = "computed something before user code";
```
```javascript
// Tests
Test.assertEqual(V, "computed something before user code");
```

---

I'm not changing it anytime soon. Just looking to replace bad ideas to better ones with minimum breakage over time.
I'd like to get rid of concatenation for JS too (provide an option to use modules so existing contents will still work).
I'm shocked by the number of solutions getting this error:

```
});
 ^
SyntaxError: Unexpected token )
```
because `{` in the solution is not closed. This appears almost once per minute and I can imagine them confused because their code doesn't contain `});`.

**Comment by kazk** [comment]
cw-2.js needs to be rewritten. `uncaughtException` swallows the exception unless it's `async`.
I don't even know why it's written that way, wrapped in `try...catch`.

**Comment by Voileexperiments** [comment]
> Use `const`? For objects, freeze it?

But that's not *clean*. Preferably there shouldn't be any traces of them during the user code part.

> I'd like to get rid of concatenation for JS too (provide an option to use modules so existing contents will still work).

Moreover, because it's concatenated the classic "reveal the whole fixture" cheat works. `console.log` will hide the test fixture code somewhat but it's trivial to bypass it.

**Comment by kazk** [comment]
Closing because the original issue is resolved with the new runner.

I really want to avoid concatenation for JS, but it's not happening anytime soon. `cw-2.js` is a mess and I'd like to do something about it too. I'll come back to them after finishing other tasks.
