### ISSUE TITLE
SQL katas broken with UndefinedConversionError

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#523]
From this kata:

https://www.codewars.com/kata/sql-basics-simple-table-totaling

It wasn't broken until lately, which gives this message:

```
An error occurred while loading ./.entry.rb.
Failure/Error: print(tab ? "TAB" : "LOG", data.to_json, mode: "TABLE", label: label)

Encoding::UndefinedConversionError:
  "\xE4" from ASCII-8BIT to UTF-8
# /runner/frameworks/ruby/common.rb:17:in `encode'
# /runner/frameworks/ruby/common.rb:17:in `to_json'
# /runner/frameworks/ruby/common.rb:17:in `table'
# /runner/frameworks/ruby/sql.rb:84:in `block in run_sql'
# /runner/frameworks/ruby/sql.rb:74:in `map'
# /runner/frameworks/ruby/sql.rb:74:in `run_sql'
# ./.spec.rb:1:in `<top (required)>'
# ./.entry.rb:6:in `<top (required)>'

No examples found.
```

**Comment by kazk** [comment]
This kata uses <https://www.codewars.com/users/leaderboard> and now we have more CJK characters up there.

Adding `ENV['PGCLIENTENCODING'] = 'UTF8'` before the table is created should fix this.
![image](https://user-images.githubusercontent.com/639336/29997546-ddf94a22-8fca-11e7-80c0-9892166b7cb7.png)

![image](https://user-images.githubusercontent.com/639336/29997538-bb4d18aa-8fca-11e7-8c79-e5f422cf6e04.png)

For more permanent fix, I guess we can add that to environment variable during the image build (or set the option when connecting), but I don't know how it'll affect other kata so I won't do it for now.
