### ISSUE TITLE
Frequent timeouts with Rust

### ISSUE THREAD

**Issue by tjdett** [Codewars/codewars-runner-cli#534]
As with #440, I'm seeing lots of timeouts for quite simple Rust code. This applies to both compiling and non-compiling code, but mainly code which won't compile. In most cases, after attempting with the same code enough times a good response will come back, but it can take a lot of tries.

Successes have run times of a couple of seconds, so it doesn't feel like this is just random variation in compile times.

**Comment by joshsleeper** [comment]
I can confirm that I've seen the same thing with high frequency.

**Comment by kazk** [comment]
I realized that changing `RUSTFLAGS` (added to disable the warnings for backward compatibility) causes crates to be recompiled. So currently `libc` and `rand` are being recompiled on **every submission** in addition to the solution.
I'll open a PR to fix this soon.

**Comment by kazk** [comment]
Forgot to close this (fixed in #537). Please let me know if this is still happening.
