### ISSUE TITLE
Clang 3.6 / C11 crash : update compiler?

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars-runner-cli#535]
During solving a Kata I wrote the following code snippet that crashes the Clang 3.6 C11 compiler

`--`
`// CRASHES COMPILER`
`typedef struct { int l; char* s; } string;`
`string dup (string s) { return (string) { s.l, memcpy (malloc (1+s.l), s.s, 1+s.l) }; }`
`--`

changing the name of the function (!!) results in a succesful compile

`--`
`// WILL COMPILE`
`typedef struct { int l; char* s; } string;`
`string dup_ (string s) { return (string) { s.l, memcpy (malloc (1+s.l), s.s, 1+s.l) }; }`
`--`

Clang has just released version 5.0.0, can you upgrade the Codewars runtime to a more recent Clang version?

**Comment by kazk** [comment]
> changing the name of the function (!!) results in a succesful compile

Isn't this because `dup` is defined in `unistd.h` (part of C POSIX library)?
Did it show any hint why it crashed?

**Comment by kazk** [comment]
Closing this because no response was given.
