### ISSUE TITLE
JavaScript does not recognize the ** exponential operator

### ISSUE THREAD

**Issue by JB-Walker** [Codewars/codewars-runner-cli#541]
[MDN Web Docs - JavaScript - Arithmetic operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators)

When this simple test function was executed in the 'Write Number in Expanded Form' kata the exponential operator was not recognized and it resulted in a syntax error:

function expandedForm(num) {
    return (2 ** 3);
}

STDERR:
[eval]:8
    return (2 ** 3);
.....................^  {note: dots added to correctly position caret}
SyntaxError: Unexpected token *
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at 
    at evalScript (bootstrap_node.js:353:27)
    at run (bootstrap_node.js:122:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:121:9)
    at bootstrap_node.js:504:3

**Comment by kazk** [comment]
Node 6.x doesn't support exponentiation operator. See [node.green ES2016-features](http://node.green/#ES2016-features-exponentiation------operator).

Select "Node v6.11.0/Babel" or "Node v8.1.3" to use it.
![image](https://user-images.githubusercontent.com/639336/32148228-e2e5ac8e-bcb0-11e7-832d-d65320f852a4.png)
