### ISSUE TITLE
Last Random Tests Fails everytime on site, but not on local machine.

### ISSUE THREAD

**Issue by fredz0003** [Codewars/codewars-runner-cli#542]
I found a rather interesting issue. Everytime I submit my solution the last random test fails. Only one test fails everytime. I've passed anywhere from 34, 17, etc, and everytime one fails. Usually that's a good indications of a bug in my algorithm, so I take the failed test, and run on my local machine and it passes everytime. I've never seen this before to where a failed test passes on my machine, usually if it fails, it should fail on my machine too but that's not the case.

Here's a demo of what I explained. [https://youtu.be/vhmWieF8EDs](url)

**Comment by kazk** [comment]
I think Python's test framework *stops* when a test fails, so "the last" random test fails is expected behavior.

What happens if you test it on Codewars (write tests in the editor under your solution) with "run sample tests"?

**Comment by fredz0003** [comment]
Just tested it, I took the failed test and ran it with the sample tests and it passed.

**Comment by kazk** [comment]
Please take a look at [the reply](https://www.codewars.com/kata/great-total-additions-of-all-possible-arrays-from-a-list/discuss/python#59f7749dc859cdc20b000018) you just got on kata discourse.
