### ISSUE TITLE
Python does not support special characters such as ♠♥♣♦

### ISSUE THREAD

**Issue by MarkSchemmer** [Codewars/codewars-runner-cli#545]
Python does not support such characters in the CW console and throws an error, every time I try to compare or use the characters.

**Comment by MarkSchemmer** [comment]
The following characters such as ♠♥♣♦

Here is an link to my translation [here please view](https://www.codewars.com/kumite/59fcbb016975983aa5000149?sel=59fcbb016975983aa5000149)

The error that is thrown is ```Error: python version python not supported```

**Comment by MarkSchemmer** [comment]
When you have the chance please PM me in the Gitter Channel I would like to help fix this issue if possible.

**Comment by kodaman2** [comment]
Just a suggestion why not use letters for the suits? H, S, D, C. Easier than dealing with unicodes across python versions.

**Comment by MarkSchemmer** [comment]
@kodaman2, That is actually a really good idea!

**Comment by MarkSchemmer** [comment]
I'm going to change the Kata and I will ask @myjinxin2015 about it as well!

**Comment by kazk** [comment]
Fixed with https://github.com/Codewars/codewars.com/issues/1336

Python 3:

```python
# any of these will work
print("♠♥♣♦")
print("\u2660\u2665\u2663\u2666")
print(u"♠♥♣♦")
print(u"\u2660\u2665\u2663\u2666")
```

Python 2:
```python
print u"\u2660\u2665\u2663\u2666"
```
