### ISSUE TITLE
How do I include guava as library in a Kata?

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#547]
Hello I've added

    // @config reference guava

as the [documentation said](https://github.com/Codewars/codewars-runner-cli/blob/9df0faf4eeacbf8b7e3e97e2c7d8d3b0fe62c9a5/documentation/environments/java.md) in the preloaded section but still got the following error:

> /home/codewarrior/src/main/java/Sum.java:1: error: package com.google.common.base does not exist
import com.google.common.base.Preconditions;

Check [the Kata](https://www.codewars.com/kata/5a036ce38ba91443fa0000b0/edit/java) if you please.

**Comment by javatlacati** [comment]
solved, [documentation](https://github.com/Codewars/codewars-runner-cli/blob/9df0faf4eeacbf8b7e3e97e2c7d8d3b0fe62c9a5/documentation/environments/java.md) is wrong.

where it says:
 
    // @config reference guava

should say:

    // @config: reference guava

please update documentation accordingly

**Comment by kazk** [comment]
`@config: reference` is not necessary anymore. The class path will include it when compiling.

**Comment by javatlacati** [comment]
Then please reopen until documentation is corrected

**Comment by kazk** [comment]
As indicated on README and description, this repository is obsolete and no longer updated. Documentation have been outdated for a long time and have moved to https://github.com/Codewars/codewars.com/wiki while ago.
