### ISSUE TITLE
Missing ScalaCheck in Scala

### ISSUE THREAD

**Issue by error256** [Codewars/codewars-runner-cli#551]
Generator-driven property checks don't work.
https://www.codewars.com/kumite/5a1439b569759823f5000036
```
Symbol 'type <none>.scalacheck.Gen' is missing from the classpath.
This symbol is required by 'value org.scalatest.prop.GeneratorDrivenPropertyChecks.genAndNameA'.
Make sure that type Gen is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
A full rebuild may help if 'GeneratorDrivenPropertyChecks.class' was compiled against an incompatible version of <none>.scalacheck.
    forAll { (a: Int, b: Int) =>
    ^
one error found
```
Apparently, ScalaTest uses ScalaCheck which is not available.

**Comment by kazk** [comment]
We've switched to using ScalaTest directly and ScalaCheck is installed there. Now we should be able to use property based testing.
I'll be updating the exiting contents once the change is applied to the frontend.
