### ISSUE TITLE
Add Swift 4 support

### ISSUE THREAD

**Issue by kazk** [Codewars/codewars-runner-cli#554]
Add Swift 4 support. This should be implemented in the new system we've been working on, but use this issue to keep track and to discuss for now.

Originally requested by @jpv123 in https://github.com/Codewars/codewars.com/issues/1250

**Comment by kyzmitch** [comment]
Hi, with lack of Swift 4 it's impossible to solve problems related to String manipulations. Please increase priority of that task.

**Comment by kazk** [comment]
Swift 4.0.x is supported on the new system. But we need to work on other parts and do more internal testing before making it available to Qualified/Codewars.

**Comment by kyzmitch** [comment]
Oh thanks for the info, nice to hear that

**Comment by kyzmitch** [comment]
Great news

**Comment by timvermeulen** [comment]
What's the status on this?

**Comment by d4rkd3v1l** [comment]
> It’s been supported.
> Existing kata needs to be updated and republished if they’re not compatible.

How can I do this? Can I update katas where I'm not the author? 
I would really love to see more Swift 4 support. It's just annoying to have to think/remember what the things were in Swift 3, e.g. with Strings.

**Comment by kazk** [comment]
@d4rkd3v1l if the kata allows contribution and if you have enough honor points (more than 4000 if I remember correctly) then you can edit the kata and republish.

If not, the best you can do is to request it by commenting on the kata.

164 Swift kata seems to support Swift 4 at the moment.
