### ISSUE TITLE
Mobile screen layout not dynamic

### ISSUE THREAD

**Issue by EdwardDunn** [Codewars/codewars-runner-cli#564]
I just wanted to report a bug I found when trying to use the website on my phone. When I open the kata pages the screen layout is not dynamic and elements overlap and flicker.

Phone - Samsung S6
Browser - Chrome
Page - https://www.codewars.com/kata/cryptic-cave-episode-1/train/java

![code-wars-issue](https://user-images.githubusercontent.com/22660271/34942201-978cdade-f9ee-11e7-9598-cfacc3fa9b88.png)

Hope this helps, I really enjoy using the site!

**Comment by kazk** [comment]
Closing this because this is out of scope of this repository.

See https://github.com/Codewars/codewars.com/issues for codewars.com issues and possibly a duplicate issue https://github.com/Codewars/codewars.com/issues/939
