### ISSUE TITLE
Add jsoup for Groovy

### ISSUE THREAD

**Issue by romerojp** [Codewars/codewars-runner-cli#565]
Tried to add it in a translation of a scraping kata.

https://www.codewars.com/kumite/5a60492dcadebf3214000086

**Comment by kazk** [comment]
This is not a bug because it was never available for Groovy. I can look into adding it later.

**Comment by javatlacati** [comment]
Since it's published perhaps you should add an additional bug named "you can publish Groovy translation with broken solutions"

**Comment by kazk** [comment]
You can publish translation with broken solution. But you shouldn't approve it if it's broken.

**Comment by kazk** [comment]
Added `jsoup` to Groovy 2.5

**Comment by javatlacati** [comment]
still not available on preview

**Comment by kazk** [comment]
It's been available on production. Try forking the kumite and change the version to 2.5.

**Comment by kazk** [comment]
I just republished the kata with Groovy 2.5.
