### ISSUE TITLE
Add libraries for Kotlin

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#573]
Kotlin doesn't recognize `@config` notation.

Please see [this](https://www.codewars.com/kumite/5a92fd475084d7219600012d?sel=5a92fd475084d7219600012d) example.

**Comment by kazk** [comment]
This is because those are Java only. Kotlin/Groovy/Scala doesn't have extra libraries installed.

I'm planning to make jars available without it for Java as well. I don't see significant speed gain and it doesn't scale well.

**Comment by kazk** [comment]
Your example doesn't make sense in Kotlin because Double can't be null.

```
fixture.kt:28:17: error: null can not be a value of a non-null type Double
        Sum.sum(null, 3.0)
```

Also, Kotlin has [Preconditions.kt](https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/src/kotlin/util/Preconditions.kt) in stdlib.
