### ISSUE TITLE
Trying to get Codewars Red subscription and I can't do it?

### ISSUE THREAD

**Issue by MarkSchemmer** [Codewars/codewars-runner-cli#576]
I keep giving my card's credentials, for payment on www.codewars.com, I keep receiving a response of "Subscription failure: Your card number is incorrect." When I use this card all the time and I know it works (I even checked with my bank).

I would like to buy Codewars Red to contribute to the website because, I learn a lot, I receive help, and finally I would like codewars.com to generate more revenue so the website can continue to grow and develop.

I can pay with my Visa debit card, Paypal, or Bitcoin. 

I'm sorry to say I don't feel comfortable paying with Alipay.

**Comment by Voileexperiments** [comment]
This should really go to the main Codewars.com repo. This repo is for the runner that's used for CW only, and not about the site itself.
