### ISSUE TITLE
Code runners not working

### ISSUE THREAD

**Issue by jpmartins** [Codewars/codewars-runner-cli#578]
Hello, 

Java and javascript code runner not working at the moment, and in the https://codewars.statuspage.io says all systems are operational... Affects more then one kata.

"Request failed with status code 500
This error was caused due to an issue processing the web request, not because of an issue executing your code"

Best regards,
João

**Comment by jpmartins** [comment]
It is working now.

**Comment by MakElblotto** [comment]
Maybe related; still appear to be having issues running C code with the same "Request filed with status code 500..." error.
