### ISSUE TITLE
Please update your C# compiler, is very outdated now.

### ISSUE THREAD

**Issue by lesair** [Codewars/codewars-runner-cli#579]
Codewar folks,

When I tried to use C# 7.0  features (like tuples) I am getting compilation errors. It seems you folks are not using the latest Roslyn 2.0 compiler. Can you please tell me when are you expecting to upgrade to the latest C# version? You're targeting Mono when you could be targeting the latest .NET Core version.

Best regards.

**Comment by suic86** [comment]
Any chance to get .NET Core instead of Mono? :)

**Comment by kazk** [comment]
@suic86 The new runner actually has .Net Core support that uses `dotnet test`, but it's really slow at the moment so we haven't enabled it.
I'll start working on improving C# soon for Qualified so Codewars will also get that once it's done.

**Comment by kazk** [comment]
Update: C# 7.3 (.Net Core 2.1) will be added soon. Current plan is sometime during next week. Most of the kata should work without changes. NUnit 3 deprecated some test attributes so tests using those needs to be updated.

**Comment by kazk** [comment]
C# 7.3 is released. We're currently running a script to make it available on existing kata so that might take some time.
