### ISSUE TITLE
Control characters printed in Crystal error messages

### ISSUE THREAD

**Issue by error256** [Codewars/codewars-runner-cli#582]
Crystal error messages contain control characters like this: `[32;1m^[0m`. I don't remember this happening before the new runner.

**Comment by kazk** [comment]
Thanks, I'll look into it. Can you post the link to the kata that this occurred?

**Comment by error256** [comment]
In case of any error, for instance: https://www.codewars.com/kumite/5ac7e398c211b9e4ee00002f?sel=5ac7e398c211b9e4ee00002f

**Comment by kazk** [comment]
Thanks! I found the cause and will start fixing soon.

**Comment by kazk** [comment]
I'll also fix the test output showing the test source code on failure while I'm at it.

**Comment by kazk** [comment]
Fixed and deployed on preview. I'll deploy it to the production soon.

**Comment by error256** [comment]
I don't know if it's been this way since then or it's a new issue, but now it's like
`<ERROR::>Error in line 1: while requiring "././spec.cr"<:LF:><:LF:>...`

**Comment by kazk** [comment]
Thanks for letting me know.
Crystal `0.24` prints compile error to `stderr` and I forgot that `stderr` is formatted differently from `stdout` on Codewars. I'll try fixing it soon.

**Comment by kazk** [comment]
The fix was deployed today.
