### ISSUE TITLE
JS: `Test.assertEquals` doesn't work for `NaN`

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#583]
I know that `NaN !== NaN`, but for testing purposes if both sides are `NaN`, shouldn't them be considered equal?

Besides, `Test.assertDeepEquals` passes for `NaN` at both sides too.

**Comment by kazk** [comment]
As [the documentation](https://github.com/Codewars/codewars.com/wiki/Codewars-JavaScript-Test-Framework#testassertequalsactual-expected-msg) states, it tests for strict equality (`===`). So it shouldn't work for `NaN`.

`Test.assertDeepEquals` uses lodash's `isEqual` which is used for (structural) equivalence so it makes sense that `_.isEqual(NaN, NaN)` is true.

**Comment by Voileexperiments** [comment]
@kazk But there are 2 ways to test strict equality: `===` and `Object.is`. And each has their own peculiarities:

- `===` returns `false` for `NaN` on both sides
- `Object.is` returns `false` for `+0, -0`

But these two edge cases *are* important. Can the tests be written like `(expected === actual) || Object.is(expected, actual)`?

**Comment by kazk** [comment]
`Object.is` is same value equality and should not be implicitly mixed with strict equality like that.
Also, that test will treat signed zeros the same so the only difference will be `NaN`. `NaN` should be special cased in my opinion.

I'm going to start working on cw-2.js soon and I'm planning to decouple assertions from the test framework. We can discuss this again after that if you want.
