### ISSUE TITLE
Add test support for SASS/SCSS

### ISSUE THREAD

**Issue by javatlacati** [codewars/codewars-runner-cli#584]
I've been recently experimenting with a test framework for SASS called true. It would be nice to have it included in the Codewars environment.

Characteristics:
* Open Source ( BSD-3 License )
* node module
* can be called from mocha as `var sassTrue = require('sass-true');`

**Comment by kazk** [comment]
Looks like [sass-true](https://github.com/oddbird/true) can be used with Mocha. I'll look into it when other higher priority tasks are done.

**Comment by kazk** [comment]
This will be tracked with HTML+CSS (#836). If we decide to support SCSS, it'll be a version of CSS and not a separate language.
