### ISSUE TITLE
[GNU Fortran] Provided example for using CW-2 testing framework has actual and expected arguments swapped

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars-runner-cli#586]
@kazk Not sure how it took me this long to notice this, but currently the code example for using CW-2 testing framework looks like this:

```fortran
program TestCases
  use CW2
  use Solution
  implicit none
  call describe("add")
    call it("adds integers")
      call assertEquals(add(1, 1), 2)
    call endContext()
  call endContext()
end program
```

When I designed the framework, the order of arguments for assertion procedure `assertEquals` (and other assertions as well) is `expected` followed by `actual`, not the other way round.  Not really a big issue, but if other Codewarriors use this code example to write their assertions then the failure messages might just get a tad confusing :wink:

**Comment by kazk** [comment]
All of the other "Codewars" test framework takes `actual` first. I think it's confusing to have an exception.
Is there a reason behind this decision?

**Comment by kazk** [comment]
I've updated the docs and opened a PR to update the example shown in the editor. It should get deployed soon.
