### ISSUE TITLE
CW language documentation needs to include system OS and architecture info

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#587]
Some C katas (and now NASM) will probably inevitably involve code that depends on system OS and architecture.

I was trying to pull out system OS info on different language versions (by printing the content of `/etc/os-release`), and turns out the results are all over the place:

- Ruby:
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.7.0
PRETTY_NAME="Alpine Linux v3.7"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```
- Python:
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- JS:
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.6.2
PRETTY_NAME="Alpine Linux v3.6"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```
- C#:
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Java:
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.7.0
PRETTY_NAME="Alpine Linux v3.7"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```
- NASM:
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Others: haven't tested yet

And I haven't got into system architecture yet, so I have no idea whether they're `x86`, `amd64` or `arm`.

I dunno, but if system OS in different docker images varies wildly like *that*, it should be mentioned in the documentations?

**Comment by kazk** [comment]
They all have the same kernel (the host VM's). And are [`x86_64` (aka `amd64`)](https://en.wikipedia.org/wiki/X86-64).

OS (Linux distributions) shouldn't affect kata and users' code shouldn't depend on OS level, e.g., distribution specific files. It can change depending on the requirements in the future.
