### ISSUE TITLE
[GNU Fortran] CW-2 assertEquals doesn't handle empty strings when printing

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars-runner-cli#590]
Currently, when the `assertEquals` subroutine is used with string arguments where one or both strings are of length `0`, it encounters the following runtime error:

```
At line 201 of file cw-2.f95 (unit = 6, file = 'stdout')
Fortran runtime error: Zero width in format descriptor
(A21, A0                                                                        
                                                                                                          ^
```

![2018-04-17 5 05 20](https://user-images.githubusercontent.com/7777884/38859903-901fbecc-4261-11e8-9198-18e52711d7bf.png)

UPDATE: Note that `assertNotEquals` will also have to be fixed accordingly.

**Comment by DonaldKellett** [comment]
@kazk Does the CW runner still pull the testing framework from my `fortran-kata` repo every time Fortran code is executed?

**Comment by DonaldKellett** [comment]
@kazk This issue should be fixed on [my end](https://github.com/DonaldKellett/fortran-kata), please help me close this Issue once it has been deployed to production, cheers :smile:

**Comment by kazk** [comment]
> Does the CW runner still pull the testing framework from my `fortran-kata` repo every time Fortran code is executed?

Not every time Fortran code is executed, but pulls when the image is built. I'll rebuild the image and let you know when I deploy it.

**Comment by kazk** [comment]
I've deployed to preview and it's working as expected. I'll deploy to the production soon.
