### ISSUE TITLE
please allow use of lombok's var

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#593]
If you try to use var you will get the following error

> WithoutLetterETest.java:85: error: Use of var is disabled by default. Please add 'lombok.var.flagUsage = ALLOW' to 'lombok.config' if you want to enable is.
    var randomNum = 3 + Math.random() * 20;

To solve it If you are using maven you just had to add a file named `lombok.config` at the project root folder

and the content should be

    lombok.var.flagUsage = ALLOW

I don't know how it should be done in your runner since haven checked it in a while.

**Comment by kazk** [comment]
I've removed Lombok from Java 11 and Java 8 will be kept as is.
