### ISSUE TITLE
JS: Test.assertDeepEquals should give the same message as Test.assertEquals on test success

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars-runner-cli#599]
Since `Test.assertDeepEquals` was added it has *always* printed the whole expected value as a string as success message, while `Test.assertEquals` has always been "Test passed". This causes problems when the value being tested is huge because it chokes the stdout and hence makes the test timeout.

`Test.assertDeepEquals` should have the same handling as `Test.assertEquals` on solution success.

**Comment by Voileexperiments** [comment]
The problem with this behaviour is that it's inconsistent with pretty much every other language. In all other languages, a passed test does not show the value.

**Comment by kazk** [comment]
I think it always showed the value:

https://github.com/Codewars/codewars-runner-cli/blob/a07114084838a002c53d512f6502996ba81d9ed7/frameworks/javascript/cw-2.js#L307


This will be resolved by deprecating cw-2 in Node 10. Older versions will stay as is for compatibility until the language version is deprecated in the future.
