### ISSUE TITLE
C++: Program crash with non-zero error code is not reflected in front-end output

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars-runner-cli#601]
Suppose I have this code as the test fixture:

```
auto t=std::vector<int>{};
int v=t[10];
```

This triggers segfault, as can be seen from the response from the runner (exit code 139):

```
{"type":"execution success","stdout":"","stderr":"","exitCode":139,"wallTime":1564,"timedOut":false,"message":"","token":"","result":{"serverError":false,"completed":false,"output":[],"successMode":"assertions","passed":0,"failed":1,"errors":1,"error":"","assertions":{"passed":0,"failed":1,"hidden":{"passed":0,"failed":0}},"specs":{"passed":0,"failed":1,"hidden":{"passed":0,"failed":0}},"unweighted":{"passed":0,"failed":1},"weighted":{"passed":0,"failed":1},"timedOut":false,"wallTime":1564,"testTime":null,"tags":null}}
```

But there is no indication of that in the front-end output, just one failed tests and error among some passed tests.

In C/Fortran/NASM/... when test code crashes with non-zero exit code, this will be shown instead:

![image](https://user-images.githubusercontent.com/14909989/39125578-fb4c6f68-4731-11e8-8592-f289cb4041f3.png)

**Comment by kazk** [comment]
> In C/Fortran/NASM/... when test code crashes with non-zero exit code, this will be shown instead:

I don't know about Fortran, but for C and NASM, Criterion provides that feature. We can't make it consistent across languages and test frameworks.

**Comment by Voileexperiments** [comment]
@kazk Or just a better indication of a non-zero error code: currently if all tests pass but program terminated with non-zero error code absolutely nothing is shown, even when timeouts will show a helpful error message:

![image](https://user-images.githubusercontent.com/14909989/41266378-3fa3b978-6e29-11e8-8576-ccc95111894a.png)

To anyone unknown of this phenomenon it's absolutely confusing

**Comment by kazk** [comment]
Forgot to close this. I agree that some helpful message explaining the number will be nice.
