### ISSUE TITLE
Please add jQuery as node package

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#603]
As you might see in the commit https://github.com/Codewars/codewars-runner-cli/pull/375 it was supposed to be already added but it is not, please see [this kumite](https://www.codewars.com/kumite/5adef2556edb07a36d0000c3/edit) where the error couldn't be more clear

> Error: Cannot find module 'jquery'
    at Function.Module._resolveFilename
    at Function.Module._load
    /home/codewarrior/index.js:11:9
    at Object.handleError

You can easily get the latest version from running 

    npm install jquery

**Comment by kazk** [comment]
As we've announced, this project is no longer used. So please keep in mind that contents/history of this repository is not relevant.

You can use jQuery by including it through `jsdom`.

**Comment by javatlacati** [comment]
I inlcuded trough jsdom and got

> Error: Cannot find module 'jquery'
at Function.Module._resolveFilename
at Function.Module._load
/home/codewarrior/index.js:11:9
at Object.handleError

**Comment by kazk** [comment]
Don't do `require('jquery')`. Include it in `jsdom` environment through CDN.

https://github.com/jsdom/jsdom/blob/master/lib/old-api.md#easymode-jsdomenv

**Comment by javatlacati** [comment]
> The old jsdom API, from before v10, is **hard to use** and **understand**, and **has bad defaults**. But for now, it still has more features than the new API introduced in v10. As such, it is still supported, until we can port over all important features (notably custom resource loading) to the new API.

So please add jQuery as node package

**Comment by kazk** [comment]
Then use the new API described on their README. I just pointed to the old API because we use that on Qualified.

**Comment by kazk** [comment]
Also, you'd need to use it through `jsdom` either way.

**Comment by kazk** [comment]
If you're trying to extract something from remote HTML, don't use jQuery.
Use https://www.npmjs.com/package/cheerio which is available on Codewars.
