### ISSUE TITLE
Please add protobuf-java to java dependencies [request/package]

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#604]
I'd like to create some exercises for Google Protocol Buffer that is very helpful for creating protocols.

You can get the dependency information in [maven central repository](http://search.maven.org/#artifactdetails%7Ccom.google.protobuf%7Cprotobuf-java%7C3.5.1%7Cbundle)

**Comment by kazk** [comment]
I'm going to close this because I can't see how this can be useful on Codewars. But feel free to comment here.

How are you going to add `.proto` file and compile them with protocol buffer compiler?

**Comment by javatlacati** [comment]
Protobuf is especially useful for RPC systems too bad you don't think them useful on cw.

**Comment by kazk** [comment]
I know probuf. I'm asking how are you going to use it on the limited Codewars platform.

> How are you going to add .proto file and compile them with protocol buffer compiler?

**Comment by javatlacati** [comment]
Since you have spring-boot instead of just spring, you can create servers communicate with them to make some services kata will be good but to optimize bandwidth and create simple protocol it would be great to have protos in my opinion.
Regarding the other stuff, protos are to be deserialized so you don't need to deserialize them from a file, you can deserialize them from a stream created from a string.

**Comment by kazk** [comment]
> Regarding the other stuff, protos are to be deserialized so you don't need to deserialize them from a file, you can deserialize them from a stream created from a string.

Don't you need a code generated from `.proto` to deserialize the message?

**Comment by kazk** [comment]
https://developers.google.com/protocol-buffers/docs/javatutorial#compiling-your-protocol-buffers

**Comment by javatlacati** [comment]
yes, you need the code, not the .proto, that's the point. If you need to compile it you can use the compiler tools from your JDK installation #488.

**Comment by kazk** [comment]
So you're suggesting to write those code by hand?

**Comment by javatlacati** [comment]
nope, compiling the code in runtime

**Comment by kazk** [comment]
> compiling **the code** in runtime

Where does that "code" come from then?

If you mean to also generate that, then you'd need `.proto` file passed into the runner.

**Comment by kazk** [comment]
By the way, [Hack-22](https://www.codewars.com/kata/5510caecaacf801f820002ac) uses `tools.jar`. It can be found at `/usr/lib/jvm/default-jvm/lib/tools.jar`.

**Comment by kazk** [comment]
If it's difficult to explain, can you show me in code? Assume this was installed and how'd you author a kata.
