### ISSUE TITLE
Missing language: Groovy [BUG]

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#605]
Caution: This kata does not currently have any known supported versions for Groovy. It may not be completable due to dependencies on out-dated libraries/language versions.

https://www.codewars.com/kata/scraping-get-the-year-a-codewarrior-joined/train/groovy

Blocked by #565

**Comment by kazk** [comment]
jsoup was never available for Groovy so this is not a bug.

**Comment by javatlacati** [comment]
The kata **is published** with an Approved Groovy translation so **it's a bug**.

**Comment by kazk** [comment]
No

> Caution: This kata does not currently have any known supported versions for Groovy. It may not be completable due to dependencies on out-dated libraries/language versions.

This message appears when publish failed.

**Comment by kazk** [comment]
Someone approved a broken translation and that's not a runner's bug.
