### ISSUE TITLE
Please add jsdom node module to coffeescript

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#607]
[Tried to translate a code requiring jsdom](https://www.codewars.com/kumite/5ae01d6d9c54afa0ec000001/edit) module and got the following error:

> Error: Cannot find module 'jsdom/lib/old-api.js'
    at Function.Module._resolveFilename
    at Function.Module._load
    /home/codewarrior/test.coffee:5:13
    at Object.handleError

**Comment by kazk** [comment]
CoffeeScript and JavaScript is in separate images now and won't have same packages installed. CoffeeScript will remain minimum because it's rarely used with packages and often just translated for easy honor points.
