### ISSUE TITLE
please add selenium module to node [request/package]

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#608]
I'd like to have selenium web driver for some real test for testing automation Katas.

**Comment by kazk** [comment]
What exactly are you planning to do with it?
Selenium will be a huge dependency (requires Java if I remember correctly) and I'm not going to add rarely used packages.

I'm going to close this, but feel free to post comments.

**Comment by javatlacati** [comment]
this is not maven.central selenium java but **node** dependency selenium and as I already said for testing automation Katas.

**Comment by kazk** [comment]
https://www.npmjs.com/package/selenium-webdriver

This one right?

Needs Java and browsers installed.

> as I already said for testing automation Katas.

I'm asking because I don't see how you'd make it useful on Codewars.

**Comment by kazk** [comment]
Qualified will support headless Chrome for similar tasks, but it won't be made available to Codewars until Codewars frontend get updated to support more features.

**Comment by javatlacati** [comment]
I can train many testing automation engineers trough exercises in your platform, from the simple get the random word from the page (scrapping) to something like login on codewars and get your API token.
