### ISSUE TITLE
Kotlin solution marks error if print to error in the solution. [BUG]

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#610]
As you can see there's only one test that already passed, but if you print to the standard error console it will mark some inexisting error that allegedly maked the solution fail.

![image](https://user-images.githubusercontent.com/1063901/39484742-58242fd6-4d3c-11e8-8680-9c190764321b.png)

**Comment by kazk** [comment]
This is known Codewars limitation and applies to every language. I'd like to eventually avoid this in the future because it's also a huge pain from maintainer's point of view, but not any time soon.

**Comment by kazk** [comment]
Opened #613 for future enhancement.
