### ISSUE TITLE
Please add labels for "closed" issued

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#612]
Some reason for closing will be good since for some issues as [this](https://github.com/Codewars/codewars-runner-cli/issues/610) it's not clear if it's postponed or discarded.

So I propose the labels:

* not feasible for now
* won't fix
* can't be reproduced
* fixed
* deployed

the last two are because sometimes it is marked as closed but haven't been deployed not even to preview and reporting user might be confused and think that issue was not successfully patched.

**Comment by kazk** [comment]
Good idea.
For the last two, I only close the issue after deploying and usually comment when deployed on preview and need feedback.

**Comment by javatlacati** [comment]
Yeah some additional label for `needs feedback` or `please test` would be good

**Comment by kazk** [comment]
I won't be adding all of the labels suggested. I'll just try to leave a comment that's clear and also comment when it's deployed.
