### ISSUE TITLE
No way of printing in C synchronized with test output

### ISSUE THREAD

**Issue by error256** [Codewars/codewars-runner-cli#620]
It looks like there's no obvious way to synchronize stdout output with Criterion output. Now the output looks like this: https://www.codewars.com/kumite/5b0a815241e66a2864000088?sel=5b0a8b2807756fa1c10000ba
In new versions of Criterion there are `cr_log_*` macros/functions for this purpose. It looks like Codewars uses an older version or there's some other issue.

**Comment by kazk** [comment]
See #596. We're using Criterion 2.2.2 because 2.3.x is significantly slower when used with `--full-stats` which we need to report passed tests.
