### ISSUE TITLE
Cannot use math functions in NASM

### ISSUE THREAD

**Issue by monadius** [Codewars/codewars-runner-cli#621]
The standard math library functions are not available in NASM solutions and in the corresponding test cases. For example, if I use the function `log` in NASM test cases I will get the following linker error:
```
/tmp/ccabUXTG.o: In function `compare_powers_random_tests_impl':
fixture.c:(.text+0x61d): undefined reference to `log'
collect2: error: ld returned 1 exit status
```
It seems that the math library is not linked with `-lm`.

**Comment by kazk** [comment]
`-lm` is used. Can you post the tests?

**Comment by monadius** [comment]
Here is a fork of my NASM translation where test cases contain the `log` function: https://www.codewars.com/kumite/5b1de7769e40b98b56000060?sel=5b1ec64ba454c8d2a5000071

**Comment by kazk** [comment]
Found the fix. I had to move the `-lm` after the files.
I'll let you know when I deploy it.

**Comment by kazk** [comment]
The fix is deployed.

**Comment by monadius** [comment]
I've tested math functions in NASM and everything works now. Thank you!
