### ISSUE TITLE
Add webmock to Ruby 2.5

### ISSUE THREAD

**Issue by SaladFork** [Codewars/codewars-runner-cli#627]
The [Ruby environment documentation](https://github.com/Codewars/codewars-runner-cli/blob/master/documentation/environments/ruby.md) lists gems available for use in Kata. However, not all seem to be available when running MRI 2.5.0.

```rb
# MRI 2.3.0
require 'webmock'
p WebMock.version

# => "3.0.1"
```

```rb
# MRI 2.5.0
require 'webmock'
p WebMock.version

# => /usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -#    - webmock (LoadError)
#    	from /usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
#    	from main.rb:2:in `<main>'
```

**Comment by kazk** [comment]
I'll add webmock to 2.5 and let you know.

We've removed some gems that were never used from 2.3 and reduced the number of gems in 2.5.
More up to date documentation (which I just updated to include gems) is here: https://github.com/Codewars/codewars.com/wiki/Language-Ruby

**Comment by SaladFork** [comment]
Ah, awesome, thank you!

I had followed a link from the [documention](https://www.codewars.com/docs/programming-languages-and-environments). Is that page open source? I couldn't find it in this or the [codewars.com repo](https://github.com/Codewars/codewars.com) (figured I'd update the link to save you the trouble).

**Comment by kazk** [comment]
> Is that page open source?

No, it's part of Codewars app which is closed source.

Everything under https://www.codewars.com/docs is extremely outdated and we currently use [the wiki](https://github.com/Codewars/codewars.com/wiki) for documentation.
Sorry for the confusion.

**Comment by kazk** [comment]
Added `webmock` 3.4.2 to Ruby 2.5.
