### ISSUE TITLE
Ruby: remove 'nokogiri' gem and also disallow 'open-uri'

### ISSUE THREAD

**Issue by esotericpig** [Codewars/codewars-runner-cli#629]
The README says that this repo is obsolete. Should I post this issue in the codewars.com repo instead?

I solved this Kata first legitimately, but then, I noticed that the nokogiri gem is installed for some reason, so I made a hackier solution using google.com:

https://www.codewars.com/kata/reviews/51b66252ed2069c7c000000e/groups/5b352bdd85f945df56000f34

Actually, you don't need nokogiri at all, as you can just use open-uri by itself:

```ruby
#require 'nokogiri'
require 'open-uri'

class RomanNumerals
  def self.google(value,query)
    #doc = Nokogiri::HTML(open("https://www.google.com/search?q=#{value}+#{query}"),nil,'utf-8').to_s
    doc = open("https://www.google.com/search?q=#{value}+#{query}").read
    doc.slice(doc.index("#{value} = "),100).gsub(/\A.*=[[:space:]]+/,'').gsub(/\<.*\z/,'')
  end
  
  def self.to_roman(num)
    google(num,'to+roman+numerals')
  end
  
  def self.from_roman(roman)
    google(roman,'to+arabic').to_i
  end
end
```
Because I think no Kata should need nokogiri (or even open-uri), I think they should be disallowed. For nokogiri, this is very simple, just uninstall the gem. For open-uri, just disallow require/load of it, if possible.

**Comment by kazk** [comment]
This is a kata specific issue and should be posted on the kata discourse page. We don't control access to gems for each kata, authors should do that if needed.
