### ISSUE TITLE
Same tests but different results

### ISSUE THREAD

**Issue by Hajjjar** [Codewars/codewars-runner-cli#634]
Hey! So I am new to Codewars. And there's a problem I solved and tried to run, but it failed two tests. So I wrote a command line to print the array arguments that were tested to check what went wrong. And when I tested them myself, they actually worked, and then I realized that on Codewar there were two tests with the same method arguments but different results.  One test passed, the other failed. 

It was like this...
test1a
log: [2,2,3], [2,2,3] 
expected false but was true.

test10
log: [2,2,3], [2,2,3]
test passed

test1: 
log: [121, 144, 19, 161, 19, 144, 19, 11], [121, 144, 19, 161, 19, 144, 19, 11]
expected false but was true.

test2
log: [121, 144, 19, 161, 19, 144, 19, 11], [121, 144, 19, 161, 19, 144, 19, 11]
test passed

So is there a way to fix this? Thank you.

**Comment by kazk** [comment]
Please ask kata questions on its discourse page so the author and other users can help you. If the author thinks this is Codewars' issue, then they can open an issue here describing the situation.
