### ISSUE TITLE
Add Cobol Support

### ISSUE THREAD

**Issue by jandermannderkann** [codewars/codewars-runner-cli#635]
Hi, i recently started learning Cobol, because even so it is said to be a dead language, a lot of companies still use cobol code, and cobol-developers are very much needed. Therefore, i think it could be a great addition to the big CW-language pool. 
I would like to help in integrating, though i am rather busy with studying, and would consider myself only as a junior developer.

**Cobol resources:** 
- [Interpreter: gnucobol](https://sourceforge.net/projects/open-cobol/)
- [gnucobol Installguide & Requirenments](https://sourceforge.net/p/open-cobol/wiki/Install%20Guide/)

Cobol Testing Framework Inforamtion :

- [Wikipedia](https://de.wikipedia.org/wiki/Liste_von_Modultest-Software#COBOL)
- [Testing Framework on Github](https://github.com/neopragma/cobol-unit-test)

Thanks a lot in Advance! 

JanderMannderKann aka Tankman

---

- [x] Install
  - GnuCOBOL v2.2
- [x] Test with patched ZUT
- [x] CodeMirror mode
- [x] Icon

**Comment by kazk** [comment]
Deployed
