### ISSUE TITLE
Add PureScript Support

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars-runner-cli#638]
### Overview

A strongly, statically typed pure functional programming languages that evaluates eagerly and compiles directly to JavaScript with no additional runtime.

### Official Site

http://purescript.org

### Why add PureScript?

IMO it would be quite an interesting addition to Codewars as a somewhat similar yet distinct alternative to Haskell.  Its interoperability with plain JavaScript should also be quite interesting (though I'm not sure if that would be of any use on the CW platform).

### Any testing frameworks?

PureScript has its own implementation of [QuickCheck](https://github.com/purescript/purescript-quickcheck) provided by the maintainers of the language.  As for the custom CW output format, what was done for Haskell should be doable in PureScript as well.

### Special mention

Special mention to @CliffStamp for bringing up PureScript on the CW Gitter chat.

**Comment by kazk** [comment]
I'm using [pulp](https://github.com/purescript-contrib/pulp) build tool and package manager [psc-package](https://github.com/purescript/psc-package) so we can use `pulp test/run` and install packages in a reproducible way.

The only thing left is to write the reporter for `spec`. I'll assign myself for now and try to do it on my free time, but I'm not sure when. If anyone wants this soon and is interested to help, let me know.

**Comment by kazk** [comment]
The code runner side is finished so I'll try adding to Codewars soon. Maybe during next week if I'm not too busy.

**Comment by kazk** [comment]
PureScript is now available on Codewars
