### ISSUE TITLE
Error during assertion in the Rust version of the kata

### ISSUE THREAD

**Issue by alexnoz** [Codewars/codewars-runner-cli#641]
I'm getting this error while trying to submit my solution to the Rust version of [this kata](https://www.codewars.com/kata/remove-duplicate-words/train/rust).  Everything is ok with sample tests.
```
Time: 962ms Errors: 1 Exit Code: 101
STDERR:
error[E0433]: failed to resolve. Use of undeclared type or module `HashSet`
  --> src/lib.rs:18:19
   |
18 |     let mut set = HashSet::new();
   |                   ^^^^^^^ Use of undeclared type or module `HashSet`

error: aborting due to previous error


NOTE: Line numbers in error messages can be incorrect due to concatenation.
```

**Comment by kazk** [comment]
Please post kata issue on its discourse page. If the kata author thinks this is an issue of the service, they can open an issue here describing the situation.
I don't think this is an issue with our service because the sample tests work.
