### ISSUE TITLE
PHP error shows the incorrect line number for the error

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars-runner-cli#645]
e.g if I put this in the *first* line of user code:

```php
$a=1, $b=2;
```

This will result in an error because `,` cannot be used that way in PHP.

Clearly, the error is occurring at line 1. However the error message says this instead: `Parse error: syntax error, unexpected ',' in /home/codewarrior/run.php on line 4`. It's very hard to pinpoint where the error is as the given line number is not correct.

**Comment by kazk** [comment]
That's because of

https://github.com/Codewars/codewars-runner-cli/blob/d1c1d8bfb9919ee61d520370484894be27f48739/lib/runners/php.js#L50-L58

I'm trying my best to avoid concatenation for any new languages and new language versions.

**Comment by kazk** [comment]
Added PHP 7.4 that doesn't concatenate.

To use it, existing content must be updated. See https://github.com/codewars/codewars.com/wiki/List-of-PHP-Kata-to-Update-to-PHP-7.4
