### ISSUE TITLE
Add OCaml 4.07

### ISSUE THREAD

**Issue by kazk** [Codewars/codewars-runner-cli#646]
https://ocaml.org/releases/4.07.1.html

Original Request: https://github.com/Codewars/codewars.com/issues/1603

**Comment by abhi18av** [comment]
Thanks @kazk ! 👍

**Comment by kazk** [comment]
OCaml 4.07.1 is ready. I'll close this when it's deployed, sometime during next week.

**Comment by kazk** [comment]
Deployed. Existing OCaml kata seems to be compatible with 4.07 so I've made it available to them.
