### ISSUE TITLE
A Potentially Serious Security Issue with the Code Runner

### ISSUE THREAD

**Issue by Some-Dood** [Codewars/codewars-runner-cli#647]
Hello, there. I recently discovered something that seems pretty suspicious and dangerous when I ran my code in the editor (I was practicing my algorithm skills). I'm not sure how to disclose this because I've heard how sensitive these security issues are. Is there any way I could safely contact someone so I can describe this issue? I'm just uncertain about some behavior I have just witnessed. It's also easily reproducible which makes it worse.

Just a quick note, I have not done anything dangerous with this knowledge. I know how much damage this _may_ cause. In all honesty, I don't even want to continue investigating it. I just need to report it ASAP because, in all honesty, I really don't want to be fiddling with it.

**Comment by kazk** [comment]
Thanks. Please email me at kaz at qualified.io
