### ISSUE TITLE
In Java, preloaded code is run instead of submitted solution

### ISSUE THREAD

**Issue by hobovsky** [Codewars/codewars-runner-cli#651]
#### Describe the bug

In this kata: https://www.codewars.com/kumite/5be26955d9b25c923b0000eb?sel=5be26955d9b25c923b0000eb , translator (unintentionally, I presume) put the same code in Solution and in Preloaded sections. As a result, preloaded code seems to overwrite user solution completely, and tests are run against preloaded code. Submitted solution **does not even have to compile** (see my accepted solutions), although it must follow some format (class definition seems to be necessary, but other code might be just gibberish). 
I think that once similar thing happened to me, and I mixed up a Preloaded and Solution edit windows when authoring one of my katas. Maybe these two could be made more distinct?

#### To Reproduce

Create a Java translation, and put exact copy of reference solution into preloaded section.

#### Expected Behavior

Tests should be run against submitted solution, and not a preloaded code. Or maybe kata editor or  runner should raise an error?

#### Screenshots

Kata contents (fork view):

![image](https://user-images.githubusercontent.com/23709795/48161898-00dd8480-e2dc-11e8-9a1c-da38bca1a371.png)
![image](https://user-images.githubusercontent.com/23709795/48161929-0e930a00-e2dc-11e8-9b01-afed616d85ce.png)

Some invalid solutions:

![image](https://user-images.githubusercontent.com/23709795/48161993-3d10e500-e2dc-11e8-922a-ecb11a9f3eaa.png)

**Comment by kazk** [comment]
This happened because both solution and preloaded was written to `java/src/Solution.java` (solution was overwritten by preloaded).
The file name is derived from the code and some languages checks for this user error, but looks like Java doesn't.

**Comment by kazk** [comment]
This is fixed. The code runner rejects the request (with status 422) when file names are in conflict. The output confusingly suggests to retry, but that's a separate issue.
