### ISSUE TITLE
C++ testing framework hides spaces when comparing strings

### ISSUE THREAD

**Issue by Chrono79** [Codewars/codewars-runner-cli#652]
#### Describe the bug

C++ testing framework hides spaces when comparing strings, an so, the user doesn't know what's wrong when the expected and actual result don't match.

#### To Reproduce

You can see it in this kata for example returning `"HEY JUDE "` with a trailing space.
https://www.codewars.com/kata/decode-the-morse-code/train/cpp

#### Expected Behavior

I would suggest adding quotes when showing the actual and expected values like it's done in other languages

#### Screenshots

![image](https://user-images.githubusercontent.com/9571508/48167873-edc2b880-e2cb-11e8-8573-c9ee790e96d9.png)

**Comment by error256** [comment]
Many other types don't even have a built-in stringizer, but you can define custom stringizers in the tests:
https://www.codewars.com/kumite/5adc69f12f10c6a29c00001c?sel=5adc6c7102db61acf100003a
Or full hardcore:
https://www.codewars.com/kumite/575c405252875e7c920003f7?sel=5abbd780f675d1047700000d

**Comment by kazk** [comment]
Closing as wontfix because this seems like Igloo's limitation (you need to define ways to stringify). And @error256 showed ways to do it.

Igloo has lots of other issues as well and I'd like to eventually replace it with Catch2 (see #658).
