### ISSUE TITLE
Haskell: `quickCheck`/`quickCheckWith` does not work anymore and `withMaxSuccess` is missing in GHC 7.10.3

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#653]
I recently found that the kata test setup that I was using for Haskell katas are not working anymore:

```haskell
    describe "Random tests" $ do
      it "Should pass 50 random tests" $ quickCheckWith stdArgs { maxSuccess = 50 } $ do
        forAll (choose (2,999999)) $ \ n -> do
          userSolution n `shouldBe` refSolution n
```

because apparently since the Haskell 8 upgrade `quickCheck`/`quickCheckWith` is not using the CW formatter, and so failed tests does not cause an actual test failure.

Now this works in Haskell 8 version:
```haskell
    describe "Random tests" $ do
      it "Should pass 50 random tests" $ withMaxSuccess 50 $ do
        forAll (choose (2,999999)) $ \ n -> do
          userSolution n `shouldBe` refSolution n
```

But not in GHC 7.10.3 because apparently `withMaxSuccess ` does not exist, even after `import Test.QuickCheck`.

So currently there is no way to specify the amount of random tests while keeping GHC 7.10.3 version (I don't want to change the tests to GHC 8 because of how GHC 8 tests are structured).

Also, is calling `quickCheck`/`quickCheckWith` directly not using CW formatting intended in the first place? It wasn't like this before the GHC 8 upgrade.

**Comment by kazk** [comment]
> (I don't want to change the tests to GHC 8 because of how GHC 8 tests are structured).

Can you elaborate?

**Comment by kazk** [comment]
> Also, is calling `quickCheck`/`quickCheckWith` directly not using CW formatting intended in the first place? It wasn't like this before the GHC 8 upgrade.

I'm actually surprised it was working because those writes directly to stdout. Can you show me one with it?

**Comment by kazk** [comment]
`modifyMaxSize` should be available on GHC 7.10.3 version and should work as long as the custom wrapper isn't doing anything that I'm not aware of.

**Comment by kazk** [comment]
Sorry, I meant `modifyMaxSuccess`. That should also exist in both versions and that should be used when using QuickCheck with Hspec.

**Comment by kazk** [comment]
Also, from Gitter:

> another problem I have with current 8.2 setup: why the hell do I need one and only one spec defined?

GHC 7 version had single entry point `main`. Why is this a problem now? `main = hspec spec`. You can have multiple groups of tests under it as before.

**Comment by kazk** [comment]
Closing as invalid.

- `quickCheck`/`quickCheckWith` shouldn't work because it writes to stdout directly. Please open a new issue if it does with links to kata with them.
- Use functions provided by Hspec for QuickCheck integration instead.

**Comment by kazk** [comment]
Also, if the above comment didn't clarify, please explain the issue with single `spec` by opening a new issue. As far as I know, there's no significant difference between the GHC 7 style

```haskell
main = hspec $ do
  describe "tests" $ do
    -- ...
```
and
```haskell
spec = do
  describe "tests" $ do
    -- ...

main = hspec spec -- `main` is optional in GHC 8
```

**Comment by Voileexperiments** [comment]
@kazk [Almost all Haskell katas](https://github.com/codewars/codewars.com/wiki/List-of-Haskell-Kata-to-Update) has been updated to ghc 8.x, with a few exceptional cases that can't be fixed yet. Though I think you need to do the following things:

1. Double-check any katas which is still ghc 7.x only since when I double-check some of the katas they were removed from the list but did not have ghc 8.x enabled, aka some katas might be slipping off the net
2. Search for any test suites with string `quickCheck`/`quickCheckWith` (case sensitive) because I do recall there are a few katas using that
3. Search for usages of `System.Random` (aka searching for the string `import System.Random`) in test suites and preferably migrate them to `Test.QuickCheck` (though this is not at a very high priority)
