### ISSUE TITLE
`quickCheck`/`quickCheckWith` does not work anymore

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#654]
From #653:

> I'm actually surprised it was working because those writes directly to stdout. Can you post a link to a kata with it?

At least these 2:

- https://www.codewars.com/kata/integer-to-nested-structure
- https://www.codewars.com/kata/one-line-task-how-many-digits

There should be a few more, but I can't remember those ones anymore.

**Comment by kazk** [comment]
Yeah, those are not working as expected. Try incorrect submitting incorrect solution after removing fixed tests.

![image](https://user-images.githubusercontent.com/639336/48319759-c10dea00-e5c6-11e8-92cf-82a01cf7fdd4.png)

**Comment by kazk** [comment]
This is expected behavior and it's been like this from the beginning. `quickCheck`/`quickCheckWith` is independent, writes the result to stdout and Hspec doesn't know about it. You need to use Hspec's QuickCheck integration.

**Comment by Voileexperiments** [comment]
> it's been like this from the beginning

Yeah, but the point is, they used to work. That is why I've been using it.

**Comment by kazk** [comment]
It *appears* to work, but it doesn't.
GHC 7.10 one hasn't changed (Hspec version and command line arguments have been exactly the same). It doesn't share anything with GHC 8 version.

**Comment by kazk** [comment]
Also, this has nothing to do with us. `quickCheck`/`quickCheckWith` always wrote to stdout and Hspec was never able to use that in the formatter.
