### ISSUE TITLE
Use `Promise.race` to perform test timeout detection in JS easily

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars-runner-cli#661]
Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race

Currently it is done by a very hacky way that I don't really understand just by glancing over the code in `cw-2.js`. Certainly it can use some improvement.

When `Promise.race` is used timeout detection is as easy as running the test fixture Promise along with another Promise that rejects with an error after a timeout period.

It's also available since Node 0.12.

**Comment by kazk** [comment]
Mocha allows setting timeout per test case so deprecating cw-2 should resolve this.

If you're talking about 12s timeout then that's handled by just killing the container.
