### ISSUE TITLE
JS: No way to disable explain in test assertion

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars-runner-cli#665]
Any test fixture with massive expected/actual values will break the tests as there are no way to disable explain, aka showing the expected/actual values.

That is, unless we abandon the use of `Test.assertDeepEquals` and the likes and do the value comparison before using `Test.expect` to make a test assertion ourselves. This leads to very bad things.

That is, we have to do this *in the very least*:

```javascript
Test.assertEquals(0,1,'Test failed',{successMsg: 'Test passed'});
```

And we'd still get the expected/actual values in failed tests, and `Test passed: Test passed` in the actual tests.

(Speaking of which, appending the success message after `Test passed` is a bad idea too: if I'm supplying a custom success message, of course I'm expecting it to completely override the entire success message, not being appended after a `Test passed: `).

**Comment by kazk** [comment]
This will be resolved by deprecating cw-2 in Node 10. Older versions will stay as is for compatibility until the language version is deprecated in the future.
