### ISSUE TITLE
Add Lua 5.3

### ISSUE THREAD

**Issue by SavageHolycow** [Codewars/codewars-runner-cli#666]
- Name: Lua
- Version: 5.3
- Release Note/Changelog: Integers, Bitwise operators, A basic utf-8 library
---
Quite a few Katas require the utf-8 library. A 5.3 version upgrade is mandatory now.

**Comment by kazk** [comment]
Added Lua 5.3 support. I'll close this when it's deployed, maybe sometime during next week.

**Comment by SavageHolycow** [comment]
Alrightyyy <3

**Comment by kazk** [comment]
Deployed. All kata should have Lua 5.3 as default now.
