### ISSUE TITLE
Python: add pypi 'regex' module in addition to the 're'

### ISSUE THREAD

**Issue by sgerodes** [Codewars/codewars-runner-cli#672]
Please add the [pypi regex module](https://pypi.org/project/regex/) for advanced regex usege.

I am constructing the "RegEx Like a Boss" katas. I am missing the maintenance of **subroutines** and **recursion** for some new Ideas. The 're' module is really weak.

**Comment by sgerodes** [comment]
Sorry for the branch mess... First time branching directly on github. Only the last one is relevant

**Comment by kazk** [comment]
Added regex 2018.11.22
