### ISSUE TITLE
[PureScript] Add module `Undefined` as dependency

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars-runner-cli#676]
Unlike Haskell, PureScript does not have a polymorphic `undefined` value by default and enforces totality so it may be impossible to provide an initial solution that compiles in certain cases without resorting to ugly hacks such as `Unsafe.Coerce.unsafeCoerce Prelude.unit`.  However, a handy module `Undefined` ([source](https://github.com/bklaric/purescript-undefined)) with a value `undefined` has been made available in PureScript since April 2018 which does not appear to be available on Codewars.  Please consider adding it as a dependency, thanks :smile:

**Comment by kazk** [comment]
We use [psc-package](https://github.com/purescript/psc-package) so a package needs to be the one in [package-sets](https://github.com/purescript/package-sets). `purescript-undefined` doesn't seem to be.

Is this package commonly used? It also needs to be compatible with `0.12` (May 2018).

See these issues and documentation

- https://github.com/purescript/documentation/blob/master/language/Differences-from-Haskell.md#error-and-undefined
- https://github.com/purescript/purescript-prelude/issues/44
- https://github.com/purescript/purescript/issues/1283

**Comment by kazk** [comment]
Maybe updating to `v0.12.2` will help. It supports named type wildcards `?hole`.

**Comment by kazk** [comment]
I might be wrong, but the package you're suggesting won't behave like Haskell's `undefined`. I think it will just give a runtime type error that it's not a function. And it's confusing because it'll be in JavaScript syntax.

---

I think `?undefined` (or name that's more appropriate) is good enough.

## PureScript

```purescript
countSheep :: Int -> String
countSheep = ?undefined
```
won't compile and shows

```
Error found:
in module CountSheep
at src/CountSheep.purs line 9, column 14 - line 9, column 14

  Hole 'undefined' has the inferred type

    Int -> String

  You could substitute the hole with one of these values:

    CountSheep.countSheep  :: Int -> String


in value declaration countSheep
```

(I can see this can be annoying for more complex kata though)

## Haskell

```haskell
countSheep :: Int -> String
countSheep = undefined
```
will compile, but the error is
```
ErrorCall (Prelude.undefined
CallStack (from HasCallStack):
  error, called at libraries/base/GHC/Err.hs:79:14 in base:GHC.Err
  undefined, called at src/CountSheep.hs:4:14 in main:CountSheep)
```

**Comment by DonaldKellett** [comment]
Good point - typed holes should provide a clearer error message than `TypeError: CountSheep.countSheep is not a function` (which is what happens when `undefined = unsafeCoerce unit` is used) which is arguably even less readable than a compilation error message.  Naming it `?todo` should get the message across to beginners that the code would compile once the hole is replaced with a sensible solution implementation.
