### ISSUE TITLE
Add ReasonML

### ISSUE THREAD

**Issue by kamilkuz** [Codewars/codewars-runner-cli#686]
Hello, I suggest to add language ReasonML. It's quite new but very promising and is becoming more and more popular.
Now, the most popular use is for web application (can be compile to javascript).

- Name: ReasonML
- Website: https://reasonml.github.io/en/
- Language Version: newest :)

**Comment by ZielonyBuszmen** [comment]
This is good idea! I sugest to add this language too.

**Comment by kazk** [comment]
I think we can use [Jest wrapper](https://github.com/glennsl/bs-jest) for testing. If I'm understanding correctly, it'll output tests in JS and regular Jest can be used to run them.

**Comment by kamilkuz** [comment]
I think yes, I use it exactly the way you wrote.

**Comment by kazk** [comment]
I got it working with the latest `bs-platform` and `bs-jest`. I'm assuming latest ReasonML is [v3.0.4](https://github.com/facebook/reason/releases/tag/3.0.4) and it's being used.

It'll look something like
```ocaml
let add = (a, b) => a + b;
```
```ocaml
open Jest;

describe("add", () => {
  open Expect;

  test("1 + 1", () =>
    expect(Solution.add(1, 1)) |> toBe(2));
});
```

Solution will be always put in `Solution` module (`src/Solution.re`) because Codewars doesn't allow specifying file names.

**Comment by kamilkuz** [comment]
@kazk 
It's great. When can we expect Reason will be available in codewars.com ?

**Comment by kazk** [comment]
Maybe next week. I'm doing this on my own time after work so I don't know how much time I can spend.

I'd say it's 95% complete because code runner is done. I just need to update Codewars to let it know about Reason. I still need to find an icon though.

**Comment by kazk** [comment]
Reason is now available on Codewars!

Currently there's only [Multiply](https://www.codewars.com/kata/multiply/reason).
Please try it, help translate existing kata, and let me know if you find any issues.

**Comment by kamilkuz** [comment]
@kazk 
It's greate ! I tried it and for now seems to work fine ! 
I will translate some kate in my free time.
Thanks :)
