### ISSUE TITLE
Add BigInteger libraries to PureScript

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars-runner-cli#688]
Some libraries with arbitrary-precision integers in PureScript:

- [purescript-bigints](https://pursuit.purescript.org/packages/purescript-bigints/4.0.0) - Its `BigInt` supports all the key integer operations (`+`, `-`, `*`, `div`, `mod`, etc.) due to `EuclideanRing` instance
- [purescript-precise](https://pursuit.purescript.org/packages/purescript-precise/3.0.1) - Its `HugeInt` supports addition, multiplication and subtraction but unfortunately doesn't seem to support division (due to lack of `EuclideanRing` instance).  Also contains `HugeNum`

Adding them to CW would hopefully put PureScript (almost) on par with Haskell in terms of arbitrary-precision integer support (minus BigInteger literal support, e.g. `9873489723894327894237498273489237498237423984`).

**Comment by kazk** [comment]
I'll add `purescript-bigints`. `purescript-precise` is not in [package-sets](https://github.com/purescript/package-sets).

I'll also add #689 and update PureScript to the latest [v0.12.2](https://github.com/purescript/purescript/releases/tag/v0.12.2).

**Comment by kazk** [comment]
Added `bigints` and updated PureScript to latest
