### ISSUE TITLE
Add purescript-rationals to PureScript

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars-runner-cli#689]
[purescript-rationals](https://pursuit.purescript.org/packages/purescript-rationals/5.0.0) is the PureScript version of [`Data.Ratio`](http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Ratio.html) in Haskell.  In fact, one of its modules is called `Data.Ratio` (the other being `Data.Rational`).  Including this package should make PureScript on par with Haskell in this regard.

**Comment by kazk** [comment]
Added `rationals`
