### ISSUE TITLE
Implement Test.CodeWars.BlackList for Haskell 8

### ISSUE THREAD

**Issue by Bubbler-4** [Codewars/codewars-runner-cli#691]
Name: Test.CodeWars.BlackList
Language Name: Haskell 8
Website: [Within codewars-runner-cli repo](https://github.com/Codewars/codewars-runner-cli/blob/master/frameworks/haskell/Test/CodeWars/BlackList.hs)

### Why?

For library re-implementation challenges, e.g. transpose or fold or whatever, the `hidden` feature is necessary to stop people import that exact thing. Unfortunately, its access is limited to legacy Haskell (v7), so any kata that has a `hidden` test is stuck to v7 and therefore out of future support. (Not that writing a new kata that requires `hidden` is a good idea in the first place...)

### Is it possible?

Looking at its imports, simply having that file alongside the solution/test.hs files should enable `import Test.CodeWars.BlackList`, unless there's some insanity in `Language.Haskell.Exts.*`.

**Comment by kazk** [comment]
`Language.Haskell.Exts.Annotated` doesn't seem to exist anymore.

https://github.com/Codewars/codewars-runner-cli/blob/a07114084838a002c53d512f6502996ba81d9ed7/frameworks/haskell/Test/CodeWars/BlackList.hs#L3

I think we just need to use [Language.Haskell.Exts.Parser](https://www.stackage.org/haddock/lts-10.4/haskell-src-exts-1.19.1/Language-Haskell-Exts-Parser.html) instead.

---

I'll see if I can make it work, but if not, I guess I can add [haskell-src-exts](https://www.stackage.org/lts-10.4/package/haskell-src-exts-1.19.1) and let the community come up with something usable based on that, then extract that into a new module that can be included.

**Comment by Bubbler-4** [comment]
That's a bad news (that there *is* some insanity). Can you add `haskell-src-exts` first? That will allow others to do interesting source code analysis other than just `hidden` (I have no idea right now though). Also, working it out within CW (say, kumite) is easier (IMO) to develop something compatible with CW.

**Comment by kazk** [comment]
Yeah, I started reading the documentation and it seemed to have changed a lot. I can't find the replacement for `import Language.Haskell.Exts.Annotated.Simplify (sModule)` for example.

I'll add `haskell-src-exts` and make this a community project.

Solution can be read from `/workspace/solution.txt` instead of using the environment variable.

I'll let you know when it's deployed.

**Comment by DonaldKellett** [comment]
Idk if this is a bit of a stretch but would it be reasonable for me to request something similar to `Test.Codewars.BlackList` in PureScript?  Currently, quite a few Haskell kata aren't suitable for translation into PureScript (e.g. "The Five Fundamental Monads", "foldMap all the things") because they require certain built-ins to be hidden and AFAIK there is no module/library in PureScript for writing such tests.  Or are such Kata (requiring certain built-ins to be hidden) highly discouraged and only kept as legacy content?

**Comment by kazk** [comment]
@DonaldKellett can you open a new issue for it? We can discuss more there. I'd consider it if we can come up with something maintainable.

**Comment by kazk** [comment]
Added `haskell-src-exts` to Haskell 8

**Comment by Bubbler-4** [comment]
Tried a few things, and it seems to be straightforward.

Given the source code

```haskell
module Example where

import Prelude hiding (Bool(..), head, (/))
import Data.Maybe
import qualified Data.Map as Map
import Data.Map (Map(..), fromList)
```

the import list from the result of `parseFile "solution.txt"` looks like (formatting by me, every `()` part is where source annotations would go):

```haskell
[
  ImportDecl {
    importAnn = (),
    importModule = ModuleName () "Prelude",
    importQualified = False, importSrc = False, importSafe = False,
    importPkg = Nothing, importAs = Nothing,
    importSpecs = Just (
      ImportSpecList () True [
        IThingAll () (Ident () "Bool"),
        IVar () (Ident () "head"),
        IVar () (Symbol () "/")
      ]
    )
  },
  ImportDecl {
    importAnn = (),
    importModule = ModuleName () "Data.Maybe",
    importQualified = False, importSrc = False, importSafe = False,
    importPkg = Nothing, importAs = Nothing, importSpecs = Nothing
  },
  ImportDecl {
    importAnn = (),
    importModule = ModuleName () "Data.Map",
    importQualified = True, importSrc = False, importSafe = False,
    importPkg = Nothing, importAs = Just (ModuleName () "Map"), importSpecs = Nothing
  },
  ImportDecl {
    importAnn = (),
    importModule = ModuleName () "Data.Map",
    importQualified = False, importSrc = False, importSafe = False,
    importPkg = Nothing, importAs = Nothing,
    importSpecs = Just (
      ImportSpecList () False [
        IThingAll () (Ident () "Map"),
        IVar () (Ident () "fromList")
      ]
    )
  }
]
```

[Related kumite](https://www.codewars.com/kumite/5c5c74f49d76d45523b4ec8a?sel=5c5c74f49d76d45523b4ec8a).

The relevant parts for `hidden` seem to be `importModule` and `importSpecs`:

* If `importSpecs == Nothing`, the `importModule` is imported as a whole.
* If `importSpecs` matches `Just (ImportSpecList _ False xs)`, the identifiers in `xs` are imported.
* If `importSpecs` matches `Just (ImportSpecList _ True xs)`, the identifiers in `xs` are hidden using `hiding`.

**Comment by Bubbler-4** [comment]
Ok, [finished writing `hidden` close enough to be usable](https://www.codewars.com/kumite/5c5c74f49d76d45523b4ec8a?sel=5c5c74f49d76d45523b4ec8a), except that it doesn't accept single item yet.

**Comment by kazk** [comment]
@Bubbler-4 Looks great!

I don't think we need to be 100% compatible (unless we really need to keep GHC 7.10 compatibility for some reason) so we can have separate functions if that makes sense.

Maybe we can create `Test.Hspec.Codewars` to provide various utility functions for testing on Codewars like [Test.Hspec.Megaparsec](https://hackage.haskell.org/package/hspec-megaparsec-2.0.0/docs/Test-Hspec-Megaparsec.html).

We can also name the function to match other assertions. Something like `shouldNotUseModule`, `shouldHaveHiddenImport`, etc?

**Comment by Bubbler-4** [comment]
That module name is a good idea.

I think `should*` implies that the function is designed for infix usage, so I guess we can expose a black-box object that represents solution's imports, and have a use case like

```haskell
solutionImports `shouldHide` Module "Data.List"
solutionImports `shouldHide` FromModule "Data.List" "tail"
```

or, probably better:

```haskell
solutionShouldHide $ Module "Data.List"
solutionShouldHide $ FromModule "Data.List" "tail"
solutionShouldHideAll [Module "Data.List", Module "Data.Set", Module "Data.Map"]
```

---

Just for reminder, there's one more must-have for `Test.Hspec.Codewars` - `shouldApproxEqual`.

**Comment by kazk** [comment]
Yeah, I like `solutionShouldHide` and `solutionShouldHideAll` :+1:

---

For `shouldApproxEqual`, I added [HUnit-approx](https://www.stackage.org/lts-10.4/package/HUnit-approx-1.1.1.1) because it was [requested](https://github.com/Codewars/codewars.com/issues/1587), but I haven't actually tried using it.

**Comment by Bubbler-4** [comment]
Well, I already made a [complete module](https://www.codewars.com/kumite/5c5cabb78dac194b19d61072?sel=5c5cabb78dac194b19d61072) including approx assertions (with descriptive failure messages), so you don't need HUnit-approx (which is IMO somewhat obscure in terms of epsilon).

**Comment by kazk** [comment]
@Bubbler-4 Looks great!

I'll make a repository under Codewars org. Maybe https://github.com/Codewars/hspec-codewars . So you can open a PR and we can maintain this.

**Comment by Bubbler-4** [comment]
PR submitted.

Codewars is just perfect for slacking at work (just kidding :)

**Comment by kazk** [comment]
`Test.Hspec.Codewars` is now available to every kata. Thanks again for doing this.
