### ISSUE TITLE
[PureScript] JavaScript module `big-integer` not found

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars-runner-cli#694]
`Data.BigInt` from `purescript-bigints` can now be imported into PureScript modules on Codewars but it seems that its corresponding JavaScript dependency [`big-integer`](https://www.npmjs.com/package/big-integer) is not yet available, leading to a runtime JavaScript error.

The screenshot below illustrates the issue and the related Kumite can be found in https://www.codewars.com/kumite/5c56d5cef6e4fc6caf1d900e?sel=5c5ea61ae5dc6c634c369f7e

![2019-02-09 18 07 02](https://user-images.githubusercontent.com/7777884/52519425-1cb74480-2c96-11e9-9b71-fb770aec186c.png)

**Comment by kazk** [comment]
Deployed the fix
