### ISSUE TITLE
Groovy 2.5.x

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars-runner-cli#697]
Please add or update the Groovy version to 2.5.5.

**Comment by kazk** [comment]
I'll add Groovy 2.5.6. We'll see if existing content works with 2.5 and remove 2.4 once it's unnecessary.

**Comment by kazk** [comment]
Groovy 2.5 is now available. I'm planning to run a script to update compatible kata, but not today.
Play with it and let me know if you find any issues.

**Comment by suic86** [comment]
@kazk there are not that many backwards incompatible changes, so I expected that there won't be issue with kata. However, when I tried to republish [this kata](https://www.codewars.com/kata/5b7c80094a6aca207000004d) with Groovy version, I got the annoying "Default Version is not a supported version" message. I remember that it was similar with Python 2.x vs. 3.x in the past.

**Comment by kazk** [comment]
@suic86 Sorry about that. Some parts of Codewars are still unclear to me :( What happens if you validate with 2.5 and republish?

**Comment by suic86** [comment]
@kazk no problem. Apparently, it requires some testing :) I've checked this with three other katas with the same result. I do the following:

1. Open kata in editor
2. Change language to Groovy 2.5
3. Validate and publish

The publishing takes quite a while and then it fails with "Default Version is not a supported version".

**Comment by kazk** [comment]
@suic86 OK, I figured out what's going on.

This happens when a new language version is set to the default language version without any code change. For some reason, Codewars doesn't add the new language version to the list of supported language versions of the kata when nothing else is changed. So it fails with `"Default Version is not a supported version".` when validating the data.

Until I run the script to update compatible kata or fix this weird bug, you can enable 2.5 by changing some code (e.g., adding empty line) and republishing. [Hungarian Vowel Harmony (easy)](https://www.codewars.com/kata/hungarian-vowel-harmony-easy/groovy) has Groovy 2.5 now.

**Comment by suic86** [comment]
@kazk thanks for explanation. This behavior seems to be buggy. :)

**Comment by kazk** [comment]
I know, I'll see if I can figure out where this comes from. Codewars is full of things like this.

**Comment by kazk** [comment]
@suic86 I ran a script to update compatible ones to use Groovy 2.5. So most of them can use 2.5 now.

These were not compatible with 2.5. Can you look into what's wrong if you've completed them already and update them?

- [Calendar Week](https://www.codewars.com/kata/5c2bedd7eb9aa95abe14d0ed/groovy)
- [Is the date today](https://www.codewars.com/kata/563c13853b07a8f17c000022/groovy)
- [Molecule to atoms](https://www.codewars.com/kata/52f831fa9d332c6591000511/groovy)
- [Piano Kata, Part 2](https://www.codewars.com/kata/589631d24a7323d18d00016f/groovy)
- [To BrainFuck Transpiler](https://www.codewars.com/kata/59f9cad032b8b91e12000035/groovy)

**Comment by suic86** [comment]
@kazk: The problem with the first two is explained [in Breaking Changes for 2.5.0](http://www.groovy-lang.org/releasenotes/groovy-2.5.html):

> The extension methods for the java.util.Date class are now in a separate groovy-dateutil module which isn’t included by default when using the groovy-all pom dependency.

I've used 2.5.6 with Java 9 for Calendar Week translation and I didn't experience any issues but with Java 8 used on CW I was able to reproduce the issue locally. This one I fixed today but a better solution would be install `groovy-all` as it's suggested in the release notes.

**Comment by kazk** [comment]
Thanks, I'll add `org.codehaus.groovy:groovy-dateutil:2.5.6` then.

**Comment by kazk** [comment]
Added `org.codehaus.groovy:groovy-dateutil:2.5.6`
