### ISSUE TITLE
@Test.timeout decorator in python doesn't behave correctly anymore

### ISSUE THREAD

**Issue by Blind4Basics** [Codewars/codewars-runner-cli#698]
#### Describe the bug

Known fact: the decorator was tricky to use, but I had found a way and [documented it in the wiki](https://github.com/Codewars/codewars.com/wiki/Codewars-Python-Test-Framework-V2#timeout-utility) about the test framework.

* known problem: if the call to the function of the user was done inside the decorator, he could raise an issue to stop the tests, then the decorator was swallowing the exception (thrown in another thread than the one of the test suite, so didn't trigger the failure of the test suite itself, iirc).
* previous solution: like I documented it, using an intermediate function so that the call to the function of the user is in the current thread all the same.
* current problem: that doesn't work anymore...:

#### To Reproduce

See [this fork](https://www.codewars.com/kumite/5c654b161fb6854a4c17a90b?sel=5c654b6dd157454b217da31e) of anter69's solution to my "Ulam sequence" kata. I tried different things but only get the printing of the stack trace, the test suite is never crashing.
(edit: btw, there is something weird about the performances: I couldn't make my own solution to pass unless I lowered by 25% the load of the perf tests... x/. Tho that was valide before... That's unrelated to the current problem, tho. Just a note...)

#### Expected Behavior

Any exception thrown by the user or his code should interrupt the test with an actual failure.

#### Screenshot

![image](https://user-images.githubusercontent.com/32236948/52784187-8fd50800-3054-11e9-9845-a43c624e9721.png)

**Comment by kazk** [comment]
I don't understand the "anymore" part. I haven't changed anything.

@Bubbler-4 any idea what's going on?

**Comment by Bubbler-4** [comment]
No idea either. I didn't know about throwing errors in threads when I wrote it.

On the other hand, I found [this SO answer](https://stackoverflow.com/questions/19924104/python-multiprocessing-handling-child-errors-in-parent) to reraise child's exceptions in the parent. We can start working from there, though it sounds like a lot of work. Or, we can study and use [pathos](https://github.com/uqfoundation/pathos) which is mentioned in a comment there.

**Comment by Blind4Basics** [comment]
errr... "solitude" just posted that code as a fork. Is that actually one of you? x)

ok, that effectively works, even if it's absolutely unusable for the average user, I'd say... :/

Would it be possible to make that internal to the timeout decorator in some way? I fear not, because this hack is still subject to the original problem. For instance:

This one is catching the exception raise in the code correctly:

```python
def doTests(nTests, n):
    a = range(1,100)
    for i in range(nTests):
        ...
        expect_no_error(
            'Should not raise exceptions',
            lambda: test.assert_equals(ulam_sequence(u0, u1, n), expected)
        )
        
caller = lambda: doTests(20, 1500)

@Test.describe('Random tests')
def rnd():
    
    @Test.it('Small sequences')
    def smalls(): doTests(20, rand(10,31))
    
    @Test.it('Large sequences')
    def bigs(): 
        @Test.timeout(11)
        def withTimer(): caller()
```

but this one doesn't anymore:

```python
def doTests(nTests, n):
    a = range(1,100)
    for i in range(nTests):
        ...
        expect_no_error(
            'Should not raise exceptions',
            lambda: test.assert_equals(ulam_sequence(u0, u1, n), expected)
        )
        
#caller = lambda: doTests(20, 1500)

@Test.describe('Random tests')
def rnd():
    
    @Test.it('Small sequences')
    def smalls(): doTests(20, rand(10,31))
    
    @Test.it('Large sequences')
    def bigs(): 
        @Test.timeout(11)
        def withTimer(): doTest(20,1500)      #<<<<<
```

**Comment by Bubbler-4** [comment]
You made a typo in the second code block (`doTest` should be `doTests`), and [it indeed works as it should](https://www.codewars.com/kumite/5c654b161fb6854a4c17a90b?sel=5c65eaa1f1adc5313fedff2f) (`doTests` is already in our scope).

And... yes, solitude is my Haskellish self, though it's invading many other areas these days. Sorry if you feel bad about it.

**Comment by Blind4Basics** [comment]
x/

what the hell... Sorry... :/

**Comment by Bubbler-4** [comment]
In order to avoid the hacks, I think this could work (given that we already have `expect_no_error`):

```python
def timeout(limit):
    ...
    def wrapper(func):
        ...
        def child_process():
            expect_no_error('Should not raise exceptions', func)
        ...
```

Thinking about the use cases involving exceptions, you don't usually want to raise specific exceptions when you write a performance kata, and for `GeneratorExit`, you normally handle it by simple iterable protocol. So catching `BaseException` so nothing can leak would be the way to go here.

**Comment by kazk** [comment]
@Bubbler-4 Created https://github.com/Codewars/python-test-framework with current cw-2.py so you can fork it and open PR with changes.

**Comment by Bubbler-4** [comment]
PR submitted. Anyone interested can see the [demo kumite](https://www.codewars.com/kumite/5c654b161fb6854a4c17a90b?sel=5c6642e0f1e5471a3f626439).

**Comment by kazk** [comment]
I'll let you guys know when this is deployed.

**Comment by kazk** [comment]
Deployed. Thanks @Bubbler-4 for the fix.
