### ISSUE TITLE
Compiler flags for Haskell

### ISSUE THREAD

**Issue by Bubbler-4** [Codewars/codewars-runner-cli#699]
A couple of days ago, I tried giving `-O` GHC option in CW kumite like this:

```haskell
{-# OPTIONS_GHC -O #-}
```

But the compiler rejected it, saying that `-O` is ignored because `--interactive` is on. (I used it in Preloaded section, and didn't check other sections yet.)

The `--interactive` flag is usually just for running `ghci` and (if I'm understanding the [GHC docs](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/flags.html) correctly) not for use in compiled programs. That's pretty lame because GHC's optimization is really good if enabled (it's sometimes said that Haskell is almost on par with C/C++ about performance, at least if properly coded) but we're totally throwing it away and dragging it down to that of common interpreted languages.

That said, can you show us the current GHC command-line options for v8? Let's see what we can change to make it better.

**Comment by kazk** [comment]
> That said, can you show us the current GHC command-line options for v8? Let's see what we can change to make it better.

`stack runghc -- -i/path/to/include:src:test test/Main.hs`

`test/Main.hs`

```haskell
module Main where

import Test.Hspec.Runner
import Test.Hspec.Formatters.Qualified (codewars)

import qualified Spec

main :: IO ()
main = hspecWith defaultConfig {configFormatter = Just codewars} Spec.spec
```

`test/Spec.hs`

```haskell
{-# OPTIONS_GHC -F -pgmF hspec-discover -optF --module-name=Spec #-}
```

**Comment by Bubbler-4** [comment]
`runghc` seems to assume `--interactive`, and there's no way to fix it easily. I guess `ghc --make` then running the output file is the way to go - something close to how to run a C project in CW.

For `-i/path/to/include:src:test`, `-isrc:test` should work unless you really have a dependency in `/path/to/include` literally.

Here's what I use in my own project (I don't use stack):

```bash
ghc --make -isrc:test test/Spec.hs -o out/Spec
out/Spec
```

Given that you do use stack and a separate Main, something like this would fit the needs:

```bash
stack ghc -- --make -isrc:test test/Main.hs -o a.out && a.out
```

I don't think we should actually include any fancy flags on the script, as anyone (be a kata author or solver) can include any flags via `OPTIONS_GHC` to fit their needs.

**Comment by kazk** [comment]
> For `-i/path/to/include:src:test`, `-isrc:test` should work unless you really have a dependency in `/path/to/include` literally.

It includes the folder where the formatter and `hspec-codewars` is. I just changed the actual path to `/path/to/include`.

> I don't think we should actually include any fancy flags on the script, as anyone (be a kata author or solver) can include any flags via `OPTIONS_GHC` to fit their needs.

I took them from Hspec discover example. Not sure which one is necessary or what each of them means.

**Comment by Bubbler-4** [comment]
> It includes the folder where the formatter and `hspec-codewars` is.

Ah, that makes sense.

> Not sure which one is necessary or what each of them means.

I didn't mean that one, the `test/Spec.hs` file is perfectly fine as is. By "the script", I meant the build script i.e. the one with `stack runghc -- ...` or `stack ghc -- ...`.

**Comment by kazk** [comment]
Got it working. I'll let you know when I deploy it.

**Comment by Bubbler-4** [comment]
Probably we need to test-run some proof katas to see if they don't timeout while compiling. Especially A+B=B+A one is known for being tight (not sure on other ones). It's not yet v8-enabled, so I guess we can check it while moving it to v8 (though I just found it's not yet unlocked...)

**Comment by kazk** [comment]
This is deployed now.

**Comment by Bubbler-4** [comment]
Umm... Looks like the running time display (the thing that comes with `<COMPLETEDIN::>`) has disappeared. Can you check the possible causes?

**Comment by kazk** [comment]
I removed the outer most "Tests" group which was used to calculate it. I haven't found a way to add duration for each `describe` yet.

**Comment by Bubbler-4** [comment]
Did some search and my wild guess is that `main = hspecWith {-option-} $ mapSpecItem timeIt id spec` might work, with [`Test.Hspec.Core.Spec.mapSpecItem`](https://hackage.haskell.org/package/hspec-core-2.7.0/docs/Test-Hspec-Core-Spec.html#v:mapSpecItem) and [`System.TimeIt.timeIt`](http://hackage.haskell.org/package/timeit-2.0/docs/System-TimeIt.html#v:timeIt) from package `timeit` or the simplified version

```haskell
timeIt ioa = do
  t1 <- getCPUTime
  ioa
  t2 <- getCPUTime
  printf "%.3fs" (t2 - t1)
```

I'll try it out in a kumite later.

**Comment by Bubbler-4** [comment]
@kazk I think I got it working [here](https://www.codewars.com/kumite/5c703ea1c447bd4b75bafebf?sel=5c703ea1c447bd4b75bafebf), though it assumes that dangling `<COMPLETEDIN::>` is rendered just like the matched ones.

**Comment by kazk** [comment]
> it assumes that dangling `<COMPLETEDIN::>` is rendered just like the matched ones.

I'm actually surprised this is rendered like that.

We probably need to wait for https://github.com/hspec/hspec/issues/315 to do it properly.

Is showing the total test duration important enough to do this? I didn't think anyone cared. I'd rather revert the change to remove "Tests" group than add this.

**Comment by Bubbler-4** [comment]
> We probably need to wait for [hspec/hspec#315](https://github.com/hspec/hspec/issues/315) to do it properly.

I agree. I just concluded that we can't properly support group-wise timings without serious hacks e.g. global mutable state.

> Is showing the total test duration important enough to do this? I didn't think anyone cared. I'd rather revert the change to remove "Tests" group than add this.

Personally, I like to have test duration displayed wherever possible, which is also a design decision behind the Python test framework (the `describe` and `it` blocks there are always timed). But it's in no way an absolute necessity, and I can live without that. I was just doing some experiments to see what we can do with what we have.

**Comment by kazk** [comment]
> Personally, I like to have test duration displayed wherever possible

Yeah, I agree. Just to be clear, I didn't think anyone cared for Haskell because test duration of Haskell was always hacky and didn't provide durations for each tests.

>> I'd rather revert the change to remove "Tests" group than add this.

For total test duration, I just realized that we don't need `Tests` group if unmatched `<COMPLETEDIN::>` works. We don't need any hack to do this.

But I'm pretty sure unmatched `<COMPLETEDIN::>` is a bug, so maybe I can add a way to output a message in similar style (or just use inline css) and use that. Regular log output looks too out of place.

![image](https://user-images.githubusercontent.com/639336/53277011-ae6f7a80-36b6-11e9-9b01-f7e7efc373cc.png)

**Comment by kazk** [comment]
I'll keep this in mind, but Haskell output won't have test durations for now.

**Comment by kazk** [comment]
By the way, have you tried using compiler flags (the original issue)?

**Comment by Bubbler-4** [comment]
I forgot to update the [kumite](https://www.codewars.com/kumite/5c703ea1c447bd4b75bafebf?sel=5c703ea1c447bd4b75bafebf) with a simpler way I found:

```haskell
specWrapper :: Spec -> Spec
specWrapper = beforeAll timeBefore . afterAll timeAfter . aroundWith (\ioa _ -> ioa ())
```

For the compilation flags, I can confirm that I can pass `-O` or `-O2` without being ignored. For actual performance or compilation time changes, I'll try some harsh katas out there and let you know if there's something bad with it.
