### ISSUE TITLE
PureScript: disable warnings for unspecified imports

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#703]
Unspecified imports are warnings for some reasons, and completely clutters the runner output.

Also *maybe* it'd be good to disable warnings in general?

**Comment by kazk** [comment]
> completely clutters the runner output.

Warnings in stderr should be collapsed when the tests pass. It's expanded on failure and that's intentional because warnings can contain useful information when something is wrong.

There's no way to turn off only unspecified imports warning as far as I know using the standard tools.

**Comment by Voileexperiments** [comment]
The problem is, warnings and errors are all printed to stderr, and whenever there's an compile error the error always goes after the warnings, which makes it very hard to read the error message.

**Comment by kazk** [comment]
Yeah, I agree. stderr currently doesn't support any formatting if I remember correctly. So we'll need to improve that first.
I also need to know if it's possible to get those errors/warnings in JSON or something so that we can display them better.

**Comment by kazk** [comment]
Opened #705
