### ISSUE TITLE
PureScript: `shouldEqual` failure message does not tell which value is expected/actual

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#704]
When I see

```
Test Failed
this thing ≠ that thing
```

Caused by failed `shouldEqual` assertion, how could I know which value is expected and which value is actual?

At least it should be annotated which value is expected and which value is actual.

**Comment by kazk** [comment]
We don't control the message. The right hand side should be the expected because we're testing for `a == b`.
