### ISSUE TITLE
Priority list for adding new languages

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#708]
Currently new languages are added as soon as a CW-compatible test framework stack setup is provided.

Which is not really a good idea. What if someone submitted setups for all the golfing languages in codegolf.SE? (They usually have a Python interpreter so setting them up isn't exactly hard. It's like SQL/Ruby and BF/JS setup.) [Try It Online](https://tio.run) has even more recreational and esoteric languages.

And currently it's weird that we're getting languages of little demand with almost no katas written on them while some very big items are still on the list (Pascal, Lisp, Smalltalk, MATLAB/Octave...).

Can we have a priority list or something based on demand and language popularity, so we can pick up the languages that are needed by more users and finish their setup?

**Comment by kazk** [comment]
> 
Which is not really a good idea. What if someone submitted setups for all the golfing languages in codegolf.SE?

I won't add them. This was already brought up when we added BF.

**Comment by kazk** [comment]
I didn't mean to close it.

> 
And currently it's weird that we're getting languages of little demand with almost no katas written on them while some very big items are still on the list

Which language are you talking about?

> 
Pascal, Lisp, Smalltalk, MATLAB/Octave...

Some of them have issues already open and not gained much interest.

**Comment by kazk** [comment]
> Can we have a priority list or something based on demand and language popularity, so we can pick up the languages that are needed by more users and finish their setup?

I'm doing this mainly on my own time after work as I feel like it. So I wouldn't want to have a list and be expected to work on them from the top to bottom.

That being said, if there's enough interest in a language and if there's enough information, I may prioritize it. I sometimes sort issues by the number of :+1: reactions to choose what to work on next.

So please open new issue if there isn't one already for the languages you have in mind, using the issue template and provide as much information as possible. Each language will be handled case by case.
