### ISSUE TITLE
Add Idris

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars-runner-cli#711]
Please complete the following information about the language:

- Name: Idris
- Website: http://idris-lang.org
- Language Version: [1.3.1](https://www.idris-lang.org/idris-1-3-1-released/)

The following are optional, but will help us add the language:

- Test Frameworks: [(native)](http://docs.idris-lang.org/en/v0.10.2/tutorial/testing.html), [specidris](https://github.com/pheymann/specdris)
- How to install: see [Download](https://www.idris-lang.org/download/)
- How to compile/run: `idris solution.idr -o solution && ./solution` (where `solution.idr` is the Idris program to be compiled)
- Any comments: *Much better suited than Haskell* at **theorem proving** due to *proper totality checking* (both coverage and termination check).  Consider [this Haskell "cheat"](
https://www.codewars.com/kata/reviews/5c302f795fd0d10001ba9117/groups/5c360e139098750001476767) to "A * B = B * A? Prove it!" - it leverages the absence of coverage and totality checking in Haskell to construct a fake "proof" which would never type-check in Idris to begin with.  Also, unlike PureScript which has received virtually no attention, I know of at least one fellow Codewarrior who would like to see it available on Codewars (special mentions below).

---

:+1: reaction _might_ help.  Special mentions: @ice1000 , @MarisaKirisame :wink:

**Comment by ice1000** [comment]
Is it possible to enforce users to `%total`?

**Comment by kazk** [comment]
We might be able to add test support by forking specdris and changing the output.

@ice1000 Can you explain what that is and what's need it to accomplish that?

**Comment by ice1000** [comment]
@kazk To ensure users don't write unsafe code (like panic in unreachable cases) and infinite-loop code.

Idris has the ability to use the type system to eliminate all impossible cases and people are supposed to make use of this mechanic.

IDK if it's easy to accomplish since I'm rarely Idrising. I was basically throwing some ideas so people can discuss.

**Comment by kazk** [comment]
@ice1000 

> By default, Idris allows all well-typed definitions, whether total or not. However, it is desirable for functions to be total as far as possible, as this provides a guarantee that they provide a result for all possible inputs, in finite time. It is possible to make total functions a requirement, either:
>
> - By using the `--total` compiler flag.
> - By adding a `%default total` directive to a source file. All definitions after this will be required to be total, unless explicitly flagged as partial.
>
> All functions after a `%default total` declaration are required to be total. Correspondingly, after a `%default partial` declaration, the requirement is relaxed.
>
> http://docs.idris-lang.org/en/latest/tutorial/theorems.html#directives-and-compiler-flags-for-totality


I guess we can put `%default total` whenever needed and disallow flagging it as partial? I'm guessing it's not always enforced because that'll be too strict.

**Comment by kazk** [comment]
The code runner part of Idris support is almost ready.

I've got the test support with specdris by [forking and changing the output](https://github.com/pheymann/specdris/compare/master...kazk:codewars-output). The code was easy to follow even it was my first time reading Idris. The [example from their repo](https://github.com/pheymann/specdris/blob/7d7721cb16f71a389145ce0f41562d889ae648a7/examples/SpecExample.idr) works.

Minimum example:

```idris
module Solution

%access export
%default total

add : Nat -> Nat -> Nat
add a b = a + b
```

```idris
module SolutionSpec

import Specdris.Spec
import Solution

%access export
%default total

specSuite : IO ()
specSuite = spec $ do
  describe "add" $ do
    it "adds two natural numbers" $ do
      (1 `add` 1) `shouldBe` 2
```

The test needs to export `specSuite : IO ()` like in their example. The name of the module can be anything and the optional preloaded code will be just extra module.

**Comment by Bubbler-4** [comment]
Just added a thumbs up. I got disappointed at Haskell once when I saw [a pile of type system hacking for a seemingly simple task - modular arithmetic](https://github.com/TikhonJelvis/modular-arithmetic/blob/master/src/Data/Modular.hs); I still have no idea how it works. Idris looks promising in this particular aspect to me.

**Comment by kazk** [comment]
Idris is now available on Codewars.
See [example kumite](https://www.codewars.com/kumite/5c7ecdc3f3c865000ce13d6c?sel=5c7ecdc3f3c865000ce13d6c) or [wiki page](https://github.com/Codewars/codewars.com/wiki/Language-Idris) for how to write tests.

**Comment by DonaldKellett** [comment]
Great, we finally have a language dedicated to theorem proving on CW! :tada: 

One thing though - random tests currently appear to be infeasible in Idris, at least when using specdris.  While I doubt random tests will find their use in theorem-proving Kata where totality is enforced (which should make it pretty hard to get hardcoded "proof"s to type-check), a lot of generic Haskell/PureScript kata on topics other than theorem proving should also be suitable for translation into Idris.  In those cases, being able to write random tests could be helpful.

Incidentally, pheymann/specdris#1 mentions a [QuickCheck implementation in Idris](https://github.com/david-christiansen/idris-quickcheck) which has not been integrated into specdris as of 06/03/2019.  Would such an integration be possible?

**Comment by kazk** [comment]
> Would such an integration be possible?

I'd recommend working with specdris authors and make something that can be used by the Idris community and not just on Codewars. We're using specdris with [minimal change](https://github.com/pheymann/specdris/compare/master...kazk:codewars-output) so we should be able to use it too.

I'd start by asking them for their plans and what can be helped. It has "help wanted" label so I'm sure they're looking for some help :)

I have no experience with Idris so I can't help with this. Maybe some of our users can, but I think the discussion should happen on https://github.com/pheymann/specdris/issues/1.

**Comment by ice1000** [comment]
I've did the first non-multiply Kata translation: https://www.codewars.com/kumite/5c7fbeaf9775762c55934656?sel=5c7fbeaf9775762c55934656

**Comment by Voileexperiments** [comment]
@kazk There's a critical issue in regards to type holes:

1. They don't actually show the type of the holes at all: ![image](https://user-images.githubusercontent.com/14909989/53893697-a5dd5380-4069-11e9-88d0-16c469d89611.png)

2. They're only *warnings*, which means a kata can be passed with dangling holes that are not evaluated. However the holes is as powerful as `undefined` in Haskell (in fact it even covers equality types like `2 + 2 = 4`) so for example, in [this kata](https://www.codewars.com/kata/im-now-360-degree-different-from-the-past/train/idris), submitting initial solution passes the kata.

**Comment by Voileexperiments** [comment]
There's another issue(?):

Every data type and type level function must be `public export`ed in order for the test module to see them (and the same goes to the test module to `main`), so `%access public export` should be the default for almost all cases. This throws people (read: me when solving a Idris kata) off because e.g [Try It Online](https://tio.run/#idris) does not need it (code are in the same module as `Main.main`).

I think at least this should be documented somewhere?

**Comment by ice1000** [comment]
Doilecument
