### ISSUE TITLE
Optimization is off by default

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars-runner-cli#714]
Apparently [compiler flag for C++ runner does not have optimization turned on](https://github.com/Codewars/codewars-runner-cli/blob/815480438a336443327e850a2c9e51eaae8e4989/lib/runners/cpp.js), as well as other languages.

This is arguably wrong because it's non-standard: standard optimization parameter used across most languages (if available) in OJ ecosystem (e.g IOI [[1]](http://ioi2017.org/contest/environment/), ACM [[2]](https://icpc.baylor.edu/worldfinals/programming-environment), Codeforces[[3]](https://codeforces.com/blog/entry/79)[[4]](https://codeforces.com/blog/entry/57646)) is `-O2`, so CW should use `-O2` by default too.

Now there is #699, but `OPTIONS_GHC` pragma [overrides command-line options anyway]( https://downloads.haskell.org/ghc/latest/docs/html/users_guide/using.html#command-line-options-in-source-files) so it shouldn't be a problem:

> NOTE: The contents of OPTIONS_GHC are appended to the command-line options, so options given in the source file override those given on the command-line.

**Comment by kazk** [comment]
C/C++ needs an update in general. I'm going to turn on the warnings as well which was turned off because Codewars used to treat `stderr` as error.

**Comment by Voileexperiments** [comment]
For C++, I used this OB snippet for testing optimization:

```
#include <iostream>

typedef int (*Function)();

static Function Do;

static int EraseAll() {
  std::cout << "Safe!\n";
  return 1;
}

void NeverCalled() {
  Do = EraseAll;
}

int test() {
  return Do();
}
```

Calling `test` in `-O1` or above will not crash because `Do = EraseAll` is completely optimized in these cases (check with [Compiler Explorer](https://www.godbolt.org/z/ptAyxk)).

A kumite is available [here](https://www.codewars.com/kumite/5c7f809af3c8655f35e13f99?sel=5c7f809af3c8655f35e13f99).

**Comment by Voileexperiments** [comment]
> C/C++ needs an update in general

I suppose the update includes using the newest version of `clang`/`gcc`?

Also compiler optimization flag applies to many other languages besides C/C++, so they have to be checked against as well.

**Comment by Voileexperiments** [comment]
Also, ref: #706

**Comment by kazk** [comment]
`-O2` was added to newer versions of C/C++.

**Comment by Voileexperiments** [comment]
What about other languages that has similar optimization settings?
