### ISSUE TITLE
Forbit holes in Idris submissions

### ISSUE THREAD

**Issue by ice1000** [Codewars/codewars-runner-cli#717]
#### Describe the bug

Prove with a hole: `?unfinished_code`

#### To Reproduce

... and run it.

#### Expected Behavior

Test failed because the code is incomplete.

#### Screenshots
![image](https://user-images.githubusercontent.com/16398479/53895929-0e441a80-4001-11e9-8f18-80bd22d6d56e.png)

**Comment by kazk** [comment]
Is there a way to enforce this? I've looked at compiler flags but I don't think I see anything.

If not, we can consider having `WARNING: There are incomplete holes:` a failure.

**Comment by ice1000** [comment]
I didn't see any ways of enforcing this. Thumb up for banning the warning message.

**Comment by kazk** [comment]
OK, I post-processed the output to make this warning a failure.

![image](https://user-images.githubusercontent.com/639336/53999318-d66bce80-40f7-11e9-94d2-9fa8f19c92d3.png)

I might change the test group name, but it'll look something like this.

I'll close this issue when I deploy.

**Comment by ice1000** [comment]
Nai su~

**Comment by kazk** [comment]
Deployed
