### ISSUE TITLE
[Idris; Discussion] Easy escape hatches for subverting the totality checker (cheat)

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars-runner-cli#718]
Currently, it is very easy to subvert the totality checker in Idris by marking partial functions as total - see 
https://www.codewars.com/kumite/5c7fde0290438512c5ce7bac?sel=5c7fde0290438512c5ce7bac . This would place theorem-proving Kata in Idris in jeopardy since the only reason Idris kata are not expected to have random tests is because the type system is expected to automatically reject incorrect proofs (represented by ill-typed programs in Idris).  With easy escape hatches like `assert_total`, `believe_me` and the like, fake proofs can be constructed in Idris as easily as in Haskell.

What should we do if we discover someone abusing these loopholes?  Some potential suggestions:

1. It is the responsibility of the Kata author/translator in Idris to check the user solution for such escape hatches (how? maybe read solution file and check for terms like "assert" and "partial"?)
2. It should be treated like runner cheats in other languages with harsh penalties for offenders, e.g. perma-ban.

Feel free to chime in :smile: Special mentions: @ice1000 @MarisaKirisame (feel free to mention others if they are also interested in Idris on Codewars)

**Comment by Bubbler-4** [comment]
If we ban the use of partial/assert/holes/whatever altogether, won't it affect non-theorem-proving katas that require you to write partial functions by nature?

**Comment by ice1000** [comment]
> If we ban the use of partial/assert/holes/whatever altogether, won't it affect non-theorem-proving katas that require you to write partial functions by nature?

No, partial functions are possible with the absense of `%default total` in tests. People don't need holes to write partial functions.

**Comment by Bubbler-4** [comment]
Another question. Suppose that we want to write A + B = B + A kata in Idris. If I write a line of test code

```idris
x : 3 + 5 = 5 + 3 -- just an example
x = plusCommutes 3 5 -- just an example
```

and a user tries to cheat with incomplete proof, which of the possible cheats can be caught with e.g. compile-time infinite loop or runtime crash?

**Comment by ice1000** [comment]
This won't be a compile time infinite proof due to totality. Runtime crash may not be caught due to erasure.

I suppose only type error can be caught.

**Comment by Bubbler-4** [comment]
Erm... looks like we have one more loophole, namely [`postulate`](https://www.codewars.com/kata/reviews/5c7fdf85ecdbb9000149d24e/groups/5c835866fc6e19000149fff3) ([related SO question](https://stackoverflow.com/questions/27999552/postulates-in-idris)). Unlike typed holes, it is *designed* for assertions that aren't provable inside Idris, e.g. those about built-in types.

**Comment by ice1000** [comment]
Can we pattern match a `postulate`d i.e. equality proof with `Refl`? Is it gonna work on earth?

**Comment by Bubbler-4** [comment]
No chance, even with properly proven ones.

```idris
plusComm : (a : Nat) -> (b : Nat) -> a + b = b + a
plusComm = plusCommutative

proofEval : {a : Nat} -> {b : Nat} -> (a + b = b + a) -> Nat
proofEval {a=a} {b=b} Refl = a + b

main : IO ()
main = do
  putStrLn "Compiled Successfully!"
```

```
  |
5 | proofEval {a=a} {b=b} Refl = a + b
  | ~~~~~~~~~
When checking left hand side of proofEval:
When checking an application of Main.proofEval:
        Type mismatch between
                plus b a = plus b a (Type of Refl)
        and
                a + b = b + a (Expected type)
        
        Specifically:
                Type mismatch between
                        plus b a
                and
                        plus a b
```

**Comment by ice1000** [comment]
Try this

```idris
proofEval : {a : Nat} -> {b : Nat} -> (a + b) -> (a + b = b + a) -> Nat
proofEval {a=a} {b=b} (b + a) Refl = a + b
```

**Comment by Bubbler-4** [comment]
No, `Refl` is not recognized as a constructor for `a + b = b + a` type.

Meanwhile, I found [a way to catch `postulate` and holes using dependent tuples](https://tio.run/##rZNBS8NAEIXv@RXPIpi05NDqKRBFiwdBVFQ8eCnTZmMXNtmwO1sp4m@Pm8S0tSexEjLMZt58b2fZyMxIW9dxjI8YL6RkhsponQeVcnaqiwIJQvLhjjhCfI5wvrMgjDBH6t8RaNuSok8dE8uVCDw//gwC7zElKzBO8LyuRIalVuJAq4s@3zeZJHjQlp0i9h59hj@47YFPE1wJJcVKoBAIS81YkHtbcnTQKNR97MizhtwKo337swSX1grDYM2k/nsD1LJnHft4c1wnbfl9KYwIgIoMS1/fVn/vh52uV/@keBS56qdsb9/1yrO3RAyHG2Cb/wBGUbTTlSIct5pJEzezjTHxsqAgWXrOzT3CqFukyHSzJcdPbG5LDLy8ksrfzSe3WAhrc6fU@mjQaIws2R9Jbptoy@9fpbGt6y8):

```idris
plusComm : (a : Nat) -> (b : Nat) -> a + b = b + a
plusComm = plusCommutative

proofEval : (a : Nat ** (b : Nat ** (a + b = b + a)))
proofEval = (1 ** (2 ** plusComm 1 2))

main : IO ()
main = do
  putStrLn "Compiled Successfully!"
  print $ fst $ snd proofEval
```

Output:
```
Compiled Successfully!
2
```

Some possible fake proofs and the results:
```
-- typed hole
plusComm : (a : Nat) -> (b : Nat) -> a + b = b + a
plusComm = ?plusComm
-- result: runtime error (abort)
ABORT: Attempt to evaluate hole Main.plusComm1

-- postulate
postulate plusComm : (a : Nat) -> (b : Nat) -> a + b = b + a
-- result: compilation error
reachable postulates:
  Main.plusComm
```

But `assert_total` and `believe_me` are not caught. Can we remove those definitions (`assert_total`, `believe_me`, `really_believe_me`) from the Idris stdlib?

**Comment by ice1000** [comment]
This is really cool, admire

**Comment by ice1000** [comment]
Banned `postulate` in https://www.codewars.com/kata/5c82b661562a2074bbeac980/discuss

**Comment by ice1000** [comment]
We should special mention this in some wiki or kata example test cases

**Comment by ice1000** [comment]
Banned `postulate` in https://www.codewars.com/kata/5c7fdf0b00718714fd002bd2/ as well

**Comment by Bubbler-4** [comment]
> But `assert_total` and `believe_me` are not caught. Can we remove those definitions (`assert_total`, `believe_me`, `really_believe_me`) from the Idris stdlib?

On second thought, we can't remove `assert_total` because the stdlib itself (e.g. some Nat functions) depends on it. Then we probably really need source code pattern matching on them?

What if we put a line of bash script (say, grep) into the runner so that it refuses to run if the source contains one of `assert` or `believe_me`? IMO it's more gentle and overall better option than e.g. a perma-ban, if *anything* should be done on the runner side.

**Comment by kazk** [comment]
@Bubbler-4 Yeah, we can check if the solution contains any of those and consider failed. I don't know if there's a way to workaround that, but it should be enough to prevent accidental cheating. We'll have false positives like `assert_total` in a comment, but that should be acceptable trade-off.

So disallow the following?

- `assert_total`
- `believe_me`
- `really_belive_me`

I'll probably still allow it to run and just mark it as failed, similar to the hole #717.

**Comment by Bubbler-4** [comment]
Yes, the three are the identified ones. I think we can disallow using the keyword `postulate` too - while it's catchable, the exact mechanism of catching it is unknown, so it may not be applicable to all cases.

**Comment by MarisaKirisame** [comment]
update: it turnout idris has so much loophole it is impossible.
https://www.reddit.com/r/Idris/comments/b008b5/how_do_i_stop_people_from_writing_partial_program/

**Comment by Bubbler-4** [comment]
@MarisaKirisame That's exactly why we're going for pattern-matching on source code at #725.

In the (likely incomplete) list of possible loopholes, I tried to identify all the functions in the stdlib that open the access to `a -> b` while keeping it total (or faking it). For `x -> Void` functions (aka impossibility proofs), it's impossible to construct a value of type `x` in the first place (without introducing a new axiom, which in turn requires a use of `postulate` or other loophole functions).

**Comment by kazk** [comment]
I'm closing this because #725 is deployed and I think that's the most we can do at the moment. But feel free to continue the discussion here if necessary.
