### ISSUE TITLE
Node 10 error messages becomes very ugly if error comes from outside of a `it` block

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#722]
Suppose I have this piece of code:

```javascript
function removeWhitespaces(s) {
  return s.replace(/ /ig,'');
}

describe("Solution", function() {
  it("should test for something", function() {
    Test.assertEquals(removeWhitespaces('a quick brown fox jumps over the lazy dog'), 'aquickbrownfoxjumpsoverthelazydog');
    removeWhitespaces(0); // 'Error!'
  });
});
```

In Node 10, putting `removeWhitespaces(0)` inside a `it` block gives a very nice message:
![image](https://user-images.githubusercontent.com/14909989/54096465-f399e900-43e6-11e9-8c50-badfdf8038f2.png)

This not the case if it's it put outside of a `it` block:
![image](https://user-images.githubusercontent.com/14909989/54096499-1f1cd380-43e7-11e9-8852-66a7d60e30d2.png)

(Also note that there are 2 scrollbars if the error is thrown in a `describe` but outside `it` block, which is another related bug.)

In Node 8, error messages are much cleaner and consistent: (in the order of outside `describe` block, inside `describe` block and inside `it` block)

![image](https://user-images.githubusercontent.com/14909989/54096563-630fd880-43e7-11e9-8ed4-0bb157b8d559.png)

![image](https://user-images.githubusercontent.com/14909989/54096577-71f68b00-43e7-11e9-847a-f09f90131213.png)

![image](https://user-images.githubusercontent.com/14909989/54096596-7fac1080-43e7-11e9-8983-9bc913d7cc0a.png)

**Comment by kazk** [comment]
Fixed
