### ISSUE TITLE
Forbid some functions in Idris

### ISSUE THREAD

**Issue by kazk** [Codewars/codewars-runner-cli#725]
A solution containing any of the following should be considered failed:

- `assert_total`
- `assert_unreachable`
- `assert_smaller`
- `believe_me`
- `prim__believe_me`
- `really_believe_me`
- `postulate`

Submitted solution containing them should still run, but marked as failed similar to #717. The goal is to prevent accidental cheating and still allow to use them while solving.

Any of `System.exit`, `System.exitWith`, `System.exitFailure`, `System.exitSuccess` can be combined with printing the test passed message like other languages, but this shouldn't happen accidentally. Same for `idris_crash`. These can be marked as intentional cheat and repeated offenders are banned.

Fixes #718

**Comment by Bubbler-4** [comment]
> `assert_similar`

No, it's `assert_smaller`. It's uses are to indicate that a recursive definition will indeed terminate.

**Comment by kazk** [comment]
Good catch! Fixed the comment. I'll work on this tonight.

**Comment by kazk** [comment]
Deployed
