### ISSUE TITLE
Status of Racket support?

### ISSUE THREAD

**Issue by yfzhe** [Codewars/codewars-runner-cli#727]
It seems that the Racket support on Codewars is on the waitlist for a long time. On the "training setup" page, Racket has stayed in the area "Languages which are not yet supported within Kata" since I first used Codewars when is about a year ago. 

In the README of this repo, Racket is listed in the "[Language Support Status](https://github.com/Codewars/codewars-runner-cli#language-support-status)" table, with "Kumite only" note. 

Just want to know there is something like a roadmap for Racket support.

**Comment by DonaldKellett** [comment]
Gentle reminder: to those who want Racket to be fully supported on Codewars, :+1: reaction *might* help.

**Comment by kazk** [comment]
@yfzhe can you [open an issue using our template for language request](https://github.com/Codewars/codewars-runner-cli/issues/new?template=request-language.md) and provide as much information as you can?

**Comment by yfzhe** [comment]
As there is some partial support for Racket, I thought it would not be new language support.😔 OK, I will open a new issue.

**Comment by kazk** [comment]
Thanks. It's not a new language, but we don't have test support and that template will be a good starting point.
