### ISSUE TITLE
Cannot use crypto functions in C/NASM

### ISSUE THREAD

**Issue by uniapi** [Codewars/codewars-runner-cli#728]
The openssl library functions are not available in C and NASM solutions (translations).
Trying to use the `MD5` function or similar gives the following linker error:
```
/tmp/solution-b46886.o: In function `passwd_hash':
solution.c:(.text+0x61): undefined reference to `MD5'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
The link to [C Translation](https://www.codewars.com/kumite/5c82508c40d43b1f0f0b75b6?sel=5c82508c40d43b1f0f0b75b6)

Please, add `-lcrypto` for C and NASM languages (maybe for C++ and Objective-C)
Also add `-ldl` as it will be needed in some future Katas not to open a similar issue again...

:+1:

**Comment by uniapi** [comment]
If `status/ready` means that the package was added then the same error message still appears...
Otherwise, ignore this comment.

**Comment by kazk** [comment]
It means it's ready to be deployed (hover over the label or go to labels page). I'll close when it's deployed.

I might change the name to make it more clear.

**Comment by kazk** [comment]
Deployed

**Comment by uniapi** [comment]
Great! It does work now...
:rainbow:
