### ISSUE TITLE
Add Racket testing support

### ISSUE THREAD

**Issue by yfzhe** [Codewars/codewars-runner-cli#729]
- Name: Racket
- Website: https://racket-lang.org/
- Language Version: 7.2

The following are optional, but will help us add the language:

- Test Frameworks: [rackunit](https://docs.racket-lang.org/rackunit/)
- How to run: `racket <filename>`
- How to compile (to bytecode): `raco make <filename>` (details in <https://docs.racket-lang.org/raco/make.html>)

---

:+1: reaction _might_ help.

---

- [x] Install `racket`
- [x] Run code
- [x] Testing support (need to implement a function to output the test results)
- [x] Logo for icon

**Comment by yfzhe** [comment]
Just made a simple wrapper using `foldts-test-suite` that make check result of a **test suite** in Codewars format. 

Only support the basic tags ("a small subset of commands" in the document): `<DESCRIBE::>` (nested), `<IT::>`, `<PASSED::>`, `<FAILED::>`, `<ERROR::>` and `<COMPLETEDIN::>`. `<DESCRIBE::>` for a test suite, `<IT::>` for a test case, `<PASSED::>` when check succeeded, `<FAILED::>` when check failed, `<ERROR::>` when an error is raised.

Don't know how to contribute to this repo, and just put the code to one gist: https://gist.github.com/yfzhe/dc3115b4a29957ec6d68ee908d8cd1cd

Some note:
- Not familiar with Codewars format. Is there some difference between the structure of Codewars output format and Rackunit? In Rackunit, 
  
  > A check is the basic unit of a test. As the name suggests, it checks whether some condition is true.
  > 
  > A test case is a group of checks that form one conceptual unit. **If any check within the case fails, the entire case fails.**
  > 
  > A test suite is a group of test cases and test suites that has a name.
  
  As described above, however many checks are in a test case, if one check failed, checks following would not be run. Inside Rackunit, an error would be raised. Therefore, only one `<FAILED::>` would appear in `<IT::>`.
- This code is a little dirty for supporting direct output. I open a string port, and make both the direct output and checks result print to this port, and then get the content from the string port, which is not so "functional".
- `<LOG::>` tag is not supported. Not sure whether it must be supported. Making another pass after `run-test-and-wrap-result` to add `<LOG::>` for lines which does not have a prefix tag can fix it. Or we build a Codewars' version of `display`, `print`, ..., which prefix a `<LOG::>`, using Racket's `#lang` feature.

**Comment by kazk** [comment]
@yfzhe Thanks for doing this! Looks great!
There's one typo:
```racket
(define complited "<COMPLITEDIN::>")
```
should be
```racket
(define complited "<COMPLETEDIN::>")
;;                       ^
```

Once this is fixed, it should be displayed like:

![image](https://user-images.githubusercontent.com/639336/54497212-057efe80-48b5-11e9-8bc3-e91ebeff7e13.png)

![image](https://user-images.githubusercontent.com/639336/54497229-424af580-48b5-11e9-98b4-5d1e004cdb87.png)

---

> Don't know how to contribute to this repo

Yeah, sorry. I'll create a new repository for this so you can open a PR.

> Therefore, only one `<FAILED::>` would appear in `<IT::>`.

This is fine, most of the test frameworks we support works like this.

> * This code is a little dirty for supporting direct output. I open a string port, and make both the direct output and checks result print to this port, and then get the content from the string port, which is not so "functional".

I think this is fine.
Just one thing, what happens if a user uses `print`, i.e., without trailing newline?
Will it output like the following?
```
'yes<PASSED::>Test Passed
```
If so, all tags should be prefixed with `\n`, e.g., `\n<PASSED::>`.

> * `<LOG::>` tag is not supported. Not sure whether it must be supported.

No need to support it. Lines without output commands are considered `<LOG::>`.

**Comment by kazk** [comment]
I think we should create `test/codewars` function that does `
(display (run-test-and-wrap-result test))` so we can make a package and use it like `test/gui` from `rackunit/gui`.

Example usage:
```racket
#lang racket
(require "solution.rkt")
(require rackunit codewars/rackunit)

(test/codewars
 (test-suite
  "example"
  (test-case "add" (check-equal? (add 1 1) 2))))
```

It'll be nice if `test/codewars` exit with `1` if any test fail. Is this possible?

---

I'm going to explain how we'll proceed from here. Please correct me if I'm misunderstanding anything.

Once I make a new repository for the test runner and we package this, we should be able to install it by:
```
raco pkg install --name 'codewars/rackunit' https://github.com/Codewars/codewars-rackunit.git
```

When using this, we'll set up the files:
```
- preloaded.rkt (optional module from the author)
- solution.rkt
- tests.rkt
```
and we should be able to run `racket tests.rkt`.

**Comment by yfzhe** [comment]
> Just one thing, what happens if a user uses print, i.e., without trailing newline? Will it output like the following?

Yes. I missed it. Does Codewars just ignore blank lines in output? If so, I will add a prefix "\n" to tags, which you pointed out above.

> I think we should create test/codewars function that does (display (run-test-and-wrap-result test))

Ok. And now the code will not open a string port, and put all output into it. Just output to stdout (`current-output-port`). And rename the function `run-test-and-wrap-result` to `run-tests`, looking like using `rackunit/test-ui`:)

Also, there will be a module `codewars/rackunit` (or `rackunit/codewars`, unsure which one is preferred), exporting `run-tests` and all things from rackunit, so we can just require one module.

**Comment by yfzhe** [comment]
And the Racket logo on Codewars website is different with the one on the Racket website: https://racket-lang.org/img/racket-logo.svg.

![image](https://user-images.githubusercontent.com/18626884/54504095-2440cc00-496d-11e9-866f-25b427c80f9f.png)

**Comment by kazk** [comment]
> Yes. I missed it. Does Codewars just ignore blank lines in output? If so, I will add a prefix "\n" to tags, which you pointed out above.

Yeah, it ignores blank lines.

> exporting `run-tests` and all things from rackunit, so we can just require one module.

I'd like to keep the setup as close as possible to how you'd run tests outside of Codewars. Does `rackunit/text-ui` export all things from `rackunit`? Will this work?

```racket
(require "solution.rkt")
(require rackunit/text-ui)

(run-tests
 (test-suite
  "example"
  (test-case "add" (check-equal? (add 1 1) 2))))
```

If it does, then I'd like to do the same.

For module name, I guess `codewars/rackunit`. I made https://github.com/Codewars/codewars-rackunit, can you open a PR there with any other necessary files to make it installable?

---

> And the Racket logo on Codewars website is different with the one on the Racket website

I guess they updated the logo. The old one is more similar to the icon on Codewars: https://www.racket-lang.org/logo.png

**Comment by yfzhe** [comment]
Yes, they updated the logo, two years ago. <https://blog.racket-lang.org/2017/01/racket-v6-8.html> In my opinion, using the new one is better.

**Comment by yfzhe** [comment]
Great! 

So when can we use Racket on Codewars?

**Comment by kazk** [comment]
I'll try releasing sometime during this week, but it depends on how busy I am.

I'll review https://github.com/Codewars/codewars-rackunit/pull/1 tomorrow because I need to get some sleep.

Thanks for contributing!

**Comment by kazk** [comment]
Racket 7.2 is now available. There's obviously no kata yet, so please help translating existing kata.

**Comment by error256** [comment]
Are handling `message` parameters of checks and additional `check-info` data not implemented?

**Comment by kazk** [comment]
@error256 I'm not sure. Can you open a new issue with more details on https://github.com/Codewars/codewars-rackunit ?

**Comment by yfzhe** [comment]
No. Have considered using location `check-info`, but I found when an error was raised while checking test, we can only catch a simple error, not `exn:test:check`. That means, we can only use `check-info`s when a test **failed**, can not when an **error** raised.

Anyway, adding issue on `codewars-rackunit` is preferred.
