### ISSUE TITLE
Add Julia 1.0

### ISSUE THREAD

**Issue by inkydragon** [Codewars/codewars-runner-cli#730]
Compare to Julia 0.6, julia 1.0 changed a lot. So I'm not sure if we should update 0.6 to 1.0 or just add a new version.

- Name: Julia
- Version: [v1.0.3 LTS](https://julialang.org/downloads/)
- Release Note/Changelog:
    + [0.6 -> 0.7](https://docs.julialang.org/en/v0.7/NEWS/): Changed a lot, add new language features, many Breaking changes.
    + [0.7 -> 1.0(1.0.3)](https://docs.julialang.org/en/v1.0/): removal of deprecation warnings, using Deprecated or removed function/features will cause a error.
- TestSuit
    + [JuliaAttic/FactCheck.jl](https://github.com/JuliaAttic/FactCheck.jl) No longer update.
    Just use [`Test`](https://docs.julialang.org/en/v1.0/stdlib/Test/) pkg in Julia Standard Library

**Comment by kazk** [comment]
@inkydragon We'll add 1.0, update exiting kata to 1.0, then remove 0.6.
Does `Test` pkg support customizing the test output?

**Comment by inkydragon** [comment]
> Does `Test` pkg support customizing the test output?

I think `Test` Pkg covered most functions of `functions `. And we could do some hacks.

So, we should update this file [codewars-runner-cli/`Test.jl`](https://github.com/Codewars/codewars-runner-cli/blob/master/frameworks/julia/Test.jl) to use StdLib `Test` right?

I will try my best to do it.

**Comment by kazk** [comment]
> So, we should update this file [codewars-runner-cli/`Test.jl`](https://github.com/Codewars/codewars-runner-cli/blob/master/frameworks/julia/Test.jl) to use StdLib `Test` right?

No, that's really outdated. I don't think that even works with 0.6. FactCheck used on Codewars is a modified version of https://github.com/JuliaAttic/FactCheck.jl/commit/51a5e71937e3d35c0ce8e5b9fbbf84ffba81dd45 .

I'll try to extract it and make it available for you to see.

**Comment by kazk** [comment]
I mad a fork and applied the changes. https://github.com/kazk/FactCheck.jl/commit/edb6598260f6325cacafdc68cc5299f4d56f7abd
This is what we currently use with Julia 0.6. If you can make that work with Julia 1.0, that'll be great.

**Comment by kazk** [comment]
Julia 1.0 is now available on Codewars. Thanks for your help.
I ran a script to update compatible kata, but it looks like 137 kata needs to be updated manually.

**Comment by inkydragon** [comment]
> 137 kata needs to be updated manually

Is there a list of those kata?

We could add this list to wiki, just like [List of Haskell Kata to Update · Codewars/codewars.com Wiki](https://github.com/Codewars/codewars.com/wiki/List-of-Haskell-Kata-to-Update)

**Comment by kazk** [comment]
I made a page: https://github.com/Codewars/codewars.com/wiki/List-of-Julia-Kata-to-Update

**Comment by inkydragon** [comment]
I' am trying to update kata by fork Translations (like [Julia Translation](https://www.codewars.com/kumite/5ba0a1e7362ce9d762000125?sel=5cb81d9979ac890017205d75)), but this kata doesn't update, so there is no way to update a Approved kata except  [those three ways](https://github.com/Codewars/codewars.com/issues/1723#issuecomment-462507533)?

**Comment by kazk** [comment]
Yes. Currently those are the only way. I'd recommend commenting with "Suggestion" label and include the link to the wiki page of Julia kata to update.

Forking and approving doesn't work at the moment because of https://github.com/Codewars/codewars.com/issues/1725

**Comment by kazk** [comment]
I've fixed https://github.com/Codewars/codewars.com/issues/1725 so you should be able to use translation forks to update.
