### ISSUE TITLE
Agda: Improve type-checking time

### ISSUE THREAD

**Issue by Bubbler-4** [Codewars/codewars-runner-cli#733]
I have a feeling that it takes too long to typecheck Agda on CW. When I work locally with emacs, commonly used library modules like `Data.Nat` get pre-typechecked (so the compiled type information is stored for reuse), and re-typechecking takes (pretty much) less than a second.

If it isn't done already, can we get the library modules pre-typechecked inside the Docker image? For standard library, [I think you can run `GenerateEverything.hs` then call `agda Everything.agda` or the like](https://github.com/agda/agda-stdlib/blob/master/GenerateEverything.hs). For Cubical library, [it should be enough to call `make`](https://github.com/agda/cubical/blob/master/Makefile).

I'm suggesting this because [this kata](https://www.codewars.com/kata/typeclass-is-garbage) imports several big nested modules including `Data.Nat`, `Data.Integer` and `Data.List`, which makes the code time out several times. (And even if a run finishes successfully, having to wait ~12 seconds every time just to typecheck is not very good.)

**Comment by kazk** [comment]
> If it isn't done already, can we get the library modules pre-typechecked inside the Docker image?

This is already done. `cabal install` does for `agda` itself. For `agda-stdlib`, `cabal install` and `dist/build/GenerateEverything/GenerateEverything`. For `cubical`, `make`.

**Comment by Bubbler-4** [comment]
I guess we can do nothing about it (just found that batch mode is slow as hell, even on my local PC). Then can you at least increase the time limit, to 15s or maybe 20s?

**Comment by kazk** [comment]
I'll make it 16s for now.

**Comment by kazk** [comment]
I'll close this when it's deployed.

**Comment by kazk** [comment]
The change is deployed
