### ISSUE TITLE
Parts of failure messages are displayed as Log

### ISSUE THREAD

**Issue by error256** [Codewars/codewars-runner-cli#735]
Everything after the first line is displayed as Log. It's displayed like this at least for OCaml and Clojure; probably for other languages, but these too have multiline messages by default.
https://www.codewars.com/kumite/5cacb6bd2caabb001801810f?sel=5cacb6bd2caabb001801810f
![image](https://user-images.githubusercontent.com/5375100/55813588-890ac480-5adc-11e9-81a8-3d3dfa77bdfe.png)

- [x] OCaml
- [x] Clojure

**Comment by kazk** [comment]
Thanks for letting me know. I've fixed OCaml and simplified/fixed Clojure. The changes were just deployed.
