### ISSUE TITLE
First character isn't printed in Rust 1.33

### ISSUE THREAD

**Issue by error256** [Codewars/codewars-runner-cli#738]
https://www.codewars.com/kumite/5cd3ff7e8b47bb001982deaa
```rust
println!("qwerty");
println!("asdfgh");
```
shows
```
werty
asdfgh
```
in Rust 1.33 (and only in 1.33).

**Comment by kazk** [comment]
Thanks for always including Kumite showing the bug, it's extremely helpful.

Looks like this is caused by Rust 1.33's output lacking a tab character (`\t`) in front of the first line unlike previous versions.
I'll close this when the fix is deployed.

**Comment by kazk** [comment]
Fixed
