### ISSUE TITLE
Node 8 runner does not await all currently running Promises before exiting

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars-runner-cli#739]
Reported in and adapted from [here](https://www.codewars.com/kata/5a331ea7ee1aae8f24000175/discuss/javascript). Given this piece of code:

```
function trap() {
  console.log('s');
  trap();
}

const assert = require("chai").assert;
assert.isDefined(trap);
new Promise(trap).catch(e=>(console.log(e), console.log('<FAILED::>')));
```

`trap` manages to abort the test without triggering any exception (it should raise a `RangeError: Maximum call stack size exceeded` error, which will then get caught and result in a failed test case. However the `catch` part never got to run at all, resulting in no failed tests).

This only works when
- language version is Node 8.1.3
- Argument of `console.log` is a string
- `trap` is called inside an async block (e.g `describe`/`it`)

This sounds really like a Node bug IMO. I guess it's time to upgrade Node 8 version?

**Comment by Voileexperiments** [comment]
[Another example](https://www.codewars.com/kata/reviews/5a4af62e5f08294c840020cb/groups/5d4a243c57245b00015d3a35)

**Comment by kazk** [comment]
Closing because it doesn't seem to happen in newer versions of Node.
