### ISSUE TITLE
Add Equations package for Coq

### ISSUE THREAD

**Issue by Bubbler-4** [Codewars/codewars-runner-cli#741]
Please complete the following information about the package:

- Name: Equations 1.2
- Language Name: Coq 8.9
- Website: http://mattam82.github.io/Coq-Equations/
- Install Command: `opam install coq-equations.1.2+8.9`

Following are optional, but will help us consider adding:

- Why is this useful?

> Equations provides a notation for writing programs by dependent pattern-matching and (well-founded) recursion in Coq. It compiles everything down to eliminators for inductive types, equality and accessibility, providing a definitional extension to the Coq kernel.

- Example Code: http://mattam82.github.io/Coq-Equations/examples/

---

:+1: reactions _might_ help.

**Comment by kazk** [comment]
Deployed

**Comment by Bubbler-4** [comment]
(Un)related note: The latest CoqIDE on Windows (8.9.1, May 20, 2019) comes with Equations 1.2 bundled, so there's no problem testing code locally (at least on installing packages and syntax differences between Equations versions).

**Comment by kazk** [comment]
Cool, I'll ask for help when we need to update in the future. I only tried the `neg` example so let me know if you run into issues.
