### ISSUE TITLE
Add TLC package for Coq

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars-runner-cli#742]
The [TLC](https://www.chargueraud.org/softs/tlc/) package for Coq contains (among other things) a handy tactic library `LibTactics` featuring an improved set of tactics that can be used to drastically shorten proof scripts and increase the productivity of the experienced Coq user. Unlike SSReflect (another major Coq package) which was developed with proving mathematical theorems in mind, `LibTactics` in TLC is especially well-suited for the study of programming languages and therefore could come in handy in Kata such as [Evaluating the type safety of a toy language](https://www.codewars.com/kata/5cfd36be4c60c3001b8fb38a). Nontrivial examples of leveraging this tactic library can be found at [UseAuto](https://softwarefoundations.cis.upenn.edu/plf-current/UseAuto.html) of [PLF](https://softwarefoundations.cis.upenn.edu/plf-current/index.html).

To install:

```
$ opam install coq-tlc
```

Minimal example of using `LibTactics` from TLC:

```coq
From TLC Require Import LibTactics.

Inductive R : nat -> nat -> Prop :=
  | R_0_1 : R 0 1.

Example not_R_S_n_m : forall n m, ~ R (S n) m.
Proof.
  (* Duplicate current subgoal to demonstrate two ways to prove
     the same statement *)
  dup.

  (* Was ... *)
  intros n m H; inversion H.

  (* Is now ... *)
  introv H; inverts H.

Qed.
```

****

:+1: reactions *might* help

**Comment by kazk** [comment]
> Also I wonder when kazk will finally add TLC to Codewars ... 

I'd appreciate if you don't make a comment like this. This sounds like I've been ignoring the request for months. This issue was opened only 11 days ago and didn't have :+1: other than your own when I checked few times since it was opened.

---

Anyways, it's failing to install. The files doesn't seem to exist in expected path.
Any ideas?
```
The following actions will be performed:
  - install coq-equations 1.2+8.9
  - install coq-tlc       20181116
===== 2 to install =====

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[coq-tlc.20181116] downloaded from http://tlc.gforge.inria.fr/releases/tlc-20181116.tar.gz
[coq-equations.1.2+8.9] downloaded from https://github.com/mattam82/Coq-Equations/archive/v1.2-8.9.tar.gz

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The installation of coq-tlc failed at "make install".
-> installed coq-equations.1.2+8.9

#=== ERROR while installing coq-tlc.20181116 ==================================#
# context              2.0.4 | linux/x86_64 | ocaml-base-compiler.4.02.3 | http://coq.inria.fr/opam/released#2019-06-28 22:10
# path                 /opt/coq/ocaml-base-compiler.4.02.3/.opam-switch/build/coq-tlc.20181116
# command              /usr/bin/make install
# exit-code            2
# env-file             /opt/coq/log/coq-tlc-1-0c525f.env
# output-file          /opt/coq/log/coq-tlc-1-0c525f.out
### output ###
# make[1]: Entering directory '/opt/coq/ocaml-base-compiler.4.02.3/.opam-switch/build/coq-tlc.20181116/src'
# rm -rf /opt/coq/ocaml-base-compiler.4.02.3/lib/coq/user-contrib/TLC
# mkdir -p /opt/coq/ocaml-base-compiler.4.02.3/lib/coq/user-contrib/TLC
# install -m 644 *.v *.vo *.glob Makefile Makefile.coq /opt/coq/ocaml-base-compiler.4.02.3/lib/coq/user-contrib/TLC
# install: cannot stat '*.vo': No such file or directory
# install: cannot stat '*.glob': No such file or directory
# make[1]: *** [Makefile:46: install] Error 1
# make[1]: Leaving directory '/opt/coq/ocaml-base-compiler.4.02.3/.opam-switch/build/coq-tlc.20181116/src'
# make: *** [Makefile:8: install] Error 2
```

The page you linked is down.
![image](https://user-images.githubusercontent.com/639336/60467565-c8443f80-9c0b-11e9-8e8c-4effc27fa16c.png)

Installing with:
```
opam install \
  coq-equations.1.2+8.9 \
  coq-tlc.20181116 \
  ;
```

**Comment by DonaldKellett** [comment]
> I'd appreciate if you don't make a comment like this.

Apologies for my comment on the Gitter channel, it does indeed sound quite rude and inconsiderate now that I look at it again 😅 

> The page you linked is down.

I'm assuming the [TLC](https://www.chargueraud.org/softs/tlc/) link? That's rather unfortunate - I just checked 02/07/2019 14:03 (GMT +8) and the site is functioning as expected (as well as the other links I posted). Perhaps you could take a look at it again sometime?

> Anyways, it's failing to install ...

I haven't seen this issue when installing TLC on my Mac. I'll try to get back to you if I find out anything about it.

**Comment by DonaldKellett** [comment]
I just executed the command you posted on my Mac

```
opam install \
  coq-equations.1.2+8.9 \
  coq-tlc.20181116 \
  ;
```

and successfully installed Equations without encountering any issues (`opam` didn't bother re-installing TLC).  Anyway, the error message you posted reveals that the OCaml version Codewars(?) is currently using is `4.02.3` while the newest version is `4.08.0` (my OCaml version is `4.07.0`) - perhaps it might have something to do with this?

Anyway, I just found this site called [Coq bench](http://coq-bench.github.io) which benches a wide range of Coq OPAM packages including TLC - perhaps [this particular page](http://coq-bench.github.io/clean/Linux-x86_64-4.05.0-2.0.1/released/8.8.1/tlc/20181116.html) could help?

**Comment by kazk** [comment]
Thanks, I'll take a look at those pages later today.

**Comment by kazk** [comment]
OK, I got it installed and it should be working. The minimal example exits with zero and produces no output.

I'll close this when I deploy it. Probably within few days.

**Comment by kazk** [comment]
Deployed
