### ISSUE TITLE
Add lenses to purescript

### ISSUE THREAD

**Issue by glebec** [Codewars/codewars-runner-cli#743]
Both supported compiler versions for [Haskell](https://github.com/Codewars/codewars.com/wiki/Language-Haskell) include lens libraries. AFAICT PureScript currently does not enjoy the same capabilities.

I am not very knowledgeable on PureScript and its ecosystem, so I cannot say for sure what the best lens library to choose would be. I see these two:

- [`purescript-profunctor-lenses`](https://pursuit.purescript.org/packages/purescript-profunctor-lenses/6.2.0) updated 2019-04-08
- [`purescript-lens`](https://pursuit.purescript.org/packages/purescript-lens/4.0.0) updated 2018-10-10

The former (`purescript-profunctor-lenses`) looks more thorough to me, and includes common lenses OOB. It's what I'd be inclined to recommend offhand, but again, noob here.

**Comment by kazk** [comment]
Added `profunctor-lenses`.
