### ISSUE TITLE
C# 7.3 stdout is printed after failed test assertion

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#746]
Modified from the example code:

```cs
namespace Solution {
  using NUnit.Framework;
  using System;

  // TODO: Replace examples and use TDD development by writing your own tests

  [TestFixture]
  public class SolutionTest
  {
    [Test]
    public void MyTest()
    {
      for(int i=0; i<10; i++) System.Console.WriteLine(i);
      Assert.AreEqual("expected", "actual");
    }
  }
}
```

Mono 4.2.3 works fine:

![image](https://user-images.githubusercontent.com/14909989/60706260-a87a8780-9f3b-11e9-8655-cf6577a03380.png)

But C# 7.3 stdout is printed *after* failed test assertion:

![image](https://user-images.githubusercontent.com/14909989/60706184-7f59f700-9f3b-11e9-858e-cf3f3c367166.png)

**Comment by kazk** [comment]
Deployed the fix
