### ISSUE TITLE
Permit certain axioms in Coq?

### ISSUE THREAD

**Issue by Bubbler-4** [Codewars/codewars-runner-cli#747]
The current Coq runner does not allow any kind of axioms, even relatively standard ones. At least to me, the most critical ones are "proof irrelevance" used in Program Fixpoint and "functional extensionality" used in Equations. Both are great for writing non-trivially terminating functions, but sometimes they can't be used in the CW runner because the auto-generated definition includes one of the axioms.

To the best of my knowledge, allowing these axioms doesn't harm the integrity of existing katas (contrary to e.g. excluded middle which makes certain proofs trivial), and [allowing both does not automatically imply excluded middle](https://github.com/coq/coq/wiki/The-Logic-of-Coq).

Example using Program: (Note that Program doesn't give you reduction lemmas, so [you need to prove them manually using `fix_sub_eq`](https://stackoverflow.com/questions/36329256/coq-simpl-for-program-fixpoint). This is where the axiom is introduced.)

```coq
Require Import Arith Lia Program.
Program Fixpoint fib_prog (n : nat) {wf lt n} : nat :=
  match n with 0 => 0 | 1 => 1 | S (S n) => fib_prog (S n) + fib_prog n end.
Theorem fib0 : fib_prog 0 = 0.
Proof. auto. Qed.
Theorem fib1 : fib_prog 1 = 1.
Proof. auto. Qed.
Theorem fibSS : forall n, fib_prog (S (S n)) = fib_prog (S n) + fib_prog n.
Proof. intros. unfold fib_prog at 1. rewrite fix_sub_eq.
  - fold fib_prog. simpl. auto.
  - intros. destruct x as [ | [ | ]]; auto. Qed.
Print Assumptions fibSS.
(*
Axioms:
proof_irrelevance : forall (P : Prop) (p1 p2 : P), p1 = p2
*)
```

Example using Equations:

```coq
From Equations Require Import Equations.

Equations fibE (n : nat) : nat by wf n lt :=
fibE 0 := 0;
fibE 1 := 1;
fibE (S (S n)) := fibE (S n) + fibE n.
Check fibE_equation_3.
(*
fibE_equation_3
     : forall n : nat, fibE (S (S n)) = fibE (S n) + fibE n
*)
Print Assumptions fibE_equation_3.
(*
Axioms:
functional_extensionality_dep : forall (A : Type) (B : A -> Type) (f g : forall x : A, B x),
                                (forall x : A, f x = g x) -> f = g
*)
```

Someone might suggest to have a whitelist per kata, but I don't think it's really necessary because manual proof using axioms can be avoided with a premise to the theorem (or section hypothesis), and it's way too vulnerable to attacks.

### TL;DR

1. To Coq experts: Is it really safe to allow the two axioms for katas?
2. If so, can we have them allowed in the runner (mainly, the output post-processor)? Whitelisting the exact function signatures (modulo whitespace) should be enough.

**Comment by Bubbler-4** [comment]
@monadius @dramforever Do you have any thoughts?

**Comment by monadius** [comment]
I support the idea of allowing certain Coq axioms. In particular, I would be interested in creating some real analysis kata which cannot be done without assuming axioms of real numbers. But I'm not sure whether axioms should be allowed globally or not. It is quite possible that somebody decides to create a kata where assuming, for example, functional extensionality trivializes everything.

Ideally, I would like to be able to check inside Coq whether a given theorem depends on a given list of axioms. I am not a Coq expert so I don't know if it is possible to achieve without writing a Coq plugin in OCaml. But writing such a plugin should be not difficult (I hope) and then it could be deployed on Codewars.

**Comment by Bubbler-4** [comment]
The `Print Assumptions` command seems to run [this ML script](https://github.com/coq/coq/blob/a5e4dd7faa23abd4a4ebe093076484d090a8a47e/vernac/vernacentries.ml#L1981), using [`Assumptions.assumptions`](https://github.com/coq/coq/blob/459fc67f4a40ff82a7694f9afafb3ac303d74554/vernac/assumptions.ml#L298) which extracts assumptions and [`Printer.pr_assumptionset`](https://github.com/coq/coq/blob/82aa7ed1c929533f2b9e7acaa8264c5a81e7a45e/printing/printer.ml#L898) which prints messages based on the assumptions found.

I think we can try out a simplified version of `pr_assumptionset` with optional whitelist to test what we want. (cf. [ML plugin tutorial](https://project.inria.fr/coqexchange/a-small-tutorial-for-ocaml-plugins-to-extend-the-coq-system/) and [interface for `Map.Make`](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Map.Make.html).) That way we don't need an external post-processor anymore, as we can directly print `<PASSED::>` or `<FAILED::>` or whatever; we could even add a command for `<DESCRIBE::>` (when many theorems are being tested in one kata, it's nice to add titles or group them by some categories). We might need some experiments on how to pass a list of identifiers to the ML plugin.

**Comment by Bubbler-4** [comment]
[More up-to-date and (probably) official plugin tutorial.](https://github.com/coq/coq/tree/master/doc/plugin_tutorial)

**Comment by monadius** [comment]
I have created a [prototype plugin](https://github.com/monadius/coq_codewars) for testing assumptions. A small example:

```coq
From CW Require Import Loader.
From Coq Require Import Classical.

Lemma lemma : (2 = 3) \/ ~(2 = 3).
Proof.
apply classic.
Qed.
  
Fail CWTest lemma Assumes.
CWTest lemma Assumes classic.
CWTest lemma Assumes classic proof_irrelevance.
```

Feedback, testing, and contributions are welcome.

**Comment by kazk** [comment]
Sounds good, but I don't know Coq enough to contribute.

Does it need any changes other than including the plugin? Just `coqc` when testing?

I think we can have different "modes" if necessary. Maybe some special comment in `Preloaded.v` can be used as a switch to use this plugin and leave existing kata as is.

**Comment by monadius** [comment]
When the plugin is ready it should be easy to use it. The plugin should be compiled and then it is enough to add one extra parameter to `coqc`: the compiled plugin location (`coqc -I [path_to_plugin]`).

I don't think it is necessary to have any special options in `Preloaded.v`. Kata authors can decide whether they want to use this plugin or not by loading (or not loading) the corresponding plugin declaration file (currently called `Loader.v`); the plugin is not loaded by default. I also think that the plugin should not be allowed in user solutions. This means that user solutions should be compiled without `-I [path_to_plugin]`.

**Comment by Bubbler-4** [comment]
Feature request:

* Let the `CWTest` command print `\n<PASSED::> (message)\n` and `\n<FAILED::> (message)\n` directly, then it doesn't interfere with the post-processor (I think).
* Could you add `CWGroup` and `CWEndGroup` or something similar to print `\n<DESCRIBE::> (message)\n` and `\n<COMPLETEDIN::>\n` ? (All the newlines are intentional, for proper formatting on CW test results window.)

---

Probably we should organize a folder structure to achieve one-way dependency:

* `src`: `Preloaded.v` and `Solution.v`
* `test`: Test library (the ML plugin, and `Check.v`) and `Tests.v` (are the file names right?)

**Comment by monadius** [comment]
@Bubbler-4: I added `CWGroup` and `CWEndGroup`. I also changed `CWTest` and it now prints `<PASSED::>` and `<FAILED::>`. This command still fails (yields a Coq error) when the tested constant contains extra axioms. But maybe it is better to print `<FAILED::>` and continue without any errors?

**Comment by Bubbler-4** [comment]
I guess the failing behavior is fine as-is, unless it interferes with the post-processor.

**Comment by kazk** [comment]
`theories/Demo2.v`? It shouldn't interfere with the post processor.

So to use this, we need to:

1. `coq_makefile -f _CoqProject -o Makefile && make`
2. `coqc -I plugin_dir loader_dir/Loader.v`
3. `coqc Check.v`
4. `coqc Preloaded.v` if provided
5. `coqc Solution.v`
6. `coqc -I plugin_dir -R loader_dir CW SolutionTest.v`

1-3 are done when building the image to avoid doing on every submission.

We can organize the folder structure. Do we need to add `-Q src ""` or something? I skimmed through https://github.com/coq/coq/wiki/CoqPaths but it's confusing. If we're doing that, I think we can put `Loader.v` in `test/Loader.v` and do `coqc -I plugin_dir -R test/ CW test/SolutionTest.v`.

**Comment by monadius** [comment]
The [plugin](https://github.com/monadius/coq_codewars) is ready. The required files are: `src/coq_cw.ml`, `src/cow_cw.mli`, `src/coq_cw_plugin.mlpack`, `src/g_cow_cw.ml4`, and `theories/Loader.v` (not strictly required but it is better to encapsulate the command for loading the plugin inside this file). The plugin can be built with the command:

```
coq_makefile -f _CoqProject -o Makefile && make
```
This command builds the plugin and `Loader.vo` (I removed `Demo.v` from `_CoqProject`).

It is also possible to add `Check.v` to `_CoqProject`. Then it will be not required to run `coqc Check.v` afterwards.

Solution and test files can be built with the following commands:
```
coqc Preloaded.v
coqc Solution.v
coqc -I plugin_dir -Q loader_dir CW SolutionTest.v
```
Options `-Q` and `-R` are almost identical but `-Q` requires a fully qualified path and I think it is better to be explicit when loading the plugin. That is, with `-R` it is possible to write `Require Import Loader` but `-Q` requires `CW`: `From CW Require Import Loader` or `Require Import CW.Loader`.

@kazk: is this path correct `let solution_file = "/workspace/Solution.v"`? This is the default path for `CWFile` commands.

**Comment by kazk** [comment]
Yeah, that's the correct path at the moment. I'm also going to write it to `/workspace/solution.txt` like other languages. That might be a better default so changing the folder structure in the future won't affect tests.

I got the example (`cw_example`) working. The output is
```
<PASSED::> Testing solution
```

Do you want to move the repo to https://github.com/Codewars/coq_codewars ?

**Comment by monadius** [comment]
It is a good idea to move the repository to the Codewars account.

**Comment by kazk** [comment]
To transfer to `Codewars` org, I think we need to first transfer to my account (`kazk`) first. Then I can transfer into `Codewars` since I have the permission to create a repository here.

See https://help.github.com/en/articles/transferring-a-repository#repository-transfers-and-organizations for the details.

So can you transfer it to my account?

---

`theories/Demo.v` should look something like this (added `CWFile tests` group):

![image](https://user-images.githubusercontent.com/639336/61180131-6352f700-a5c6-11e9-9331-5dd6563a4992.png)

**Comment by monadius** [comment]
@kazk: I started the transfer process to your account.

**Comment by kazk** [comment]
Transferred to https://github.com/Codewars/coq_codewars :tada:

**Comment by kazk** [comment]
Thanks @monadius! Examples from the repository seems to be working and it shouldn't affect existing kata.
I'll close this and #748 when it's deployed. Probably on Monday.

**Comment by kazk** [comment]
Deployed :tada:
If you find any issues, please report to https://github.com/Codewars/coq_codewars.
