### ISSUE TITLE
Get user code in Coq

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#748]
For, you know, Coq golf katas.

**Comment by kazk** [comment]
Can you tell me what needs to be done? Does it need some external code written in OCaml? Maybe this can be part of #747?

The solution is written to `/workspace/Solution.v`. I can duplicate that to `/workspace/solution.txt` like other languages if necessary for some reason.

**Comment by Voileexperiments** [comment]
> Does it need some external code written in OCaml? Maybe this can be part of #747?

Most probably yes, Coq doesn't have any IO functionality as IO actions do not guaranteed to terminate.

It's mostly related to #747 but I decided to open a separate issue since it's fundamentally about something different.

**Comment by monadius** [comment]
@Voileexperiments: is it enough to implement the following commands for testing user solutions:
1) Testing that the solution code size is less than a given number.
2) Testing that the solution contains (does not contain) certain words (more generally, testing solutions with regular expressions).

I can implement these two commands in the [plugin](https://github.com/monadius/coq_codewars) which I created for #747. Getting user solutions as strings is also possible but it is harder to implement.

**Comment by Voileexperiments** [comment]
I think these two are good for now. *Maybe* someone will come up with crazier ideas but before the kata meta reaches that point, it's more than enough.

(The second one is probably useful for detecting usage of certain tactics for whatever reasons that'd make it necessary, I'll let others figure that out for me I suppose.)

**Comment by monadius** [comment]
I [added](https://github.com/monadius/coq_codewars/commit/0ef1588da579e765f554fb4ba2f917e013b6c290) new plugin commands for testing user solutions. An excerpt from [Demo.v](https://github.com/monadius/coq_codewars/blob/master/theories/Demo.v):

```coq
CWFile "theories/Demo.v" Size < 1000.
Fail CWFile "theories/Demo.v" Size < 200.

CWFile "theories/Demo.v" Matches "Axiom".
Fail CWFile "theories/Demo.v" Matches "$Theorem".

Fail CWFile "theories/Demo.v" Does Not Match "Axiom".
CWFile "theories/Demo.v" Does Not Match "$Theorem".
```
The file name is optional. The default file is `/workspace/Solution.v`.

**Comment by kazk** [comment]
Deployed :tada:
If you find any issues, please report to https://github.com/Codewars/coq_codewars.
