### ISSUE TITLE
Add Nim v1.0

### ISSUE THREAD

**Issue by alaviss** [Codewars/codewars-runner-cli#750]
- Name: Nim
- Version: 1.0.0
- Release Note/Changelog:
  - https://nim-lang.org/blog/2019/06/06/version-0200-released.html
  - https://nim-lang.org/blog/2019/07/17/version-0202-released.html
  - https://nim-lang.org/blog/2019/09/23/version-100-released.html

---

:+1: reaction _might_ help.

**Comment by kazk** [comment]
Deployed and enabled Nim 1.0 for compatible kata.

We currently have 13 incompatible ones and those are listed on https://github.com/Codewars/codewars.com/wiki/List-of-Nim-Kata-to-Update-to-1.0
