### ISSUE TITLE
Rust users need some way to set up their dependencies

### ISSUE THREAD

**Issue by Souzooka** [Codewars/codewars-runner-cli#755]
Currently, there seems to be no way to extern crates not hardloaded in by Codewars (and this might only be `rand`, not sure what Codewars has loaded).

Since there is no way to add crates and many features that are normally in the standard library of another language are not in the standard library of Rust, Rust is a lot less powerful than it normally is. For example, Rust users cannot use any regular expressions as this is an external crate.

**Comment by kazk** [comment]
@AHeavner it's been used on Codewars. The packages installed are listed in https://github.com/Codewars/codewars.com/wiki/Language-Rust#125133-1

We're not letting users specify dependencies, but we're accepting requests. If you have anything you need, please open an issue here following the template provided.
