### ISSUE TITLE
Is NLL enable for Rust?

### ISSUE THREAD

**Issue by weiby3** [Codewars/codewars-runner-cli#759]
#### Describe the bug
In this [kata](https://www.codewars.com/kata/primes-in-numbers), it seems that NLL is not enable for Rust.

#### To Reproduce
Attempt the following code as rust code:
```rust
fn is_prime(n: i64) -> bool {
    if n < 2 { return false; }
    if n == 2 { return true; }
    let mut i = 3i64;
    while i.pow(2) <= n {
        if n % i == 0 {
            return false;
        }
        i += 2
    }
    true
}

fn set_to_string(v: std::collections::BTreeMap<i64, i64>) -> String {
    v.iter().map(
        |(&num, &count)| {
            if count > 1 {
                format!("({}**{})", num, count)
            } else {
                format!("({})", num)
            }
        }
    ).collect()
}

fn prime_factors(n: i64) -> String {
    let mut set = std::collections::BTreeMap::new();
    if is_prime(n) {
        set.insert(n, 1);
    } else {
        let mut n = n;
        let mut i = 2i64;
        while n % i == 0 {
            match set.get_mut(&i) {
                Some(v) => *v += 1,
                None => { set.insert(i, 1); }
            }
            n /= i;
        }
        i += 1;
        while i <= n {
            if is_prime(i) {
                while n % i == 0 {
                    match set.get_mut(&i) {
                        Some(v) => *v += 1,
                        None => { set.insert(i, 1); }
                    }
                    n /= i;
                }
            }
            i += 2
        }
    }
    set_to_string(set)
}
```

#### Expected Behavior
Compile pass. Test in local rust stable 1.33 and it compiles. But I got compile error in codewars.
Here is the output:
```
error[E0499]: cannot borrow `set` as mutable more than once at a time
  --> src/lib.rs:36:27
   |
34 |             match set.get_mut(&i) {
   |                   --- first mutable borrow occurs here
35 |                 Some(v) => *v += 1,
36 |                 None => { set.insert(i, 1); }
   |                           ^^^ second mutable borrow occurs here
37 |             }
   |             - first borrow ends here

error[E0499]: cannot borrow `set` as mutable more than once at a time
  --> src/lib.rs:46:35
   |
44 |                     match set.get_mut(&i) {
   |                           --- first mutable borrow occurs here
45 |                         Some(v) => *v += 1,
46 |                         None => { set.insert(i, 1); }
   |                                   ^^^ second mutable borrow occurs here
47 |                     }
   |                     - first borrow ends here

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0499`.


NOTE: Line numbers in error messages can be incorrect due to concatenation.
```
#### Contexts

Please complete the following information:

- OS: [e.g. macOS] Windows 7
- Browser: [e.g. chrome, safari] Chrome
- Browser Version: [e.g. 22] 69

**Comment by kazk** [comment]
> Compile pass. Test in local rust stable 1.33 and it compiles. But I got compile error in codewars.

Can you try `rustc --test src/lib.rs`? This fails with the same error with my local installation (mine is 1.35 though).
You can also add some tests like Codewars does.

The output with `--explain E0499` is
````
A variable was borrowed as mutable more than once. Erroneous code example:

```
let mut i = 0;
let mut x = &mut i;
let mut a = &mut i;
// error: cannot borrow `i` as mutable more than once at a time
```

Please note that in rust, you can either have many immutable references, or one
mutable reference. Take a look at
https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html for more
information. Example:


```
let mut i = 0;
let mut x = &mut i; // ok!

// or:
let mut i = 0;
let a = &i; // ok!
let b = &i; // still ok!
let c = &i; // still ok!
```
````

**Comment by kazk** [comment]
I did some research and it turns out that we need to opt-in to 2018 edition in order to enable NLL.

- https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html#rust-2018
- https://doc.rust-lang.org/cargo/reference/manifest.html#the-edition-field-optional

I'll add it and check compatibility with existing contents first.

**Comment by weiby3** [comment]
If you want to stay on 2015 edition, you can upgrade to 1.36, it port NLL to 2015 edition.
- https://blog.rust-lang.org/2019/07/04/Rust-1.36.0.html#nll-for-rust-2015

**Comment by kazk** [comment]
Is there any reason not to use 2018 edition for new code?

Looks like some kata breaks if we use Rust 2018 because of the changes around [path](https://doc.rust-lang.org/stable/edition-guide/rust-2018/module-system/path-clarity.html). It's not many so it should be quick to update.

I might just add Rust 1.36 with Rust 2018 first. I finished updating all kata to 1.33 so we can drop 1.15/1.25 and replace them with 1.36.

**Comment by weiby3** [comment]
> Is there any reason not to use 2018 edition for new code?

No, unless it is for compatibility. Or there are not enough people to maintain the legacy code.
I suggest to migrade to 2018 if you can migrade the 2015 code to 2018.
Your solution looks good.

**Comment by kazk** [comment]
Added Rust 1.36 with Rust 2018. 15 kata are not compatible, but others now default to it.

I made a [list of kata to update](https://github.com/Codewars/codewars.com/wiki/List-of-Rust-1.33-Kata-to-Update) and will be fixing it.
