### ISSUE TITLE
Add scala cats and cats-effect

### ISSUE THREAD

**Issue by oybek** [Codewars/codewars-runner-cli#762]
Guys, it will be Great if you'll include cats-core and cats-effect libraries to scala!!! 😊

Will be very usefull when solving problem and learning fp at the same time.

P. S. Not so technically hard to add them.

---

- https://github.com/typelevel/cats
- https://github.com/typelevel/cats-effect

**Comment by kazk** [comment]
- https://github.com/typelevel/cats
- https://github.com/typelevel/cats-effect

**Comment by kazk** [comment]
I'll update Scala to 2.13+ first so we don't need to worry about adding compiler flags.

**Comment by kazk** [comment]
The runner now supports Scala 2.13 and added `cats-core`/`cats-effect` `2.0.0-RC1` (will update when they release 2.0.0).

I'll enable Scala 2.13 on Codewars later next week and I'll close this issue when I do.

**Comment by kazk** [comment]
Deployed. Currently 180 kata has Scala 2.13 support.
I'll create a list of 2.12 only kata that needs help updating manually.

**Comment by Steffan153** [comment]
@kazk All 2.12 kata are updated now.

**Comment by kazk** [comment]
Thanks!
