### ISSUE TITLE
Add Typed Racket support for Racket

### ISSUE THREAD

**Issue by yfzhe** [Codewars/codewars-runner-cli#764]
- Name: typed/racket
- Language Name: Racket
- Website: https://pkgs.racket-lang.org/package/typed-racket-lib

Typed Racket is gradual typing variant of racket. We can write static typing programs with it.

---

:+1: reactions _might_ help.

**Comment by kazk** [comment]
This can be done by simply installing `typed-racket-lib` right?

Then current
```racket
#lang racket
(provide add)

(define (add a b) (+ a b))
```
can also be written with types:
```racket
#lang typed/racket
(provide add)

(: add (-> Integer Integer Integer))
(define (add a b) (+ a b))
```

**Comment by yfzhe** [comment]
Yes.

It seems that the racket environment codewars using is minimal-racket, which lacks `typed-racket-lib`. So installing it is the solution.

**Comment by kazk** [comment]
Cool. Just wanted to make sure I wasn't misunderstanding.

Yeah, it's using minimal-racket because the default installation includes a lot of things that's never going to be used and makes the container image much larger.

I'll close this when I deploy it.

**Comment by kazk** [comment]
Deployed
