### ISSUE TITLE
Add list-extra for Elm

### ISSUE THREAD

**Issue by Steffan153** [Codewars/codewars-runner-cli#766]
`list-extra` simplifies many tasks for Lists in Elm. Pretty useful, and I think it would be nice to add to CW. :slightly_smiling_face: 

- Name: `list-extra`
- Language Name: Elm
- Website: https://package.elm-lang.org/packages/elm-community/list-extra/latest
- It has convenience functions for working with List.

---

:+1: reactions _might_ help.

**Comment by kazk** [comment]
Thanks for doing Elm translations. Elm was wanted by many (#520) and wasn't very easy to add, but it hasn't been used much so far :( I'm happy to see more Elm kata on Codewars.

I'll also add [elm-community/random-extra](https://package.elm-lang.org/packages/elm-community/random-extra/3.1.0) and close this when it's deployed.

**Comment by Steffan153** [comment]
Some other extras BTW: [string-extra](https://package.elm-lang.org/packages/elm-community/string-extra/latest/), [maybe-extra](https://package.elm-lang.org/packages/elm-community/maybe-extra/latest/), [array-extra](https://package.elm-lang.org/packages/elm-community/array-extra/latest/), [basics-extra](https://package.elm-lang.org/packages/elm-community/basics-extra/latest/), and [dict-extra](https://package.elm-lang.org/packages/elm-community/dict-extra/latest/)

**Comment by kazk** [comment]
I wish Elm Packages shows some statistics like the number of downloads or sort by popularity or something. I can add those too.

`list-extra` and `random-extra` should be available on preview.codewars.com if you want to try. I installed them but didn't test :p
I'll comment here when I deploy those to production. Other extras will be added later.

**Comment by Steffan153** [comment]
`List.Extra` works good. I haven't tested `Random` yet as the built-in fuzzers have been enough... thanks!

**Comment by kazk** [comment]
Deployed `list-extra` and `random-extra`. I'll close this because the original request is done, but I'll let you know when I add other extras.
Feel free to bump this issue if I don't update after more than a week and especially if you need those.

**Comment by kazk** [comment]
Added other extras mentioned above and deployed it
