### ISSUE TITLE
Add purescript-debug for PureScript

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars-runner-cli#776]
Please complete the following information about the package:

- Name: purescript-debug
- Language Name: PureScript
- Website: https://pursuit.purescript.org/packages/purescript-debug/4.0.0

Following are optional, but will help us consider adding:

- Why is this useful? Debugging in a purely functional language such as PureScript is a PITA without debugging packages such as purescript-debug (equivalent to [Debug.Trace](http://hackage.haskell.org/package/base-4.12.0.0/docs/Debug-Trace.html) in Haskell). Inclusion of this package also makes PureScript on par with Haskell in this regard on Codewars.
- Example Code: see https://pursuit.purescript.org/packages/purescript-debug/4.0.0/docs/Debug.Trace for detailed documentation

---

:+1: reactions _might_ help.

**Comment by kazk** [comment]
Deployed
