### ISSUE TITLE
Prolog tests incorrectly report passed and failed cases

### ISSUE THREAD

**Issue by FArekkusu** [Codewars/codewars-runner-cli#778]
I'm not sure whether this is an issue with the runner or simply a bad test setup, but I found a strange/wrong behavior while checking [this Prolog translation](https://www.codewars.com/kumite/5e1484ba464ddd00315ce9af?sel=5e1484ba464ddd00315ce9af).

A solution which fails the random tests results in a `Test Passed` message with `Exit Code: 1`, at the same time there're no messages about failed assertions, so it's impossible to tell what's happening:

![image](https://user-images.githubusercontent.com/31668662/71899550-a7cde280-3164-11ea-8f92-4a0460ded653.png)

But if I add `write("\n")` inside the random tests block, the "assertion failed" messages do appear, but the `Test Passed` message still remains:

![image](https://user-images.githubusercontent.com/31668662/71899702-ed8aab00-3164-11ea-922d-a4aecfa9ed98.png)

___

Not sure whether that's related, but if I add `write("\n")` inside the solution, a similar thing happens with the fixed tests:

![image](https://user-images.githubusercontent.com/31668662/71900964-92a68300-3167-11ea-9cd7-612b379e220c.png)

![image](https://user-images.githubusercontent.com/31668662/71901086-d4cfc480-3167-11ea-8a0e-14732cf079aa.png)

![image](https://user-images.githubusercontent.com/31668662/71901161-00eb4580-3168-11ea-9320-60abe2327ad9.png)

**Comment by kazk** [comment]
Thanks for reporting with all the details. I had assumed that each `ERROR` starts at new line from the outputs I had seen, so that's probably the cause.

**Comment by kazk** [comment]
Fixed. I wasn't aware of `forall bindings`. It should now display like the following:

![image](https://user-images.githubusercontent.com/639336/71943989-47946c00-3177-11ea-98c1-71c9ebbf2378.png)
