### ISSUE TITLE
Prolog solutions can be bypassed

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#780]
#### Describe the bug

The Kumite runner says

![image](https://user-images.githubusercontent.com/1063901/72777021-d377b080-3bd9-11ea-9f62-0bda9856fcb2.png)

however, they are not being validated as expected showing that the test passes:

![image](https://user-images.githubusercontent.com/1063901/72777049-ee4a2500-3bd9-11ea-9bb1-86b4893e03a3.png)

This is because **the exit code** is not being taken into account for Kumites and Katas.

#### To Reproduce

Please check [this private kumite](https://www.codewars.com/kumite/5e268489a01d9e002812ffb4?sel=5e268489a01d9e002812ffb4)

#### Expected Behavior

Very similar to the Kumite editor

![image](https://user-images.githubusercontent.com/1063901/72777151-4719bd80-3bda-11ea-8537-1afdd08c19ea.png)

however, a red marked message should be shown saying that error code has been found and your solution will not pass.

And actually I'd expect to see the output code in the top bar of the Kata runner

![image](https://user-images.githubusercontent.com/1063901/72777306-cf985e00-3bda-11ea-9a30-2e691c523f5e.png)

**Comment by javatlacati** [comment]
If you need another example: [this solution](https://www.codewars.com/kata/reviews/5e265645c551ab0001ecd381/groups/5e267e1ec551ab0001ecdec9) passes even if the error in console is:

> ERROR: /workspace/greet.plt:2:
	load_files/2: No permission to load source

**Comment by kazk** [comment]
Error in test:
![image](https://user-images.githubusercontent.com/639336/72862433-f8276300-3c81-11ea-83fa-cddd0ffaf02e.png)

Failing to load:
![image](https://user-images.githubusercontent.com/639336/72862478-23aa4d80-3c82-11ea-8b37-1683093caaf0.png)
