### ISSUE TITLE
Consider using custom expectation messages in CFML/Testbox

### ISSUE THREAD

**Issue by bdw429s** [Codewars/codewars-runner-cli#784]
#### Describe the ~bug~ _feature_

Not really a bug, but I didn't see an option for a feature :slightly_smiling_face:   The way some of the test cases are written in the CFML track can be difficult to debug since there are more than one expectation in a given spec, so you don't know which expectation failed.  There are two options to deal with this:

1. Use a separate spec ( `it()` block ) for each separate test
2. Use a custom message in each expectation.

To expand on No 2, the following expectation
```js
expect(SUT.isDivisible(12, 3, 4)).toBe(true);
```
looks like this when it fails:
```
Expected [true] Actual [false]
```
which makes it indistinguishable from the other expectations who expected a true "actual" value.

However, a custom message can be provided like so:
```js
expect(SUT.isDivisible(12, 3, 4)).toBe(true, '12 divisible by 3 and 4');
```
which fails more descriptively like so:
```
12 divisible by 3 and 4. Expected [true] Actual [false]
```

The downside of this is it adds more code to the tests and doesn't read as clean.  You can decide if you think it's worth the effort, but now would be a good time to start doing this before we get too many katas implemented in the CFML track.

**Comment by kazk** [comment]
Please comment on the kata discussion page and let the translator know. Any content related issues are handled on Codewars' discussion pages.

Before approving this `isDivisible` kata, I had asked the translator to add the custom message and apparently it was only added to random tests.

**Comment by kazk** [comment]
@Steffan153 can you improve your translations?

**Comment by Steffan153** [comment]
@kazk Fixed all.
