### ISSUE TITLE
Prolog tests expecting failure format output incorrectly

### ISSUE THREAD

**Issue by error256** [Codewars/codewars-runner-cli#792]
https://www.codewars.com/kumite/5e3ef89faf934e0010a8c2c0
The 3rd test failed, but the message is shown as plain stderr output and the test is green.
![image](https://user-images.githubusercontent.com/5375100/74090000-a31b8780-4a9e-11ea-8b92-393903ff874a.png)

**Comment by kazk** [comment]
Thanks, Prolog's plunit is supported by post processing the failure messages so this happens when the failure message has a format it doesn't know.

`must fail but succeeded in` is new. I wish there's a full list of possible messages.

**Comment by kazk** [comment]
Deployed the fix
