### ISSUE TITLE
C++ runner fails on trivial compiler warnings

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars-runner-cli#795]
Using C++ code by default has some flags which are annoying to say the least. The following warnings cause the compilation to fail, which I think is draconian:
1. warning: '&&' within '||' [-Wlogical-op-parentheses] i.e.
a = b || c && d;
does not compile (Hint: why did they invent operator precedence back in the 70s?)
2. using the result of an assignment as a condition without parentheses [-Wparentheses] i.e.
if (tmp=fun(x)) g(tmp);
does not compile (Hint: why is variable assignment an expression and not a statement?)
3. warning: expression result unused [-Wunused-value]
who cares?

Note that the exact same code will compile in a C code runner.

Please remove failure on compiler warnings. If not, at least remove the above flags.

**Comment by error256** [comment]
I don't know if (1) has ever helped anyone, I don't like it too, but (2) is helpful because it often is a typo and (3) probably can be helpful too sometimes. So disabling warnings isn't good.
I think not failing on warnings in the tests results in the warning being shown to users when they submit solutions; that might be the reason why they are treated like errors?
A common convention for disabling (2) in a specific piece of code is extra parentheses (`if ((tmp=fun(x)))`). Or in this case `if (auto tmp = fun(x))` would be even better in C++.
A common convention for disabling (3) is casting the result to `void`. Depending on how exactly you got the warning, `[[maybe_unused]]` may be useful too.

**Comment by nomennescio** [comment]
It's not that some warning might be helpful to some people, it's that it's being forced upon everyone. In this case this only happens with C++, NOT with the exact same code when submitted in the C code runner. If you want warnings, fine, just don't fail the compilation because of them.

**Comment by hobovsky** [comment]
I checked both C++14 and C++17 and warnings do not fail compilation for a couple of kata I tested:

![image](https://user-images.githubusercontent.com/23709795/76231708-e98f0e00-6225-11ea-933f-c1ae84d55eca.png)

For which kata did your compilation fail due to warnings?

**Comment by error256** [comment]
I thought warnings in the tests are like errors, but it doesn't seem so. So I don't know...
Although I wouldn't mind this behavior because, as I said, if there are warnings in the tests, everyone will see them when solving the kata.
Anyway, warning can be turned off as always:
```cpp
#pragma clang diagnostic ignored "-Wlogical-op-parentheses"
#pragma clang diagnostic ignored "-Wparentheses"
#pragma clang diagnostic ignored "-Wunused-value"
```

**Comment by kazk** [comment]
Warnings should not cause compilation failure nor test failure and it's only expanded on failure so you can ignore them if you don't care when you pass. It's mainly there to help you on failure or if you want your solution to be free of warnings.

For C++ vs C, both C++17 and C18 have `-Wall -Wextra`. Those flags might be enabling different sets of warnings, but I don't understand the need for them to match.

Please let me know if you have an example I can take a look at for warnings causing failure.

**Comment by nomennescio** [comment]
OK, so maybe I need to rephrase this; upon further inspection it does seem the compilation does indeed not fail if there is not at least one error in it, but stderr still shows up when running tests. If that is somewhat harmless, than that's OK.
