### ISSUE TITLE
Update Coq to 8.11

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars-runner-cli#796]
Coq 8.10.0 added `a new simplex-based proof engine for the tactics lia, nia, lra and nra`. This made some proofs that previous caused infinite loop and memory leak to be solved immediately:

```
Lemma quadratic_root_prop : forall b c x1 x2,
    x1 * x1 + c = b * x1 /\ x2 * x2 + c = b * x2 ->
    x1 <> x2 ->
    x1 + x2 = b /\ x1 * x2 = c.
Proof.
  intros. nia.
Qed.
```

In CW and my local environment running Coq 8.9.0 the proof is stuck with ever growing memory usage at the `nia.` tactic. Then I updated my local Coq to 8.11.0 and it's solved immediately.

**Comment by Voileexperiments** [comment]
Paging @Bubbler-4 @monadius because I'm not too faimilar with this stuff

**Comment by monadius** [comment]
It is a good idea to update Coq to 8.11.0. The first thing to do is to test the coq_codewars plugin with this version. I will test it when I have time later this week.

**Comment by DonaldKellett** [comment]
Just to confirm, we could still enable support for Coq 8.9 (like how we support two versions of Python at any given time), right? Asking because last time I checked (maybe a month or two ago), the corresponding CoqIDE for Coq 8.10+ uses GTK 3 (or whatever that graphics thing is called) instead of the GTK 2 used in CoqIDE <=8.9 which wasn't exactly stable yet so there were quite a few bugs in the UI, e.g. various icons not displaying properly.

I guess once the UI bugs in the latest CoqIDE are fixed then Coq 8.9 support can be scheduled for removal.

**Comment by Voileexperiments** [comment]
> Just to confirm, we could still enable support for Coq 8.9 (like how we support two versions of Python at any given time), right? Asking because last time I checked (maybe a month or two ago), the corresponding CoqIDE for Coq 8.10+ uses GTK 3 (or whatever that graphics thing is called) instead of the GTK 2 used in CoqIDE <=8.9 which wasn't exactly stable yet so there were quite a few bugs in the UI, e.g. various icons not displaying properly.
> 
> I guess once the UI bugs in the latest CoqIDE are fixed then Coq 8.9 support can be scheduled for removal.

Retaining Coq 8.9 because *CoqIDE* has been updated isn't exactly a good reason; there are other alternatives to CoqIDE like Proof General, and I think CoqIDE is independent to the libraries which are in the `lib/` folder.

**Comment by monadius** [comment]
I updated the plugin. All changes are in the [coq8.11](https://github.com/Codewars/coq_codewars/tree/coq8.11) branch.

I tested everything with OCaml 4.07.1 (OCaml >= 4.05.0 is required for Coq 8.11). I don't think it is necessary to keep Coq 8.9. There are some compatibility issues with existing kata but I expect that it will be easy to fix them (for instance, there are new real number axioms in Coq 8.11 so real number kata must be updated).

**Comment by kazk** [comment]
I'm trying to build a new image for Coq 8.11 and failing because of `coq-tlc`:

```
The following dependencies couldn't be met:
  - coq-tlc -> coq < 8.11
      not available because the package is pinned to version 8.11.0
```
- `coq-equations` is updated to `1.2.1+8.11`
- `coq-mathcomp-ssreflect` is updated to `1.10.0`
- `coq-tlc` doesn't have newer version

**Comment by kazk** [comment]
I built the image without `coq-tlc` and tried v8.11.
Only the following 9 kata failed:

1. [A special set of matrices with convertible representations](https://www.codewars.com/kata/5d03d84ca535d50001845e9c)
    ```
    <ERROR::>The reference x was not found in the current environment.<:LF:>File "./Solution.v", line 32, characters 16-17
    ```
1. [Efficient Fibonacci: proof and extraction](https://www.codewars.com/kata/5e2e66e8948634002d33e560)
    ```
    <ERROR::>Found no subterm matching "Z.of_nat (Z.to_nat ?M1920)" in the current goal.<:LF:>File "./Solution.v", line 55, characters 19-43
    ```
1. [EM implies LPO, LPO implies LLPO](https://www.codewars.com/kata/5cc29e3128b420000c85cc19)
    ```
    File "./Solution.v", line 8, characters 51-87:
    Error: No such contradiction
    ```
1. [Program Verification #5: The sum of a geometric progression](https://www.codewars.com/kata/5cc3d8c2312133001dea9b3d)
    ```
    <ERROR::>Tactic failure:  Cannot find witness.<:LF:>File "./Solution.v", line 9, characters 2-66
    ```
1. [Real Chebyshev](https://www.codewars.com/kata/5d2bd8e414a6ef001a0421d2)
    ```
    <DESCRIBE::>cheb_cos tests
    <IT::>cheb_cos type
    <PASSED::>Type Test
    <COMPLETEDIN::>0.59
    <IT::>cheb_cos assumptions
    <FAILED::>Real Number Axioms<:LF:>Prohibited Axioms: ClassicalDedekindReals.sig_not_dec : forall P : Prop, {~ ~ P} + {~ P}<:LF:>ClassicalDedekindReals.sig_forall_dec : forall P : nat -> Prop,<:LF:>                                        (forall n : nat, {P n} + {~ P n}) -><:LF:>                                        {n : nat | ~ P n} +<:LF:>                                        {forall n : nat, P n}<:LF:>FunctionalExtensionality.functional_extensionality_dep : <:LF:>forall (A : Type) (B : A -> Type) (f g : forall x : A, B x),<:LF:>(forall x : A, f x = g x) -> f = g
    <COMPLETEDIN::>2946.28
    <COMPLETEDIN::>2946.95

    File "./SolutionTest.v", line 11, characters 4-338:
    Error:
    Real Number Axioms
    Prohibited Axioms: ClassicalDedekindReals.sig_not_dec : forall P : Prop, {~ ~ P} + {~ P}
    ClassicalDedekindReals.sig_forall_dec : forall P : nat -> Prop,
                                            (forall n : nat, {P n} + {~ P n}) ->
                                            {n : nat | ~ P n} +
                                            {forall n : nat, P n}
    FunctionalExtensionality.functional_extensionality_dep : 
    forall (A : Type) (B : A -> Type) (f g : forall x : A, B x),
    (forall x : A, f x = g x) -> f = g
    ```
1. [Real Fibonacci](https://www.codewars.com/kata/5d2b89d4b90c0a001f4a6456)
    ```
    <IT::>binet type
    <PASSED::>Type Test
    <COMPLETEDIN::>0.69
    <IT::>binet assumptions
    <FAILED::>Real Number Axioms<:LF:>Prohibited Axioms: ClassicalDedekindReals.sig_not_dec : forall P : Prop, {~ ~ P} + {~ P}<:LF:>ClassicalDedekindReals.sig_forall_dec : forall P : nat -> Prop,<:LF:>                                        (forall n : nat, {P n} + {~ P n}) -><:LF:>                                        {n : nat | ~ P n} +<:LF:>                                        {forall n : nat, P n}<:LF:>FunctionalExtensionality.functional_extensionality_dep : <:LF:>forall (A : Type) (B : A -> Type) (f g : forall x : A, B x),<:LF:>(forall x : A, f x = g x) -> f = g
    <COMPLETEDIN::>2468.12

    File "./SolutionTest.v", line 11, characters 0-307:
    Error:
    Real Number Axioms
    Prohibited Axioms: ClassicalDedekindReals.sig_not_dec : forall P : Prop, {~ ~ P} + {~ P}
    ClassicalDedekindReals.sig_forall_dec : forall P : nat -> Prop,
                                            (forall n : nat, {P n} + {~ P n}) ->
                                            {n : nat | ~ P n} +
                                            {forall n : nat, P n}
    FunctionalExtensionality.functional_extensionality_dep : 
    forall (A : Type) (B : A -> Type) (f g : forall x : A, B x),
    (forall x : A, f x = g x) -> f = g
    ```
1. [Tricks with Identity Coercions](https://www.codewars.com/kata/5e193501bbc85d002c6a6d52)
    ```
    (?a : A) : C true
        : C true
    where
    ?a : [ |- A]
    success!
    I
        : True
    fun a : Preloaded.A => a : Preloaded.C true
        : forall _ : Preloaded.A, Preloaded.C true
    ```
1. [Verified Sorting Algorithms - Bubblesort](https://www.codewars.com/kata/5d208ab62cf48200299d55c2)
    ```
    <ERROR::>Cannot find a physical path bound to logical path matching suffix<:LF:><> and prefix TLC.<:LF:>File "./Solution.v", line 3, characters 24-34
    ```
1. [Verified Sorting Algorithms - Mergesort](https://www.codewars.com/kata/5d309eab3d9880002265aeed)
    ```
    <ERROR::>Cannot find a physical path bound to logical path matching suffix<:LF:><> and prefix TLC.<:LF:>File "./Solution.v", line 2, characters 24-34
    ```

**Comment by DonaldKellett** [comment]
[Kata QA page](https://github.com/codewars/codewars.com/wiki/List-of-Coq-Kata-to-update-to-Coq-8.11.0) created

**Comment by kazk** [comment]
Yeah, Coq 8.9 won't be removed for now.

Coq 8.11 is not available on preview yet. I just built the image locally to try.

Is it possible to remove `coq-tlc` dependency? It doesn't seem to have a version that works with Coq 8.11 so I won't be including it.

**Comment by DonaldKellett** [comment]
Sure, `coq-tlc` didn't seem to be a particularly popular library from the beginning anyway and now it's unmaintained so I don't see why we should keep it for 8.11. Though I'd prefer it to be kept for Coq 8.9 for now so my affected Kata won't break in the meantime.

**Comment by kazk** [comment]
Deployed Coq 8.11.
