### ISSUE TITLE
Increase Coq 8.11 timeout to 16 seconds

### ISSUE THREAD

**Issue by monadius** [codewars/codewars-runner-cli#800]
When I updated [this](https://www.codewars.com/kata/5d2bd8e414a6ef001a0421d2/coq) kata, I observed that it times out frequently with Coq 8.11. The new version of Coq takes more time to analyze dependencies when checking assumptions (it happens with the plugin `CWAssert Assumes` and with `Print Assumptions`).

**Comment by kazk** [comment]
Deployed the change
