### ISSUE TITLE
TypeScript 3.8 target is ES2017

### ISSUE THREAD

**Issue by error256** [codewars/codewars-runner-cli#801]
TypeScript 3.8 uses Node 12, so it there a reason why the target isn't ES2019?
https://www.codewars.com/kumite/5e831051c97b570023ea73e4
`console.log('flat' in Array.prototype);` => `true`
`console.log([].flat());` => `main.ts:2:16 - error TS2339: Property 'flat' does not exist on type 'never[]'.`

**Comment by kazk** [comment]
No, I had just overlooked. I'll update.
