### ISSUE TITLE
Nim tests incorrectly shown as passing when actually faliing

### ISSUE THREAD

**Issue by hlaaftana** [codewars/codewars-runner-cli#806]
#### Describe the bug

When using check(), Nim checks are counted as passing instead of failing even when they're wrong.

#### To Reproduce

Do check(false) in Nim and check the test results

#### Expected Behavior

It should be shown as a failure

#### Screenshots

![image](https://user-images.githubusercontent.com/10591326/79745075-29124500-8310-11ea-9036-c297934ac510.png)

**Comment by Voileexperiments** [comment]
@kazk I found a way to reproduce this: whenever `check` is called inside another function called inside `test` block this happens. For instance:

Code:
```
proc multiply*(a, b: int): int = a + b
```

Test:
```
proc testing(a: int, b: int) = check(a == b)

suite "multiply":
  test "multiply(1, 1)":
    check(multiply(1, 1) == 1)
  test "multiply(1, 2)":
    testing(multiply(1, 2), 2)
```

Result:
![image](https://user-images.githubusercontent.com/14909989/80074585-f8cede80-857b-11ea-936d-7b3ea57ff968.png)

**Comment by kazk** [comment]
https://github.com/codewars/codewars.com/issues/1087#issuecomment-325178981 ?

**Comment by Voileexperiments** [comment]
Oh, so there's no way to easily use wrap testing inside another procedure. Guess I'll have to actually rewrite the test code then.
