### ISSUE TITLE
Add Dart 2.8

### ISSUE THREAD

**Issue by cachapa** [codewars/codewars-runner-cli#807]
- Name: Dart
- Version: 2.8
- Release Note/Changelog:

Dart is evolving very quickly and it's sometimes frustrating not being able to use some of the newer features, especially those that make it a lot more convenient to write simple solutions to many katas. 

Among them:
* The spread operator `...`
* Null-safe operators
* Using `if` in collection literals
* Binary operators on booleans
* Extension methods

I suspect the upgrade will be straightforward since 2.7 should be fully backward compatible with the existing Dart 2.1 implementation.

---

:+1: reaction _might_ help.

**Comment by kazk** [comment]
Deployed. All kata seems to be compatible.
