### ISSUE TITLE
Add Rust 1.44

### ISSUE THREAD

**Issue by entropicdrifter** [codewars/codewars-runner-cli#808]
Please complete the following information:

- Version: 1.44
- Release Note/Changelog: Adds [a lot of quality of life features](https://blog.rust-lang.org/2020/03/12/Rust-1.42.html), and most importantly would allow the use of the new (as of 1.39) async/await paradigm for parallel processing.

**Comment by kazk** [comment]
Deployed. All challenges seems to be compatible with 1.44.
