### ISSUE TITLE
Add Crystal 0.34

### ISSUE THREAD

**Issue by error256** [codewars/codewars-runner-cli#811]
https://crystal-lang.org/blog/#release_notes
Lots of things have changed since the version that's currently on Codewars, among them: `/` is floating point division now, `//` is integer division; usual arithmetic operators are checked by default and there are separate wrapping operators.

---

- [x] Rewrite Spec formatter (https://github.com/codewars/crystal-spec-codewars-formatter)

**Comment by Steffan153** [comment]
I've been wanting this for a while, but I was too lazy to request it ;)

**Comment by kazk** [comment]
Deployed. We have 103 kata to update: https://github.com/codewars/codewars.com/wiki/List-of-Crystal-Kata-to-Update
