### ISSUE TITLE
Update Python math/scientific libraries

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars-runner-cli#812]
The math/scientific libraries are outdated:

| Library | Latest v. | Installed v. |
| - | - | - |
| numpy  | 1.18.3 | 1.14.0 |
| scipy | 1.4.1 | 1.0.0 |
| pandas | 1.0.3 | 0.22.0 |

They're almost unused, but it'd still be good to update these after migrating to Python 3.8 as well.

**Comment by kazk** [comment]
Deployed. See #771.
