### ISSUE TITLE
`mcheck` breaks every C kata in new language version

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars-runner-cli#813]
When I was investigating [this](https://github.com/Codewars/codewars.com/wiki/List-of-C-Kata-to-Update) I found that currently `mcheck` always breaks in Clang 8/C18, even in a minimal example:

```c
#include <criterion/criterion.h>
#include <mcheck.h>

Test(one, test) {
    cr_assert_eq(1, 1);
}
__attribute__((constructor(101))) static void init() {
  mcheck(NULL);
}
```

This results in error code 139 after all tests are run:

![image](https://user-images.githubusercontent.com/14909989/80314350-a7e11380-8823-11ea-9bdd-0be70b67dd5f.png)

So currently `mcheck` is completely unusable.

**Comment by error256** [comment]
https://github.com/Snaipe/Criterion/issues/196

**Comment by kazk** [comment]
Closing because we can't do anything about this unfortunately.
