### ISSUE TITLE
Add Lean v3.11.0 (with mathlib)

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/codewars-runner-cli#815]
Please complete the following information:

- Name: Lean
- Version: [v3.11.0](https://github.com/leanprover-community/lean/releases/tag/v3.11.0) with [mathlib commit 51e2b4ccef20e49bc24ef86a6afe6e48196abbcf](https://github.com/leanprover-community/mathlib/commit/51e2b4ccef20e49bc24ef86a6afe6e48196abbcf)

To install, just create a new project using `leanproject new` and it should use the most recent version of Lean + mathlib (as above, at the time of writing) automatically.

---

:+1: reaction _might_ help.

**Comment by DonaldKellett** [comment]
Also, when displaying supported versions of Lean:

- In the Wiki: display the full mathlib commit as well, e.g.
  1. Lean v3.7.2 with mathlib commit ecdb13831d4671eb304c41e78adb5b280c2fc365
  1. Lean v3.11.0 with mathlib commit 51e2b4ccef20e49bc24ef86a6afe6e48196abbcf
- In the trainer when selecting language version: display the first 7 hex digits of the mathlib commit as well, e.g.
  1. 3.7.2 with mathlib (ecdb138)
  1. 3.11.0 with mathlib (51e2b4c)

**Comment by kazk** [comment]
Maybe we can try updating every 2 months or so. But Codewars will only support at most two Lean versions at the same time. The community is responsible for updating the existing content to the newer version before adding the next version.

I've tested `3.11.0+51e2b4c` locally and found some incompatible kata so I'll create a wiki page like other languages.

**Comment by kazk** [comment]
Created https://github.com/codewars/codewars.com/wiki/List-of-Lean-Kata-to-Update

**Comment by DonaldKellett** [comment]
Thanks for adding the Wiki page!

Due to the rapid development of Lean + mathlib, I don't think it is reasonable to ask for updates in a backwards-compatible manner. Perhaps we should just deploy 3.11.0 support and start updating straight away?

**Comment by kazk** [comment]
I created that page so that you guys can start updating if possible. Then all compatible kata will get 3.11.0 enabled automatically when I deploy it.
If it's not possible, then that's fine. You just update to 3.11.0 dropping 3.7.2 support once it becomes available on Codewars.

I'll close this issue when I deploy.

**Comment by kazk** [comment]
Deployed. We can move Lean out of beta once the update is done.
