### ISSUE TITLE
Add possibility to use scala testing frameworks for java solutions

### ISSUE THREAD

**Issue by oybek** [codewars/codewars-runner-cli#817]
My main language is scala and I create katas using scala.

Very popular language on codewars is java, and I usually translate my katas to it.

In order to minimize amout of work when creating kata I'm requesting in this issue
to add possibility to test java solutions using ScalaTest in scala, it is possible out of box,
since any java class could be used in scala code, and there are java to scala collections
converters

This feature will speed up kata translations amount, and will be very helpful for codewars community

Author: https://www.codewars.com/users/oybek

**Comment by kazk** [comment]
Closing as wontfix. Currently Codewars can only have one test framework per language and we also have completely separate environments for each language and language version environments. It's also often required to adjust the tests based on the performance of the language (including the time to compile).

The opposite is _somewhat_ possible on Qualified (JUnit in Scala) so maybe that can happen in the future on Codewars once it allows test frameworks to be configurable. You'll still need to adjust the syntax though.
Looking back, maybe it was better to use JUnit for Scala on Codewars, but ScalaTest performed much better in the setup we used to have.
