### ISSUE TITLE
C++ : updated kata to Clang8C++17 passed by function without body

### ISSUE THREAD

**Issue by g964** [codewars/codewars-runner-cli#820]
@kazk 
Could you have a look at: <https://www.codewars.com/kata/566fc12495810954b1000030/discuss/cpp>
post by @gkontadakis. Someone updated the kata to Clang8C++17.

I tried <https://www.codewars.com/kata/5518a860a73e708c0a000027/train/cpp> too with a function without body and this solution also passed.
Same with a few others I tried. All we get are "STDERR" but it get passed.

I don't understand what happens:-(

**Comment by kazk** [comment]
Looks like the `-O2` flag that was added is messing with the test framework. If I remove that flag, the test fails the same way as C++14 version with exit code `132` (Illegal Instruction).

For "Last digit of a huge number", solution without body crashes in random tests (segfaults).

**Comment by g964** [comment]
> For "Last digit of a huge number", solution without body crashes in random tests (segfaults).

But passes "TEST".

**Comment by kazk** [comment]
I know, I'm just listing my observations. It seems to be caused by `-O2` flag like I wrote above.

**Comment by error256** [comment]
Not returning a value from a function is undefined behavior, which gives the compiler freedom to do anything, not necessarily to return an unspecified value, so, apparently, the function has been optimized to always return what is expected (and Clang is known for sophisticated optimization as in famous https://kristerw.blogspot.com/2017/09/why-undefined-behavior-may-call-never.html). So it's not like something is wrong with the framework. I'm not sure what can be done about it though...

**Comment by g964** [comment]
Amongst the kata I tried some pass and some rightly fail.

**Comment by kazk** [comment]
Yeah, you usually don't have optimization flag on while testing/developing. Most languages on Codewars doesn't have optimization/production flag on.

@g964 Why not just provide valid initial solution?

```cpp
#include <list>

using namespace std;
int last_digit(list<int> array) {
  // Write your code here
  return 0; // <- added
}
```
This won't prevent users submitting by removing that line, but it should prevent accidental ones.

**Comment by error256** [comment]
I think a wrapper with noinline may work, like
```cpp
[[gnu::noinline]]
int last_digit_wrapper(list<int> array) {
  return last_digit(array);
}
```
It seem that it works even without noinline in this kata, but it's probably less reliable.

**Comment by kazk** [comment]
> Amongst the kata I tried some pass and some rightly fail.

Maybe those that fails have `dotest` wrapper that you often use?

**Comment by g964** [comment]
I didn't try any others kata of mine except the first I mentioned in my first post.

**Comment by error256** [comment]
https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html
Compiling with `-fsanitize=return` should help too.

**Comment by kazk** [comment]
@error256 Nice find! The kata fails with
```
main.cpp:9:5: runtime error: execution reached the end of a value-returning function without returning a value
```

I still think a valid initial solution returning the empty value should be provided though. So add `return {};`/`return 0;`/`return std::string();` whatever that makes sense.

**Comment by kazk** [comment]
Deployed the fix.
