### ISSUE TITLE
Add bit_set to rust

### ISSUE THREAD

**Issue by ArikDavidov** [codewars/codewars-runner-cli#823]
Please complete the following information about the package:

- Name: Add bit_set to rust
- Language Name: rust
- Website: https://docs.rs/bit-set/0.5.0/bit_set/struct.BitSet.html

Following are optional, but will help us consider adding:

- Why is this useful?
 "Validate Sudoku with size `NxN`" kata
- Example Code:
```
use bit_set::BitSet;

fn main() {
    let mut set = BitSet::with_capacity(64);
    set.insert(42);
    println!("{:?}", set)
}
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0fe557ff4e7f998f25235fa86af4a4bb
---

:+1: reactions _might_ help.

**Comment by kazk** [comment]
Deployed. Make sure to select Rust 1.44 to use it.
