### ISSUE TITLE
Add Lean 3.16.3

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/codewars-runner-cli#824]
Please complete the following information:

- Name: Lean
- Version: [3.16.3](https://github.com/leanprover-community/lean/releases/tag/v3.16.3)
- Remarks: I've heard that mathlib compiles twice as fast in 3.16.x compared to 3.11.x so hopefully we'll be able to migrate [Real Chebyshev](https://www.codewars.com/kata/5d2bd8e414a6ef001a0421d2/lean) to 3.16.x this time?

---

:+1: reaction _might_ help.

**Comment by kazk** [comment]
At first, I thought 2 months have passed already, but it's been only a month. I wrote maybe update every 2 months or so (https://github.com/codewars/codewars-runner-cli/issues/815#issuecomment-628224563). That's already a lot more frequent than other languages.

But if it's really that much faster, then I'll consider making this an exception so that we can remove the old version.

**Comment by DonaldKellett** [comment]
> But if it's really that much faster, then I'll consider making this an exception so that we can remove the old version.

Yeah, they have a new minor version every week and mathlib is ever evolving (-:

**Comment by kazk** [comment]
? I meant faster as in performance and not how fast (frequent) they release.

Can someone compare the performance of Real Chebyshev?

Also posting leanpkg.toml here would help.

**Comment by jorendorff** [comment]
I just tried submitting https://www.codewars.com/kata/5ea1f341014f0c0001ec7c5e/ with no code in it at all. Just `import Preloaded` fails with "Execution Timed Out (20000 ms)". The kata is unsolveable.

I'm not sure upgrading Lean will help, but it takes about 2 seconds to check my solution locally (on a laptop, not a particularly fast machine).

**Comment by DonaldKellett** [comment]
@jorendorff [Uniqueness of limits in a metric space](https://www.codewars.com/kata/5ea1f341014f0c0001ec7c5e/) is indeed very close to the timeout limit in 3.11.0. If you have a working solution to it locally then try re-submitting your solution on Codewars until it passes. From my previous experience trying to upgrade the kata to 3.11.0 it works maybe about 1 in 10 times.

**Comment by DonaldKellett** [comment]
Closing in favor of Lean v3.18.2
