### ISSUE TITLE
CW Haxe 4.0 doesn't have Int64

### ISSUE THREAD

**Issue by g964** [codewars/codewars-runner-cli#826]
CW Haxe has no Int64: `5317636 * 2306` gives -622433272 instead of `12262468616`. It seems Haxe 4.1.2 has them.

**Comment by kazk** [comment]
Haxe 4.0 seems to have Int64 too. https://api.haxe.org/v/4.0.0/haxe/Int64.html

Not sure why I get `Type not found : Int64` :/

**Comment by kazk** [comment]
You need to import `haxe.Int64`.

```haxe
import utest.Assert;
import haxe.Int64;
import Solution;

class SolutionTest extends utest.Test {
  function testExample() {
    var expected = Int64.fromFloat(5317636) * Int64.fromFloat(2306);
    Assert.same(expected, Example.multiply(Int64.fromFloat(5317636), Int64.fromFloat(2306)));
    Assert.equals("12262468616", Int64.toStr(expected));
  }
}
```

**Comment by g964** [comment]
I had gotten `Type not found : Int64 ` too. Is the CW platform 64 bits or 32 bits?
