### ISSUE TITLE
Exit code is 0 when crashing with memory error with Node 12

### ISSUE THREAD

**Issue by rge123** [codewars/codewars-runner-cli#829]
#### Describe the bug

Kata: <a href="https://www.codewars.com/kata/5f0ed36164f2bc00283aed07/javascript"> Over The Road</a>
JavaScript node 12.

Some solutions are being regarded as correct by the test framework, even though they don't pass all tests. There are 2000 tests with integers up-to 5e11. Some solutions utilise lists, and produce a memory error; however, instead of failing the tests, the framework crashes and says you pass.

#### To Reproduce

```javascript
function overTheRoad(address, n){
  let impar = [];
  let par = [];
  let result = [];
  for (let i = 1; i <= n * 2; i++) {
    if (i % 2 !== 0) {
      impar.push(i);
    } else if (i % 2 === 0) {
      par.push(i);
    }
  }
  impar.sort((a, b) => b - a);

  for (let j = 0; j < impar.length; j++) {
    if (address === par[j]) {
      result.push(impar[j]);
    } else if (address === impar[j]) {
      result.push(par[j]);
    }
  }
  return result[0];
}
```

#### Expected Behavior

This code should timeout or produce a memory error AND then not unlock the kata.

#### Screenshots

There are 6 small tests and another c.2000 large random tests. When the above code is used, this happens:
![image](https://user-images.githubusercontent.com/68327328/89561323-3b0cea80-d810-11ea-8f0f-44a4b5ee5dd9.png)

![image](https://user-images.githubusercontent.com/68327328/89561348-45c77f80-d810-11ea-8c88-4d764c4c5d45.png)

As you can see the submit button is available. It says you pass all tests even though there is a fatal error.

**Comment by FArekkusu** [comment]
This happens under Node 12 only - the tests fail with non-zero error code when other Node versions are used.

I've noticed that the message written to `stderr` is different, maybe that's the cause of the problem?

* `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory` - produced by Node 8, Node 8/Babel, Node 10 (left half of the image)
* `FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory` - produced by Node 12 (right half of the image)

![image](https://user-images.githubusercontent.com/31668662/89563879-d1e3a200-d824-11ea-9338-f995826764bf.png)

___

Also, quick copy-paste example:

```
function f(n) {
  let a = [];
  while (n--) a.push(0);
  return a.length;
}


const {assert} = require("chai");

describe("Tests", function() {
  it("Small tests", () => assert.equal(f(1), 1));
  it("Big tests",   () => assert.equal(f(1e10), 1e10));
});
```

**Comment by kazk** [comment]
Thanks @FArekkusu. I'll look into it. Mocha version was updated so that might be the cause of the difference.

**Comment by kazk** [comment]
Weird. I can only reproduce this inside a container :/

This happens when running it manually so it's not the runner.

**Comment by kazk** [comment]
I think I found the cause.

We use `pnpx mocha` (from [pnpm](https://pnpm.js.org/)) to run the tests and the exit code is 0 inside a container. If I change that to `./node_modules/.bin/mocha` then the exit code is 134.

Node 10 also uses `pnpx mocha`, but with different versions of pnpm and mocha.

**Comment by kazk** [comment]
I was able to reproduce with [`npx`](https://github.com/npm/npx) as well, but I'm not sure the exact cause. I'll just change to `./node_modules/.bin/mocha`.

**Comment by kazk** [comment]
Deployed

**Comment by rge123** [comment]
Thanks &#128077;
