### ISSUE TITLE
CFML: java.lang.VerifyError:Expecting a stackmap frame at branch target

### ISSUE THREAD

**Issue by error256** [codewars/codewars-runner-cli#832]
Trying to execute a piece of CFML code throws a Java exception:
```
java.lang.VerifyError:Expecting a stackmap frame at branch target 14
Exception Details:
  Location:
    solution_cfc$cf.initComponent(Llucee/runtime/PageContext;Llucee/runtime/ComponentImpl;Z)V @7: ifeq
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 013a 042c b600 6299 0007 01a7 0007 2bb6
    0x0000010: 002f 3a05 2c2b 2a1d b600 661d 9a00 0a2b
    0x0000020: 1905 b800 69b1 2bb6 0033 03b9 0039 0200
    0x0000030: 3606 2c2b b600 6c3a 042c 2ab4 0070 0332
    0x0000040: 2ab4 0074 0332 b600 782c 2b2a b600 7c01
    0x0000050: a700 2c3a 072b 1905 b800 4719 07b8 004d
    0x0000060: bfa7 001b 3a08 2bb6 0033 1506 b900 3902
    0x0000070: 0057 2c2b 1904 b600 7f19 08bf 2bb6 0033
    0x0000080: 1506 b900 3902 0057 2c2b 1904 b600 7f2b
    0x0000090: 1905 b800 69b1                         
  Exception Handler Table:
    bci [50, 80] => handler: 83
    bci [50, 97] => handler: 100
```
Code:
https://www.codewars.com/kumite/5f46aaada098c1001964d2f3?sel=5f46aaada098c1001964d2f3
```cfml
component {
    function foo() {
        var x = 0;
        if (false) x \= 1;
    }
}
```
```cfml
component extends="CodewarsBaseSpec" {
    function beforeAll() {
        createObject('Solution');
    }
}
```
This is some very narrow case: any operator other than `\=` works and `x \= 1` works outside of `if` too.

**Comment by kazk** [comment]
@bdw429s Any idea what's causing this?

**Comment by bdw429s** [comment]
@kazk You know I just got this same exception last week in some code using the safe navigation operator (`.?`) and I'm fairly sure it's a bug in the underlying bytecode compiler of the CF Engine that only manifests in certain scenarios.   I didn't create a ticket for the issue I hit the other day.  Honestly, I forgot about it, but if there's a standalone repro case that throws this error, I can make sure a ticket gets entered in the Lucee Server issue tracker.  

As far as what codewars can do-- there's nothing really.  It's a low level compilation error in the CF engine itself.  The user will simply need to avoid the problematic code for the time being.

**Comment by bdw429s** [comment]
https://luceeserver.atlassian.net/browse/LDEV-3020

**Comment by kazk** [comment]
Thanks for filing the ticket and the TryCF link. I noticed Adobe CF 2018 fails with `Invalid CFML construct found on line 3 at column 15. on line 3` there :/

@error256 I'll close this because we can't do anything about it.

**Comment by bdw429s** [comment]
It doesn't appear that Adobe CF has a compound integer division operator:
https://helpx.adobe.com/coldfusion/developing-applications/the-cfml-programming-language/using-expressions-and-number-signs/expressions-developing-guide.html

Ironically, the compound integer division operator is not in Lucee's docs even though it does appear to be implemented:
https://docs.lucee.org/guides/developing-with-lucee-server/operators.html
