### ISSUE TITLE
Add rest api documentation. 

### ISSUE THREAD

**Issue by konczdam** [Codewars/codewars-runner-cli#841]
On the dockerhub page of the project it says: 
> You can run a server which wraps the CLI and runs it within a Docker container. If you have Docker installed on your machine and the Codewars image built, all you need to do to start the server is run node server. You can then make posts requests to localhost:8080/run and provide the same arguments that you would for the CLI tool.

I am can run the server, and make the request, however, I am unable to get any successful response. Can anybody add an example request?

**Comment by kazk** [comment]
The image ([codewars/codewars-runner](https://hub.docker.com/r/codewars/codewars-runner)) was last pushed almost 5 years ago.

> the dockerhub page of the project

I wasn't involved with the project back then, but I don't think the source of that image is this repository. It sounds like there was never an open source REST API (https://github.com/codewars/codewars-runner-cli/issues/384).

Sorry for the confusion, but the code in this project hasn't been used by us for almost 3 years as well. We're only using it as an issue tracker.
