### ISSUE TITLE
Scala support

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars-runner-cli#9]

**Comment by buaya91** [comment]
may I know is there any update on this? is there anything I can help?

**Comment by mikla** [comment]
Is there any progress with Scala support? What kind of help do you need?

**Comment by Kavignon** [comment]
Once I'm done with .net,  I'll tackle this from scratch I guess? It'll give a chance to learn about Scala :D @jhoffner is that good for you? Doing so,  I plan to turn in at least 3 languages over the summer,  bringing more options for devs all around

**Comment by IvanovPvl** [comment]
+1 for Scala support
