### ISSUE TITLE
Separate docker files

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars-runner-cli#99]
The single Docker file has gotten out of control. At this point we end up having to rebuild most if not all of the thing too often. This causes space issues as well as upload issues since all of the old stuff can't be re-used. I want to try to group common sets so that we don't have 20 images to manage. Here is what I am thinking:
### Base Image:
- ENV config
- setup codewarrior user
- common services (redis, mongo, sqlite, elasticsearch, etc)
- any packages commonly used by installers (python libs, node, etc). 
### Node Image
- node
- coffeescript
- typescript
- npm packages
### Ruby Image
- ruby
- gems
- run ruby tests
### Python Image
- python 2
- python 3
- language packages
- run python tests
### .NET Image
- c#
- f#
- dlls
- c#/f# language tests
### JVM Image
- java
- groovy
- clojure
- scala
- language packages
- JVM runner
- run jvm language tests
### Systems image
- c
- c++
- asm/arm
- language packages
- ?
- language specific tests
### Lispy Image
- Lisp
- Racket
- OCaml
- Haskell
- language packages
- tests
### Alt Languages Image (less commonly used)
- R
- Rust
- Erlang
- Elixir
- Go
- Julia
- Lua
- language packages
- tests

We would deploy the runner to all of the non-base images just as it is today. The only difference is that the server will need to pick the image based off of the language provided. We will also need to update the build, pull and push utilities to do all of the image magic for us.

**Comment by xcthulhu** [comment]
Hi Codewars/codewars-runner,
A message from Matthew Wampler-Doty was left on IQ Elite for you. 
Click here a.iqelite.com/j/0JmRlo/xei/?hg=PoO4syC8qA to read your message 


The IQ Elite Team



---------------------------------------------------------------------------
This message was meant for reply@reply.github.com. If you do not want to continue receiving such mails from IQ Elite, please click on this link: a.iqelite.com/common/unsubscribe/?code=bb01a65d&email=reply@reply.github.com&hg=PoO4syC8qA
IQ Elite is a service with main office: C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelona, Spain.
---------------------------------------------------------------------------
